modules/soc_i3/main.sh
Da hatten sich irgendwie ein paar Fehler eingeschlichen.
=> Modul soc_i3 korrigiert

README.md, evsedintest.sh, modules/soc_leaf/leaf.py, modules/soc_leafs1/leaf.py, openwb.conf, regel.sh, runs/atreboot.sh, web/index.php, web/settings.php
Lademenge 0 einstellbar, Leaf SoC Url geändert, regular Modbus check, OpenWB Duo 16A Mode
=> 1.096 beta

modules/soc_carnet/main.sh, modules/soc_carnet/soc.sh, modules/soc_carnet/vw_carnet_rb1.py, openwb.conf, runs/atreboot.sh, web/modulconfig.php, web/tools/savemodul.php
VW Carnet hinzugefügt, SoC i3 LP2 intervall hinzugefügt
=> VW Carnet hinzugefügt, SoC i3 LP2 intervall hinzugefügt

modules/wr_smartme/main.sh
Der Ordnername passt jetzt zur übrigen Struktur. Auslesen und Berechnen der Werte optimiert.
=> Modulorder umbenannt in wr_smartme. Kleine Korrekturen.

modules/wr_smartme/main.sh
Die Werte fürs Logging werden jetzt korrekt übergeben.
=> Update wr_smartme. Werte für Logging korrigiert.

modules/bezug_smartme/main.sh
Die Daten für das Logging werden jetzt richtig übergeben.
=> Update bezug_smartme. Werte fürs Logging korrigiert.

modules/bezug_fronius_sm/main.sh, modules/speicher_fronius/main.sh, runs/set-current.sh, web/index.php, web/modulconfig.php, web/tools/savemodul.php
WR Fronius Symo Speicher Modul
=> 1.105 Beta

modules/bezug_fronius_sm/main.sh, modules/simpleevsewifis2/main.sh, modules/wr_fronius/main.sh, nachtladen.sh, web/index.php
SimpleEVSEWifi LP3 Typo Bugfix, Nachtladen keine Erhöhung um 1 A vor LM Grenze, Bezug Fronius SM Bugfix
=> 1.106 beta

modules/sdm120modbusll/main.sh, modules/wr_solardege/solaredge.py, nurpv.sh, regel.sh, runs/atreboot.sh, web/index.php, web/logging/graph-live.php, web/modulconfig.php, web/settings.php, web/tools/savemodul.php
Solaredge multiplier 0 Bugfix
SDM630 source bugfix
graph ui fix
ui farben fix
loadsharing 16a fix
=> 1.107 beta

graphing.sh, modules/speicher_solaredge/main.sh, modules/speicher_solaredge/solaredge.py, modules/wr_tripower9000/tri9000.py, openwb.conf, regel.sh, runs/atreboot.sh, runs/cron5min.sh, runs/cronnightly.sh, web/graph-live.php, web/index.php, web/ladelog.php, web/logging/graph-daily.php, web/logging/graph-live.php, web/logging/graph-monthly-ev.php, web/logging/graph-monthly-evu.php, web/logging/graph-monthly-pv.php, web/logging/graph-monthly.php, web/misc.php, web/modulconfig.php, web/settings.php, web/tools/savemodul.php, web/tools/savesettings.php
SMA WR catch negative Watt, Solaredge speicher modul, Logging SoC LP2 Added & Ui Fix, Zoe Passwort escaped
=> 1.201 beta

loadvars.sh, nurpv.sh, runs/atreboot.sh, web/graph-live.php, web/index.php, web/ladelog.php, web/logging/graph-daily.php, web/logging/graph-live.php, web/modulconfig.php, web/settings.php
-Speicher minimum chargewatt
- Logging Standby added
- PV start charging delay added
- Graphing Bugfix
=> Beta 1.27 

web/graph-live.php, web/index.php
=> Beta 1.271

regel.sh, web/graph-live.php, web/hilfe.html, web/index.php, web/modulconfig.php
Live Graph Mainsite Bugfix, Slow mode enhanced, BMW SoC Info enhanced
=> Beta 1.274

modules/wr_tripower9000/main.sh, web/index.php
=> Beta 1.303

modules/keballlp1/main.sh, modules/keballlp2/main.sh, web/index.php, web/logging/graph-dailye.php, web/misc.php, web/tools/savemodul.php
=> Beta 1.351

web/themes/dark_gauges_1/index.html, web/themes/dark_gauges_1/updateGauges.js
Anpassung der Skalierung korrigiert, Skalierung jetzt auch bei sinkenden Leistungswerten.
=> Gauges bugfix und add feature

modules/soc_i3/main.sh
Prüfung ob Push aktiv ergänzt und Logik getauscht um Fehlalarm zu vermeiden.
=> Update main.sh soc_i3

index.html, web/themes/dark_gauges_1/updateGauges.js
Page redirect bei Aufruf der verkürzten URL funktionierte nicht und Update Gauges nur bei Wertänderung
=> Bugfix und Performance

web/themes/dark_gauges_1/index.html, web/themes/dark_gauges_1/updateGauges.js
Nimmt etwas die Hektik aus der Anzeige, wenn Wolken durchziehen oder der Hausverbrauch wegen Backofen etc. periodisch schwankt.
=> Zeit für Anpassung Gauge-Skala verlängert, Code umgestellt

web/setTheme.php
... otherwise it is not possible to reach the module configuration site from the theme site.
=> Small fix.

web/tools/savemisc.php
Einstellung zur Pushbenachrichtigung speichern.
=> PushPlug savemisc.php

web/misc.php
Einstellungen Misc um Einstellungen zu Pushbenachrichtigung beim Einstecken erweitert.
=> PushPlug misc.sh

loadvars.sh
Pushbenachrichtigung bei eingestecktem Fahrzeug bei verzögertem Ladestart.
=> PushPlug loadvars.sh

modules/bezug_solarview/main.sh, modules/solarview/main.sh, modules/wr_solarview/main.sh, openwb.conf
OpenWB-Module für die [Anbindung von SolarView](https://openwb.de/forum/viewtopic.php?f=5&t=497)
=> Anbindung von SolarView

runs/atreboot.sh, runs/update.sh, web/version
=> Beta 1.65b

loadvars.sh, runs/mqttpub.py, runs/pubmqtt.sh
Improving MQTT publish performance by submitting a list of topic-value-pairs via Python.
The approach using "mosquitto_publish" creates a new TCP connection to the MQTT broker for every single operation.
I've tested the code on my OpenWB series 2 with 1 LP.
I hope you find it useful and it helps.
=> Improving MQTT publish performance by submitting a list of topics

graphing.sh, web/index.php, web/js/livechart.js, web/themes/standard/index.html, web/themes/symbol/index.html, web/version
LiveGaph library changed to chart.js Bugfix
=> Beta 1.68c

graphing.sh, modules/simpleevsewifi/main.sh, web/index.php, web/js/livechart.js, web/live.js, web/misc.php, web/themes/standard/index.html, web/themes/symbol/index.html, web/version
- Livegraph lädt automatisch neu beim Seitenaufruf und in der PWA
- Overlay für Graph Einstellungen
- Steckererkennung für SimpleWifiEVSE an Ladepunkt 1
- Bis zu 2 Stunden Livegraph einstellbar
=> Beta 1.68e

runs/mqttsub.py, web/index.php, web/js/livechart.js, web/live.js, web/settings.php, web/themes/standard/index.html, web/themes/symbol/index.html, web/version
=> Beta 1.683

runs/smashm.sh, web/tools/savemodul.php
Hi,
I did a few small fixes for handling the SMA HM stuff on updates. 
- Update SMA-EM daemon properly
- Update smaemd config file properly
=> Fix handling of SMA HM on updates

web/themes/dark19_01/theme.html, web/themes/standard/theme.html
easier to switch on/off charge points on mobiles by touching the symbol or charge point name
=> more space between charge point info lines on small screens

web/settings/misc.php, web/settings/setTheme.php
Fix: falsche anzeige des Pfads im Footer einzelner Einstellung-Pages
=> fix footer text

processautolock.sh, regel.sh, runs/atreboot.sh, web/settings/autoLock.php, web/tools/saveautolock.php
needs reboot so files are created in Ramdisk through at reboot.sh
=> alpha2 autolock

web/settings/autoLock.php
- allg. Bugfix
- Überprüfung Benutzereingabe, keine identischen Schaltzeiten je Tag mehr möglich
- Layout Checkbox "sperren erst nach Ladevorgang" verändert
=> fix autolock ui

processautolock.sh, web/settings/debugging.php, web/settings/misc.php, web/settings/navbar.php, web/settings/setTheme.php, web/settings/update.php, web/tools/savemisc.php, web/tools/saveupdate.php, web/tools/senddebug.php, web/tools/updateredirect.html
alter Menüpunkt "misc" aufgeräumt
neuen Menüpunkt hinzugefügt
Benutzerführung verbessert
=> new menu structure

modules/bezug_lgessv1/main.sh, modules/speicher_lgessv1/main.sh, modules/wr_lgessv1/main.sh, runs/atreboot.sh, web/settings/modulconfig.php, web/tools/savemodul.php
LG changed array structure of JSON object.  To choose the API version, a flag was introduced in the commited source files. Modulconfig.php was modified for user friendly change of API by using a drop down menu.
=> Integration of LG API update

modules/bezug_smashm/sma-em-measurement.py
=> Watts müssen int sein

modules/bezug_smashm/sma-em-measurement.py
EVU Stromstärken (Phase 1/2/3) sollte negativ werden
=> SMASHM: Strom negativ bei Einspeisung

modules/wr_fronius/main.sh
Fixed a small bug that reads the total energy from the first inverter twice instead of building the sum of both inverters.
=> Bugfix of wr_fronius

modules/bezug_sonneneco/main.sh, web/settings/modulconfig.php
Mit dem Modul kann der Bezug durch die JSON-API eines Sonnen Eco Speichers ausgelesen werden.
=> Modul Bezug Sonnen eco

graphing.sh, web/logging/index.php, web/logging/logging_style.css, web/logging/longlivechart.js
added date to timestamp
changed algo so data-gaps will be flattened
some changes to gui
=> changes to longtime logging graph

web/logging/longlivechart.js
soc values at timeline gaps get filled in line with existing values in csv data so lines don't jump
=> avoid jumping lines at filled gaps

web/display/welcome.html, web/hilfe/navbar.php, web/ladelog.php, web/tools/update15.php
In `ladelog.php` habe ich ein  `</div>` vor dem Ende der `<section>` vergessen. Ansonsten noch kleine Korrekturen an der Einrückung. Die `welcome.html` ist nun auch validiertes HTML.
=> More cleanup

web/logging/monthlychart.js
bugfixes,
selected month always displayed with all days even if not fully logged
labels shortened for better readability
=> monthly graph bugfixes and improvements

web/logging/monthlychart.js
fixed bug that prevented correct parsing of mqtt-data-segments into graph-array
=> monthly graph bugfix

rfidtag.sh, runs/mqttsub.py, slavemode.sh
Fixes for full integration of slave mode.
=> Integration changes

web/index.php, web/settings/autoLock.php, web/settings/cloudconfig.php, web/settings/misc.php, web/settings/modulconfig.php, web/settings/navbar.php, web/settings/pvconfig.php, web/settings/settings.php, web/themes/standard/navbar.php, web/themes/standard/theme.php
This PR adresses some problems found with W3 html validator.
=> Fix validator warnings and errors

slavemode.sh
This is a first version of detecting and handling missing information from controller.
Please review.
=> Integrating heartbeat for slave mode

web/settings/pvconfig.php
Jetzt funktioniert die Anzeige des Speichers und der HTML Code ist validiert.
=> Fix Speicheranzeige in pvconfig

web/themes/standard/theme.php
Fix linebreak in input fields of standard theme.
JS visibility was broken.
=> fix standard theme

.gitignore, web/settings/cloudconfig.php, web/settings/misc.php, web/settings/modulconfig.php, web/settings/mqtt.php, web/settings/navbar.php, web/settings/pvconfig.php, web/settings/setPassword.php, web/settings/settings.php, web/settings/smarthome.php
Removed old JavaScript code and implemented separate page for setting http-auth.
=> Change Password Protection to basic http-auth

slavemode.sh
* proper equation when sum > total allowed (didn't handle floats properly and set wrong target value)
* proper rounding of negative adjustment (which is not needed as, due to parantheses, the value that is converted to int is always positive)
=> Slavemode fixes

web/themes/dark19_01/livechart.js
according to screen size:
- change quantity of x-axis-labels 
- change font-size of labels and ticks
- change line thickness of lines without filling
=> added some responsiveness to graph at dark theme

web/themes/dark19_01/processAllMqttMsg.js, web/themes/dark19_01/style.css, web/themes/dark19_01/theme.php
added row for openWB date/time-info, small adjustments to optical layout
=> added date/time to dark theme + small adjustments

web/settings/navbar.php, web/settings/setPassword.php
- Fixes cursor style when navbar element is not a link.
- fixes disabling navbar element for password protection
=> Navbar fixes in settings

web/settings/graphconfig.php, web/settings/processAllMqttMsg.js, web/settings/setupMqttServices.js, web/themes/dark19_01/livechart.js, web/themes/dark19_01/processAllMqttMsg.js, web/themes/dark19_01/theme.php
dark theme fertig, alte grab-einstellungen aus files entfernt
=> graph-einstellungen als page unter einstellungen per mqtt

rfidtag.sh
Major rework to be more generic and flexible
=> Reworked rfidtag.sh

rfidtag.sh, runs/atreboot.sh, runs/mqttsub.py, slavemode.sh
Extend slave mode to support multiple charge points and charging on multiple phases.
Minor correction to `rfidtag.sh` disabled debug output (missing null operator).
=> slave mode - multi lp, multi phase

web/themes/dark19_01/processAllMqttMsg.js, web/themes/dark19_01/theme.php
- Anzeige Datum/Uhrzeit getauscht (ist bei einem Commit zuvor vertauscht worden)
- Anzeige geladene km wenn Durchschnittsverbrauch am LP konfiguriert (>=0)
=> date/time fix & geladene km anzeigen

graphing.sh, loadvars.sh, nurpv.sh, regel.sh
=> Eliminiere wattbezugint

loadvars.sh, nurpv.sh, regel.sh, web/settings/pvconfig.php
=> 70% Regler setzt eigene Regelschwellen

web/settings/generalchargeconfig.html, web/settings/navbar.html, web/settings/processAllMqttMsg_generalchargeconfig.js, web/settings/pvconfig.html, web/settings/topicsToSubscribe_generalchargeconfig.js, web/settings/topicsToSubscribe_pvconfig.js
Kleines Delay vor redirect um Schreiben der Werte zu garantieren,
Allgemeine Einstellungen in "Übergreifendes" verschoben
=> Bugfix und Menüerweiterung

leds.sh
Support for controlling LEDs 1 & 2 in slave mode.
Hard-coded to indicate whether CP is enabled or disabled.
=> LED control in slave mode

rfidtag.sh, runs/mqttsub.py, slavemode.sh
Improvements and extensions to slave mode.
`rfidtag.sh` now allows plug-in before RFID scan for openWB single.
=> Slave mode changes

web/settings/cloudconfig.php, web/settings/modulconfig.php, web/settings/mqtt.php, web/settings/pvconfig_old.php, web/settings/setPassword.php, web/settings/settings.php, web/settings/smarthome.php
No comment - this caught my attention while setting up my new wallbox ...
=> fix: correct typo

web/themes/dark/processAllMqttMsg.js, web/themes/dark/theme.html
Attribute in data-attribute geändert und kleine Fixes/Ergänzungen
=> Small fixes

modules/bezug_lgessv1/main.sh, modules/speicher_lgessv1/main.sh, modules/wr_lgessv1/main.sh
Monthly growing array in json -> adaption of position in array for correct values neccesary. Old stuff (API version) is depricated and will be removed in next Update
=> Monthly array pos change bug 

web/themes/dark/theme.html
isNan liefert auch true bei leerem String, deswegen zuvor Umwandlung in Zahl
=> Fix isNan-Vergleich

slavemode.sh
Imbalance and control loop improvements in Slave mode.
=> Slave mode improvements and cleanup

web/themes/dark/processAllMqttMsg.js, web/themes/dark/theme.html
Leerzeichen fehlte, doppelte Variablendeklaration, Code zusammengefasst
=> Bugfixes, Code optimiert

loadvars.sh, runs/update.sh
Small change to make information of `ramdisk/mqttupdateinprogress` available to MQTT clients.
=> Update in progress via MQTT

hook.sh
Bugfix - Jetzt wird der Verbraucher2 auch im Graph auf der Home Seite angezeigt
=> Fix: Verbraucher2 wird jetzt auch im Graph angezeigt

slavemode.sh
Correct Slave mode when Allowed Total Current changes.
=> Slavemode total current limit fix

web/themes/dark/style.css, web/themes/dark/theme.html, web/themes/standard/style.css
- unified css files for dark and standard themes
- cleanup of mixed line indentation (spaces -> tab)
- moved inline styles to css section in head for easier customization
=> small rework of themes

modules/speicher_fronius/main.sh, web/settings/modulconfig.php
Added support for the new BYD HVS/HVM series.
=> Support for new BYD HVS/HVM storage (tested on Symo Hybrid).

web/settings/autoLock.beta.php, web/settings/cloudconfig.beta.php, web/settings/debugging.beta.php, web/settings/misc.beta.php, web/settings/navbar.html, web/settings/setPassword.beta.php, web/settings/setTheme.beta.php, web/settings/settings.beta.php, web/settings/settings_style.css, web/settings/update.beta.php, web/themes/Gauges/settings.css, web/themes/dark/settings.css, web/themes/hidden/settings.css, web/themes/light320480/settings.css, web/themes/standard/settings.css, web/themes/symbol/settings.css
Card Layout for setting pages.
Enabled styling by selected theme.
=> beta settings menu

web/settings/generalchargeconfig.html, web/settings/misc.beta.php, web/settings/nachtladenconfig.html, web/settings/setTheme.beta.php, web/settings/settings.beta.php, web/settings/settings_style.css, web/settings/sofortconfig.html, web/themes/Gauges/settings.css, web/themes/dark/settings.css
- enable theme support
- changed column layout to 1/3 labels and 2/3 form elements
=> change layout of some pages

web/settings/fehlerbericht.beta.php, web/settings/navbar.html, web/settings/settings.beta.php, web/settings/settings_style.css
Änderungen an den aktuellen Seiten übernommen:
- debugging
- fehlerbericht
- settings
=> Merge changes from current pages

modules/soc_tesla/main.sh
Damit sollen auch Passwörter richtig verarbeitet werden, die mir einem Bindestrich beginnen.
Siehe auch: [https://github.com/tesladdicts/testatus/issues/7](url)
=> modified call to teslajson.py

web/settings/misc.beta.php, web/settings/navbar.html, web/settings/pvconfig.beta.html, web/settings/settings.beta.php, web/settings/topicsToSubscribe_pvconfig.js
- added PV-Config in beta menue
- small layout tweaks for general and misc beta settings
=> Beta settings

web/settings/settings.beta.php
Die Einstellung war in die Karte "Awattar" reingerutscht.
=> fix settings card for extOpenWB

web/settings/pvconfig.beta.html
Behebt die schlechte Darstellung auf kleinen Geräten.
=> use custom checkboxes in pv config

web/settings/autoLock.php, web/settings/cloudconfig.php, web/settings/debugging.php, web/settings/fehlerbericht.php, web/settings/generalchargeconfig.html, web/settings/graphconfig.html, web/settings/misc.php, web/settings/modulconfig.php, web/settings/mqtt.php, web/settings/nachtladenconfig.html, web/settings/pvconfig.html, web/settings/setPassword.php, web/settings/setTheme.php, web/settings/settings.php, web/settings/smarthome.php, web/settings/smarthomeconfig.html, web/settings/sofortconfig.html, web/settings/update.php, web/tools/reboot.html, web/tools/update.php
- enable buttons on cloud config
- disable caching of ajax get requests (navbar)
- disable proper menue entries (without beta suffix)
=> fix merge from beta settings

web/settings/cloudconfig.php, web/settings/debugging.php, web/settings/fehlerbericht.php, web/settings/generalchargeconfig.html, web/settings/sofortconfig.html
Es wird nun auch angezeigt, dass der Datennutzung zugestimmt wurde. Durch den Link kann man die Einwilligung jederzeit widerrufen.
=> always show status of data usage setting

web/settings/settings_style.css
removed obsolete styling of owl-carousel
=> better readability of buttons in card header

web/settings/upload.html, web/settings/upload.php, web/themes/dark/settings.css, web/tools/backup.php, web/tools/bckredirect.html
- added some icons
- limit file upload to application/gzip
=> minor tweaks to backup/restore

web/settings/setPassword.php
enable button to remove password protection
=> fix disabled button after beta settings merge

loadvars.sh
Tested only on openWB with single CP.
You might want to double-check once again (I've tried to do my best to check) that there's no copy-and-paste error in the implementation of CPs 2-8.
=> Implement graceful handling of sporadic EVSE read issues

modules/smart_acthor/off.py, modules/smart_acthor/on.py, modules/smart_acthor/watt.py, modules/smart_elwa/on.py
Beide smartdevices sind von der Ansteuerung gleich, haben aber unterschiedliche Returnstati und brauchen somit eine andere Modbuswrite Logik
=> Acthor und Elwa separat

modules/smart_acthor/watt.py, modules/smart_elwa/watt.py
Korrektes Feld für überschuss genommen
=> elwa und acthor

web/settings/smarthomeconfig.beta.php
fox forgotten handler for device 10
=> fix typo for smarthome beta

web/settings/smarthome.php
- layout adopted to new card design
- added warning if tasmota/shelly devices are selected as SmartHome 2.0 is the preferred place for these devices now
=> Card Layout for old SmartHome settings

loadvars.sh, runs/atreboot.sh, web/settings/graphconfig.html, web/settings/topicsToSubscribe_graphconfig.js
- show/hide options in graph config
- options consider configured modules
- add general topic "openWB/pv/boolPVConfigured"
=> dynamic show/hide graph options

runs/mqttsub.py
Messages are logged before any processing takes place. So even invalid and strange garbage messages will be logged.
=> log messages first

runs/mqttsub.py, web/themes/dark/processAllMqttMsg.js, web/themes/dark/theme.html
- fix pylint warnings regarding backslashes
- add reload button to force soc update
=> add button to force lp soc update

web/tools/debug.php, web/tools/reboot.html, web/tools/remote.php, web/tools/remoteredirect.html, web/tools/senddebug.php, web/tools/starttunnel.php, web/tools/update.php
fix layout bug introduced with PR#656
=> fix styling of alerts

web/settings/modulconfiglp.beta.php
some input/select elements got not proper enabled/disabled if they were nested inside another section
=> fix display of nested sections

runs/mqttsub.py
simply discarding of empty messages should fix crash
=> do not process empty messages

web/tools/savemodul.beta.php
- i3 soc auth files
- smashm.conf
- prepared for settings.php and misc.php
=> added missing extra files

modules/smart_idm/off.py, modules/smart_idm/on.py, modules/smart_idm/watt.py, runs/atreboot.sh, runs/cleanup.sh
IDM Wärmepumpe mit Smarthome 2.0 und cleanup *.log reorg und totalwatt
=> idm und cleanup

runs/atreboot.sh, web/index.php, web/isss.html, web/notready.html, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php, web/tools/wizzard.php, web/tools/wizzardend.html, web/tools/wizzardstart.html
- moved plain html in index.php to separate files
- styled pages for slave systems and update-/bootinprogress
- added wizzard to index.php after acknoledgement of privacy policy
- wizzard.php calls defined setting pages
- added wizzard stard and end pages
- added wizzard specific code to EVU, PV and BAT modulconfig
- "wizzarddone" is set to "100" in atreboot.sh to prevent wizzard after update of already running systems
=> first start wizzard

openwb-install.sh
See also https://en.wikipedia.org/wiki/Shebang_(Unix)
=> Fixes shebang in openwb-install.sh

evsedintest.sh, graphing.sh, hook.sh, ladelog.sh, leds.sh, loadvars.sh, nachtladen.sh, nrgkickcheck.sh, nurpv.sh, processautolock.sh, regel.sh, sofortlademodus.sh, u1p3p.sh, zielladen.sh
Hauptsächlich nur Korrektur von
- Einrückungen
- Leerzeilen
- Leerzeichen/Tabs am Zeilenende
Dadurch wird der Code besser lesbar und das "Einklappen" funktioniert in VS Code.
=> fix some formatting of shell scripts

web/display/gauge.html, web/display/simple.html, web/display2/display.html, web/display2/style.css
fix gauges display theme
- changed all references to "displaytheme" configuration "0" (old value for gauges theme) to "3" (new value for gauges theme)
fix cards display theme
- font size in pin window enter/clear buttons
=> fix display themes

web/settings/modulconfiglp.php
- new attribute "data-id" to distinguish between several modbus configurations
- fixes display of corresponding div elements
=> fix modulconfiglp for openWB hardware

web/settings/smarthomeconfig.php
- fix hiding of options when config entry is missing
- fix initial label value of range inputs when config entry is missing
=> fixes: smarthomeconfig

web/settings/modulconfiglp.php
typo in form field name
https://openwb.de/forum/viewtopic.php?f=9&t=2040
=> fix modulconfig for extopenwb on lp2

runs/restore.sh
- added some logging
- fixed missing "*" in copy command; files were copied to /var/www/html/openWB/**openWB/**
=> fix: restore of uploaded backup

modules/soc_mypeugeot/main.sh, modules/soc_mypeugeot/peugeotsoc.py, modules/soc_mypeugeotlp2/main.sh, modules/soc_mypeugeotlp2/peugeotsoc.py
Credentials werden in
$soc_1_username
$soc_1_password
$soc_1_clientid
$soc_1_clientsecret
und
$soc_2_username
$soc_2_password
$soc_2_clientid
$soc_2_clientsecret
erwartet
=> soc für peugeot e208

modules/soc_myopel/main.sh, modules/soc_myopel/opelsoc.py, modules/soc_myopellp2/main.sh
Soc Auslesung E Corsa, Variablennamen eingesetzt
=> Opel E corsa Soc

modules/soc_myopel/main.sh, modules/soc_myopel/opelsoc.py, modules/soc_mypeugeot/main.sh, modules/soc_mypeugeot/peugeotsoc.py
=> soc peugeot und Corsa

modules/smart/sdm630.py, modules/smart_stiebel/off.py, modules/smart_stiebel/on.py, modules/smart_stiebel/watt.py, runs/smarthomehandler.py
Im Smarthome 2.0 werden die Schalter Gerät kann schalten und separate Leistungsmessung (mit SDM630 oder Shelly) unterstützt.
Die Stiebel WP (WPL... wie  WPL15, WPL20, usw) können neu über Smarthome 2.0 angesteuert werden (setzten SG Ready auf Modus 3 bei PV Überschuss)
=> Smarthome Separate Leistungsmessung / Gerät kann schalten und Stiebel

runs/rfid.py
- file ramdisk/rfidlasttag was not updated
- some formatting
=> fix logging of scanned tags in mode2

runs/smarthomehandler.py
Nicht schaltbare devices werden unabhängig vom definierten Typ behandelt und es wird nur auf die Attribute der separaten Leistungsmessung zugegriffen.
=> nicht schaltbare devices

web/tools/wlan/navbar.php, web/tools/wlan/wlan.php, web/tools/wlan/wlan0.sh, web/tools/wlan/wlan1.php, web/tools/wlan/wlan1.sh, web/tools/wlan/wlan_style.css
Mit web\tools\wlan\wlan.php kann im normalen Wlan Betrieb die Wlan Verbindung geändert werden.  Im Lan Betrieb wird auf die Startseite verzweigt. Es werden die Variablen für /home/pi/wssid und /home/pi/wpassword geschrieben. /homei/pi/wlan.sh macht dann den Rest. Der Look & Feel wurde von der Hilfe Seite übernommen.
=> wlan ändern während  Normalbetrieb

modules/smarthome/acthor/off.py, modules/smarthome/acthor/on.py, modules/smarthome/acthor/watt.py, modules/smarthome/elwa/off.py, modules/smarthome/elwa/on.py, modules/smarthome/elwa/watt.py, modules/smarthome/idm/off.py, modules/smarthome/idm/on.py, modules/smarthome/idm/watt.py, modules/smarthome/sdm630/sdm630.py, modules/smarthome/shelly/off.py, modules/smarthome/shelly/on.py, modules/smarthome/shelly/watt.py, modules/smarthome/stiebel/off.py, modules/smarthome/stiebel/on.py, modules/smarthome/stiebel/watt.py, modules/smarthome/tasmota/off.py, modules/smarthome/tasmota/on.py, modules/smarthome/tasmota/watt.py, runs/smarthomehandler.py
New types: Elwa, Acthor, Stieble and idm
Shelly and tasmota control and status  moved to smarthome/shelly and smarthome/tasmota
Everything else under mainfolder smarthome/...
This smarthomehandler.pyt supports existing  ini file (type= pyt, name =stieble)  and new ini file (type = stiebel)  (both ends up in /smarthome/stiebel/...). The folders smart_XXXX are not longer needed.
=> change to smarthomehandler and all smarthomedevices

runs/mqttsub.py, runs/smarthomehandler.py, web/settings/helperFunctions.js, web/settings/processAllMqttMsg.js, web/settings/smarthomeconfig.php, web/settings/topicsToSubscribe_smarthomeconfig.js
- added new device types: acthor, stiebel, idm, elwa
- disabled now deprecated device type "pyt"
- added option to change loglevel
- check for configured housebattery to show/hide options depending on this
=> new smarthome device types

modules/soc_kia/kiasoc.py, modules/soc_kia/main.sh, modules/soc_kialp2/main.sh, runs/atreboot.sh, web/settings/modulconfiglp.php
- rewrote kia soc module for flexible handling of chargepoints
- added kia soc module for chargepoint 2
- added generic settings for chargepoint 2: soc2vin, soc2intervall
=> SoC Kia on LP2

web/settings/smarthomeconfig.php
- complete rewrite of logic to decide if an element should be disabled
- now we check every field, if there is a parent wit css-class 'hide' in its dom tree
- allows flexible nesting of several conditions
=> fix dis-/enabling of nestet form fields

web/display/cards/index.html, web/display/cards/processAllMqttMsg.js, web/display/cards/setupMqttServices.js, web/display/cards/style.css
- just a quick hack!
- some data has to added as mqtt topics
=> added status panel

web/display/cards/index.html, web/display/cards/processAllMqttMsg.js, web/display/cards/setupMqttServices.js, web/display/cards/style.css
- manual ev soc input based on display lock
- minor styling tweaks to status page
=> added manual ev soc

modules/soc_bluelink/main.sh, modules/soc_bluelinklp2/main.sh, modules/soc_kia/kiasoc.py, modules/soc_kia/main.sh
- added missing "$"
- added logging to ramdisk/soc.log (will be used in all soc modules)
=> fix update of soctimerfile

web/logging/monthly.php, web/logging/monthlychart.js
Alle Smarthomedevices werden im monthlychart angezeigt
=> Smarthomedevices in Monthlychart anzeigen

web/settings/smarthomeconfig.php
=> fix publishing of device_measureurl

modules/soc_bluelink/main.sh, web/settings/modulconfiglp.php
parameter "pin" not accepted by evcc and not needed anymore
- removed parameter in call to evcc
- removed pin field in modulconfiglp page
=> fix hyundai bluelink soc

modules/soc_manual/main.sh, modules/soc_manual_lp1/main.sh, runs/atreboot.sh, runs/cron5min.sh, runs/mqttsub.py, web/display/cards/index.html, web/display/cards/setupMqttServices.js, web/settings/modulconfiglp.php, web/themes/Gauges/processAllMqttMsg.js, web/themes/Gauges/setupMqttServices.js, web/themes/Gauges/theme.html, web/themes/dark/helperFunctions.js, web/themes/dark/processAllMqttMsg.js, web/themes/dark/setupMqttServices.js, web/themes/dark/theme.html, web/tools/saveconfig.php
- enabled publishing in cards display theme
- implemented manual soc in standard, dark and gauges themes
- added settings for manual soc in modulconfiglp.php
- removed code from cron5min.sh, all in main.sh
- copied missing code for soc reload to gauges theme
=> add manual soc module

web/display/cards/index.html
- add lock check to status button
- change panel to first not locked, if locked panel is displayed and lock timeout triggers
=> lock status panel

web/logging/yearlychart.js
Input Zeilen mir nur 0 für alle Zaehlerstände werden im Jahreschart überlesen
=> Input Zeilen mir nur 0 als Zaehlerständen werden im Jahreschart überlesen

runs/sendyeargraphdata.sh
Wen ein  Datensatz vom 1.1.Folgejahr vorhanden sind, wird dieser für die Berechnung geschickt. Sonst wird zeitlich der letzte Datensatz genommen  (z.b. am 15 Dezember der vom 15.12 am 14. April der vom 14.April)
=> Letzter Zaehlerstand fürs yearylogging

web/display/cards/index.html, web/display/cards/processAllMqttMsg.js
- changed all show/hide logic to add/removeClass('hide')
=> fix display of house battery cards in dashboard

runs/sendyeargraphdata.sh, web/logging/yearly.php, web/logging/yearlychart.js
- change nested if/else statements in sendyeargraphdata.sh to elif for better readability
- fixed limiting of datepicker, date object needs date in format mm/dd/yyyy for start and end limits
- changed datepicker object format to year only ('yyyy')
- fixed indentation in yearlychart.js
=> fix datepicker in yearly logging

modules/soc_manual/main.sh, modules/soc_manuallp2/main.sh, modules/soc_volvo/main.sh, modules/soc_volvolp2/main.sh, runs/atreboot.sh, web/settings/modulconfiglp.php, web/tools/saveconfig.php
- manual soc for lp2
- volvo soc for lp2
=> SoC Modules

modules/soc_evnotify/main.sh, modules/soc_evnotifys1/main.sh, modules/soc_http/main.sh, modules/soc_http1/main.sh, modules/soc_id/main.sh, modules/soc_idlp2/main.sh
rewrote some SoC modules to "new standard" with logging to soc.log and accepting chargepoint as arg
- evnotify
- http
- vw id
=> rewrite of some SoC modules

web/themes/dark/processAllMqttMsg.js, web/themes/dark/setupMqttServices.js, web/themes/dark/theme.html
Wenn Preisladen aktiv ist, wird der aktuelle Strompreis immer im oberen Info-Block angezeigt, unabhängig vom gewählten Lademodus. Nur geändert für Dark/Standard.
=> Anzeige akt. Strompreis in allen Modi wenn Preisladen aktiv (Standard/Dark)

modules/et_awattar/main.sh, modules/et_tibber/main.sh, modules/et_tibber/tibbergetprices.py, web/themes/Gauges/electricityPriceChart.js, web/themes/Gauges/helperFunctions.js, web/themes/Gauges/processAllMqttMsg.js, web/themes/Gauges/theme.html, web/themes/dark/electricityPriceChart.js, web/themes/dark/processAllMqttMsg.js, web/themes/dark/setupMqttServices.js, web/themes/dark/theme.html
Wo bereits möglich Awattar-Bezeichner verallgemeinert
Gauges-Theme auf Stand gebracht
Stromanbieter als Module vorbereitet (Absprache mit Lutz)
Tibber-Modul implementiert (bedarf noch Integration in MQTT, hier nur proof of concept, Rest Anfang 2021)
=> Vorbereitung allgemeines preisbasiertes Laden

web/settings/autoLock.php, web/settings/generalchargeconfig.html, web/settings/graphconfig.html, web/settings/helperFunctions.js, web/settings/misc.php, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfiglp.php, web/settings/modulconfigpv.php, web/settings/nachtladenconfig.html, web/settings/pvconfig.html, web/settings/settings.php, web/settings/smarthome.php, web/settings/smarthomeconfig.php, web/settings/sofortconfig.php
- moved local functions `showSection()` and `hideSection()` to helperFunctions.js
=> unified usage of helper functions to hide sections

runs/smarthomehandler.py
AVM von Fabian integriert , no impact test für Shelly und http gemacht
Für AVM Devices wird folgendes in der smarthome.ini erwartet:
device_type__X = avm
device_actor_X
device_username_X
device_password_X
Wobei X = 1 bis 9
=> Update smarthomehandler.py für AVM 

runs/smarthomehandler.py
This is primarily to reduce the number of lines to maintain as well as making it easier to add additional device types in the future.
=> Deduplicate code in function sepwatt in smarthomehandler.py

modules/soc_eq/callback_lp1.php, modules/soc_eq/callback_lp2.php, modules/soc_eq/main.sh, modules/soc_eq/soc.py
Bug in callback_lp1 fixed
added Logging to soc.log in soc.py
#839 Fix
=> Logging and Bug Fixing Mercedes EQ SoC Module

modules/soc_bluelink/main.sh, modules/soc_eq/main.sh, modules/soc_eq/soc.py, modules/soc_evnotify/main.sh, modules/soc_from_elastic/main.sh, modules/soc_http/main.sh, modules/soc_i3/main.sh, modules/soc_i3s1/main.sh, modules/soc_id/main.sh, modules/soc_kia/main.sh, modules/soc_leaf/main.sh, modules/soc_leaf/soc.py, modules/soc_leafs1/main.sh, modules/soc_leafs1/soc.py, modules/soc_manual/main.sh, modules/soc_myrenault/main.sh, modules/soc_tesla/main.sh, modules/soc_volvo/main.sh, runs/atreboot.sh
- changed timestamp format
- fixed permissions of files from soc_eq
- fixed some formatting
=> unified timestamp in soc.log

modules/smarthome/avmhomeautomation/avmcommon.py
- Save up to 2 of 3 requests in on.py/off.py
- Save up to 1 of 2 requests in watt.py
=> Improve performance for module avmhomeautomation

modules/soc_bluelink/main.sh, modules/soc_id/main.sh
- enable logging of errors to soc.log
- only update soc if the response is valid
=> change call to evcc-soc

modules/bezug_solax/main.sh, modules/bezug_solax/solax.py, modules/speicher_solax/main.sh, modules/wr_solax/main.sh, modules/wr_solax/solax.py, runs/atreboot.sh, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php
https://openwb.de/forum/viewtopic.php?p=21723&sid=b5db9d32c27f72cc6ce40e8327c7ff9c#p21723
Warning: The internal name for the IP has changed! The used solax modules need to be reconfigured after updating.
=> updated solax integration

runs/atreboot.sh, runs/buchse.py, runs/isss.py
=> implement "openWB Buchse" for isss

modules/soc_i3/index.php, modules/soc_i3/main.sh, web/tools/saveconfig.php
- fixed wrong call in main.sh
- added default chargepoint in main.sh
- proper parsing of cli args in index.php
- fixed saving of config data to new auth files
=> fix soc_i3

modules/extopenwb/main.sh, runs/atreboot.sh, runs/modbusserver/modbusserver.py
- change all references `plugstats2` and `chargestats2` to `...lp3`
=> fix plugstat and chargestat for lp3 in ramdisk

runs/mqttsub.py, web/settings/modulconfiglp.php
- new topics for `chargestat` and `plugstat`
- fix mqtt-ll module for LP3
- fix initial display of LL module for LP3 in `modulconfiglp.php`
=> added Mqtt Module for LP1-3

web/settings/navbar.html
added warning to unplug cars before reboot
=> add warning to reboot message

modules/bezug_fronius_sm/main.sh
https://openwb.de/forum/viewtopic.php?f=9&t=2333
=> Fronius configurable Meter ID for Variant1

modules/soc_carnet/main.sh, modules/soc_carnet/soc.sh
- added socDebugLog
- removed soc.sh and integrated the code in main.sh
=> added logging to soc_carnet

web/themes/colors/chargePointList.js, web/themes/colors/powermeter.js, web/themes/colors/setupMqttServices.js, web/themes/colors/smartHomeList.js, web/themes/colors/style.css, web/themes/colors/theme.html
Diverse Fehler aufgrund des Feedbacks im Forum korrigiert
=> Error corrections

web/themes/EvenDarker/theme.html, web/themes/Gauges/theme.html, web/themes/dark/theme.html
Zur besseren Einstellungen des max. Preises bei preisbasiertem Laden insbes. auf Tablets/Handys Buttons hinzugefügt
=> +- buttons for price

runs/mqttsub.py
- fixed re.sub
- added handling of lp2 and lp3
=> fix handling lp/x/HzFrequenz messages

.gitignore, modules/bezug_fronius_sm/main.sh, modules/et_tibber/stromtarifinfo/infopage.html, modules/et_tibber/stromtarifinfo/tibber.js, modules/et_tibber/tibbergetprices.py, web/themes/EvenDarker/theme.html, web/themes/Gauges/electricityPriceChart.js, web/themes/Gauges/theme.html, web/themes/dark/electricityPriceChart.js, web/themes/dark/theme.html
Fehlerbehandlung bei Abfrage Tibber-API verbessert und Bugfixes zu "zeige Ladezeiten bei preisbasiert im Chart"
=> Fehlerbehandlung verbessert und Bugfix

loadvars.sh, runs/atreboot.sh, runs/initRamdisk.sh, runs/updateConfig.sh
- split atreboot.sh
- initRamdisk.sh
- updateConfig.sh
- fix some errors, mostly not needed usage of `su`
- added logging for easier debugging
- fixed typo in loadvars.sh
- added missing files to initRamdisk
=> split atreboot.sh and some fixes

modules/smarthome/avmhomeautomation/avmcommon.py
This commit drastically increases the amount of logging entries for the module on smarthome loglevel 0. Most data responses are traced for better troubleshooting.
=> Refactor and increase logging verbosity in AVM Home Automation module

modules/soc_eq/callback_lp.php
Error Handler impemented in callback function
=> Mercedes EQ Soc Enhanced Error Handling in callback

modules/smarthome/avmhomeautomation/avmcommon.py
This prevents an error message if e.g. a FRITZ!DECT301 is registered at the same FRITZ!Box as the actor that is to be controlled by OpenWB.
=> Don't read power/energy/voltage from devices that do not provide them

helperFunctions.sh, modules/bezug_mqtt/main.sh, modules/mqttll/main.sh, modules/mqttlllp2/main.sh, modules/mqttlllp3/main.sh, modules/soc_mqtt/main.sh, modules/speicher_mqtt/main.sh, modules/wr_mqtt/main.sh, regel.sh, runs/initRamdisk.sh, runs/mqttsub.py, runs/update.sh, runs/updateConfig.sh
- move config file changes in update.sh to updateConfig.sh
- introduced new helperFunctions.sh
- introduced global function for modules to send state messages (for demonstration in all mqtt modules)
- check for bootinprogress in regel.sh
=> fixes to update and reboot

runs/smarthomehandler.py
Log Meldungen wegen neuem Statusscreen verkürzt und aufgeteilt, Kontrolle Überschussmodus
=> smarthomehandler

web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php
workaround for not initially disabled hidden input field on some browsers
=> fix disabling of hidden input field

modules/soc_myrenault/zoenwake.py, runs/smarthomehandler.py, web/settings/smarthomeconfig.php
Zoe typo in der Aufwachfunktion korrigiert
Smarthomehandler Überschussberechnung mit offset für Einschalten bei maximaler Speicherladung eingebaut
=> Zoe typo / Smarthome

modules/smarthome/avmhomeautomation/avmcommon.py
To reduce the number of requests to FRITZ!Box devices, all Smarthome
Devices for this module that are configured with the same username and
the same Host/IP now share the cached session ID and device info. In the
worst case the cached values are 5 seconds old which is still fast
enough for OpenWB to work with.
In the unlikely event that a user mistyped one of the passwords, the
failed login session for a device might also inhibit value retrieval for
any other device that was supposed to use the same credentials. In case
of credential errors the log messages (in German language) will help to
identify the situationb.
=> Share cache for same username and IP

auslademodus.sh, evsedintest.sh, helperFunctions.sh, hook.sh, ladelog.sh, loadvars.sh, minundpv.sh, modules/bezug_mqtt/main.sh, modules/mqttll/main.sh, modules/mqttlllp2/main.sh, modules/mqttlllp3/main.sh, modules/soc_mqtt/main.sh, modules/speicher_mqtt/main.sh, modules/wr_mqtt/main.sh, nachtladen.sh, nurpv.sh, regel.sh, rfidtag.sh, runs/initRamdisk.sh, runs/updateConfig.sh, slavemode.sh, sofortlademodus.sh, u1p3p.sh, zielladen.sh
implementation for modules/runs still to be done
- logging function in `helperFunctions.sh`
- changed `updateConfig.sh` to insert Tibber demo token as default
- fix `initRamdisk.sh` to not clear log files on update
- export methods of `helperFunctions.sh` so no source in other skripts called from within `regel.sh`necessary
=> centralized logging function for shell skripts

.gitignore, runs/atreboot.sh, runs/update.sh
- add auth and token files to gitignore
- fix upgrading from old auth files in `atreboot.sh`
=> fix Soc i3

modules/soc_eq/main.sh, modules/soc_eq/soc.py
Debug Soc Interval and Log Output Changed.
=>  Mercedes EQ small Fixes

modules/soc_eq/main.sh, modules/soc_eq/soc.py
Added PID to soc.log as API is quite slow at the moment
=> Mercedes EQ Soc enhanced logging

modules/soc_eq/soc.py
=> Mercedes ME SoC without psutil

loadvars.sh, modules/et_awattar/main.sh, modules/et_awattar/stromtarifinfo/infopage.html, modules/et_tibber/main.sh, modules/et_tibber/stromtarifinfo/infopage.html, runs/initRamdisk.sh, web/themes/EvenDarker/theme.html, web/themes/Gauges/navbar.html, web/themes/Gauges/processAllMqttMsg.js, web/themes/Gauges/setupMqttServices.js, web/themes/Gauges/theme.html, web/themes/colors/navbar.html, web/themes/colors/processAllMqttMsg.js, web/themes/colors/setupMqttServices.js, web/themes/colors/theme.html, web/themes/dark/navbar.html, web/themes/dark/processAllMqttMsg.js, web/themes/dark/setupMqttServices.js, web/themes/dark/theme.html, web/tools/saveconfig.php
- add mqtt topic fo selected etprovider module
- change link in navbar for infopage to point to selected module
- trigger first update if settings page is saved
=> etprovider: dynamic navbar link

runs/smarthomehandler.py
Folgende MQTT Topics werden neu (nur bei Veränderung) geschickt:
openWB/SmartHome/Status/uberschuss
-> Gerechneter Überschuss mit  Berücksichtigung Speicherladung / Entladung.
openWB/SmartHome/Status/uberschussoffset
-> Gerechneter Überschuss mit  Offset (maximal mögliche Speicherladung als Offset berücksichtigt). Wird angewant bei Smarthomedevices wo der Speicherbeachtung beim Einschalten  definiert ist und vom Speichersoc noch nicht erreicht ist
openWB/SmartHome/Status/wattschalt
-> Aktuelle Leistungsaufnahme von Smarthomedevices die bei Ladung abgeschaltet werden
openWB/SmartHome/Status/wattnichtschalt
-> Aktuelle Leistungsaufnahme von Smarthomedevices die bei Ladung nicht abgeschaltet werden
(beide Werte zusammen ergeben die aktuelle Leistungsaufnahme Smarthomedevices) …
=> MQTT Summentopics für Smarthomehandler

web/hilfe/hilfe_erste_schritte.php, web/settings/cloudconfig.php, web/settings/helperFunctions.js, web/settings/misc.php, web/settings/mqtt.php, web/settings/navbar.html, web/settings/network.php, web/settings/processAllMqttMsg.js, web/settings/settings.php, web/settings/settings_style.css, web/settings/smarthomeconfig.php, web/status/status.php, web/themes/dark/processAllMqttMsg.js, web/tools/datenschutz.html, web/tools/savemqtt.php
- fix some html errors/warnings
- typos
- remove js console logging of stable pages
- fix some input validation
- remove nachtaden testing page from menu
=> small ui fixes

runs/buchse.py, runs/isss.py
filter short evse read errors for slave systems
=> filter read errors

modules/soc_myrenault/zoensoc.py, modules/soc_myrenault/zoenwake.py
=> Zoe api key fix

modules/soc_tesla/main.sh, modules/soc_tesla/tesla.py, runs/updateConfig.sh, web/settings/modulconfiglp.php
=> fix tesla login

runs/initRamdisk.sh, runs/mqttsub.py, web/settings/smarthomeconfig.php, web/settings/topicsToSubscribe_smarthomeconfig.js
- added mystrom devices (gui only)
- added setting maxBatteryPower
=> gui for mystrom devices and max battery power

web/settings/smarthomeconfig.php
=> smarthomeconfig

web/logging/chargelog/ladelog.php, web/logging/chargelog/ladelogexport.php, web/logging/daily.php, web/logging/dailychart.js, web/logging/index.php, web/logging/monthly.php, web/logging/monthlychart.js, web/logging/navbar.php, web/logging/yearly.php, web/logging/yearlychart.js, web/status/status.php, web/themes/EvenDarker/settings.css, web/themes/Gauges/settings.css, web/themes/dark/settings.css
added theme support for
- status
- chargelog
- chargelog export
- logging pages
adopted css for themes
- dark
- gauges
- EvenDarker
=> theme support for some pages

modules/soc_myrenault/main.sh, modules/soc_myrenault/zoensoc.py
An die neuste Api von renault angepasst, soc sollte wieder gehen
=> Zoe Soc an  Renault Api Änderung angepasst

modules/speicher_json/main.sh, runs/updateConfig.sh, web/settings/modulconfigbat.php
New Module to use Home Battery with JSON Output.
Can use complex jq Filters like PV_JSON and EVU_JSON
Description in moduleconfigbat.php has to be reworked.
=> Speicher_JSON Module BETA!!!!

runs/updateConfig.sh, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php
- move wizzarddone input field to hidden div
- fix wrong numbers in openwb.conf
=> fix wrong enabling of wizzarddone input

modules/bezug_json/main.sh, modules/speicher_json/main.sh, modules/wr_json/main.sh
testing if filter variables are empty. If yes set 0 for the results.
=> Fix Empty Filters in JSON Modules PV/WR/SPEICHER

runs/atreboot.sh, runs/initRamdisk.sh, u1p3p.sh, web/settings/pvconfig.html
- fix syntax error in u1p3p.sh
- minimize timeout values in atreboot.sh and initRamdisk.sh
- fix warning in initRamdisk.sh if openWB.log already exists
- fix display of ev soc options in pvconfig
=> beta bugfixes

helperFunctions.sh, modules/soc_eq/main.sh
First try to use the openwbModulePublishState
fixed the Doku bug in helperfunctions. EVSOC also has 4 parameters
=> SOC_EQ enhancement MQTT State helperfunction doku bug fixed

modules/et_awattar/awattargetprices.py, modules/et_awattar/main.sh, modules/et_tibber/main.sh, modules/et_tibber/stromtarifinfo/infopage.php, modules/et_tibber/tibber.js, modules/et_tibber/tibbergetprices.py, sofortlademodus.sh
Bugfixes, Logging verbessert, Logeinträge verständlicher formuliert
=> Feature 05 preisbasiert

modules/smarthome/avmhomeautomation/avmcommon.py
As agreed upon with @okaegi, this is in preparation of inverting the loglevel semantics.
=> avmhomeautomation: Use constants for loglevel

web/status/processAllMqttMsg.js, web/status/setupMqttServices.js, web/status/status.php
Neu werden 5 Kennzahlen vom Smarthome 2.0 auf der Statusseite angezeigt
=> Smarthome 2.0 auf Statusseite

modules/smarthome/tasmota/watt.py
https://github.com/snaptec/openWB/issues/1066#issuecomment-780683209
=> tasmota auf shelly

web/systeminfo/systeminfo.php, web/tools/programmloggerinfo.php
Show WLAN Details in system info
=> SystemInfo WLAN Details Enhancement

web/themes/colors/chargePointList.js, web/themes/colors/powergraph.js, web/themes/colors/powermeter.js, web/themes/colors/smartHomeList.js, web/themes/colors/style.css, web/themes/colors/theme.html, web/themes/colors/yieldmeter.js
As requested in the forum, a light mode was added to the color theme.
It has a white background and the other colors are adjusted where required.
You can toggle between light and dark mode with the new "Paintbrush" button on top of the first widget.
=> "Light mode" for the color theme

web/settings/helperFunctions.js, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfiglp.php, web/settings/modulconfigpv.php, web/settings/setTheme.php, web/settings/sofortconfig.php, web/settings/topicsToSubscribe_sofortconfig.js
- sort modulconfig options a-z
- modified theme settings to change css right after saving setting
- added missing soc configured topics to sofortconfig
=> small web ui fixes

web/themes/colors/powerdata.js, web/themes/colors/powergraph.js, web/themes/colors/powermeter.js
Removed console output
Added persistent storage for light mode selection
=> Fix for color theme

modules/et_awattar/stromtarifinfo/infopage.php, modules/et_tibber/stromtarifinfo/infopage.php, web/display/cards/setupMqttServices.js, web/status/status.php, web/systeminfo/systeminfo.php, web/themes/EvenDarker/theme.html, web/themes/Gauges/theme.html, web/themes/colors/theme.html, web/themes/dark/theme.html
- disable caching for all navbars
- some typos
- cards display theme: delay reconnect
- disabled logging of manual SoC
=> fix caching of navbar

web/themes/EvenDarker/theme.html, web/themes/Gauges/processAllMqttMsg.js, web/themes/Gauges/theme.html, web/themes/dark/processAllMqttMsg.js, web/themes/dark/theme.html
- changed themes and processAllMqttMsg to add/remoce class "hide"
- initially hide some optional elements
=> fix hiding of optional elements

web/display/cards/index.html, web/display/cards/processAllMqttMsg.js, web/display/cards/setupMqttServices.js, web/display/gauges/index.php, web/display/gauges/live.js, web/themes/Gauges/setupMqttServices.js
- added backend info to state of cards and gauges theme
- added button to state of cards and gauges theme to reload the complete display
- fixed typo in reconnect statement
=> fix reconnection of themes to broker

modules/wr2_kostalpiko/main.sh, web/settings/modulconfigpv.php
copy of wr_kostalpiko from pv1
=> new: kostal piko pv2 module

modules/soc_myrenault/main.sh
Protokollieren den von Renault gelesenen Soc im log
=> soc zoe im log protokollieren

modules/smarthome/tasmota/watt.py
Der Einschaltstatus kommt mit einem Gross / Kleingeschriebenen Power daher
https://github.com/snaptec/openWB/issues/1081
=> tasmota..Power

.gitignore, modules/soc_i3/auth.json, modules/soc_i3/index.php, modules/soc_i3/main.sh, modules/soc_i3s1/auth.json, runs/atreboot.sh, runs/update.sh, web/tools/saveconfig.php
- remove auth* files and eliminate duplicate storage of credentials in saveconfig.php
- remove bachup/restore on update/atreboot
=> soc i3: remove auth files

modules/bezug_fronius_sm/main.sh
- added debug logging
- recalculate current if meter is located in consumption path
- added env check to support manual run from shell
=> fix current calculation in bezug_fronius_sm

modules/soc_tesla/main.sh, web/tools/saveconfig.php
if modulconfiglp is updated and a tesla soc ist selected, a soc update is triggered immediately, as the mfa passcode is only valid for a short time. The triggered update may get standard for all soc modules if running without problems.
=> start ev-soc update in saveconfig.php (only tesla)

modules/wr2_json/main.sh, modules/wr_json/main.sh
Set Power to 0 if jq reponse is not numeric.
=> Bugfix WR_JSON Moduls

runs/atreboot.sh
restart apache after modifying config files in atreboot.sh
=> restart http server after config change

web/settings/autoLock.php, web/settings/navbar.html, web/settings/settings_style.css
- Letzte Überreste der alten Verlaufs-Farben für Buttons und Header entfernt
- Einheitliche Verwendung der Bootstrab-Farben
- Hinweistext für Auto-Lock
=> Einheitliche Verwendung der Bootstrap-Farben, Hinweistext

modules/soc_manual/main.sh
Reverts snaptec/openWB#1137
Merged into wrong branch
=> Revert "Update main.sh in soc_manual"

web/themes/EvenDarker/style.css, web/themes/EvenDarker/theme.html, web/themes/Gauges/style.css, web/themes/Gauges/theme.html, web/themes/dark/style.css, web/themes/dark/theme.html
revert text size changes from #1136
=> revert text size modifications

runs/initRamdisk.sh
missing variable ladungdurchziel in initramdisk
See 
https://openwb.de/forum/viewtopic.php?f=9&t=2751
=> Zielladen missing variable/file in ramdisk

openwb-install.sh, runs/atreboot.sh
check for PHP Version to set the limits correct
=> atreboot prepare for Buster

modules/smarthome/shelly/watt.py
alle drei möglichen Temperatur Sensoren für Shellys werden einzeln abgefragt. Zusätzlich wird die Return Message vom Shelly auf der Ramdisk abgelegt
=> shelly temp sensor

modules/soc_i3/index.php
- temporary change requested url to .com domain
=> fix: bmw soc after broken .de website

modules/smarthome/tasmota/watt.py
Tasmota ohne Leistungsmessung (analog Smarthome 1.0)  sollten auch laufen
=> Tasmota ohne Leistungsmessung

runs/atreboot.sh, runs/cronnightly.sh, runs/csvcalc.py, runs/initRamdisk.sh
=> Ersatz monthly v2

modules/bezug_json/main.sh
=> bezug_json changed debug output levels

modules/bezug_powerwall/main.sh
Mit dem Powerwall EVU Modul können jetzt auch die Werte Spannung, Stromstärke und Leistung je Phase ausgelesen werden.
=> Verbesserung Powerwall EVU Modul

web/settings/misc.php
- fix mixed up values
- removed unneeded function definitions
- moved some functions to document.ready
=> fix: init of radio button groups

sofortlademodus.sh
- added message to "lastregelungaktiv" topic
- fixed some typos in debug logs
- unified code for LP1/LP2 and LP3-LP8
- removed duplicate code in LP1/LP2
- always set current to mincurrent if below
=> fix: set current if below mincurrent

modules/evcc-license
as requested by author of evcc
=> added evcc-soc license file

runs/updateConfig.sh, web/logging/chargelog/ladelogexport.php, web/settings/misc.php, web/settings/settings.php, web/settings/smarthome.php, web/settings/smarthomeconfig.php, web/status/status.php, web/themes/EvenDarker/theme.html, web/themes/Gauges/theme.html, web/themes/colors/theme.html, web/themes/dark/theme.html, web/tools/saveconfig.php
- fix some errors/warnings reported by W3 validator
- added missing "hook3einschaltverz" to updateConfig.sh
- removed old code to read openwb.conf from smarthome.php
- removed duplicate section in colors theme
- added more checks before updating openwb.conf
=> fix minor html errors and warnings

runs/cron5min.sh, runs/cronnightly.sh, web/settings/misc.php
Wenn Pushover konfiguriert ist, werden die Zählerstände aller konfigurierten LP zum jeweiligen Monatsersten gepusht.
=> Pushover: Zählerstände zum Monatsersten

modules/smarthome/we514/watt.py, runs/mqttsub.py, runs/smarthomehandler.py, web/settings/smarthomeconfig.php
added smarthome2.0 module to support orno we514 energy meter via RS485/ethernet converter
=> new WE514 module for smarthome 2.0

modules/bezug_powerfox/main.sh, openwb.conf, runs/updateConfig.sh, web/settings/modulconfigevu.php
Integration von Powerfox als EVU Modul
Doku zur API:
https://www.powerfox.energy/wp-content/uploads/2020/05/powerfox-Kunden-API.pdf
=> EVU Module Powerfox 

runs/initRamdisk.sh
- should fix #1055
- remove empty backup file
- keep configured current for instant charging
=> fix init some ramdisk files

runs/updateConfig.sh
- added missing `wirkungsgradlp2`
- changed `soc_vag_vin` to avoid syntax error
=> fix config entries

runs/updateConfig.sh
=> added handling of discovergypass key

runs/atreboot.sh
=> fix module permissions

regel.sh, runs/u1p3pcheck.sh
=> fix cp/u1p3p syntax error

modules/soc_eq/soc.py
=> Bugfix Soc_Eq

.gitignore, runs/checkmqttconf.sh, runs/initRamdisk.sh, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php, web/settings/setTheme.php
- add soc_eq access files to .gitignore
- do not restart mosquitto on config change, simply trigger reload (fixes some timing issues with blocked ports on restart)
- remove duplicate line in initRamdisk.sh
- fixed hiding of JSon Input elements in modulconfigbat.php
- renamed labels with "kWh" to "Wh"
- added feedback to save button in setTheme.php button
=> minor fixes

openwb-install.sh
=> Fix Cron Logging in install

modules/soc_kia/kiasoc.py, modules/soc_kia/main.sh, runs/updateConfig.sh, web/settings/modulconfiglp.php
Add manual SoC calulation for Kia LP1
Added Retry on "valid" 0% SoC reply
Fixed Out-of-Boundary for Stams-Array
Fixed a few Typos
=> Add manual SoC calulation for Kia

web/themes/colors/powerdata.js
The naming in the energy graph for previous days is now the same like for the current day
=> Color theme bug fix

web/settings/settings.php
Bindestrich und Unterstrich als erlaubtes Zeichen hinzugefügt
=> RegEx zur Bereinigung Tibber-Token und HomeID geändert

modules/wr2_kostalsteca/main.sh
Make sure the module works for 1p and 3p converters. Make sure the Module delivers 0 if there is no numeric kwh value to prevent errors.
https://openwb.de/forum/viewtopic.php?p=29086#p29086
=> Enahancement wr2_kostalsteca

modules/wr2_kostalsteca/main.sh
get old value from ramdisk instead of 0 if WR doesn't deliver a number.
=> wr2_kostalsteca fix pv2kwh value

web/settings/modulconfiglp.php
Remover the Beta Marker, as Mercedes EQ SoC works for several month now.
=> Remove Beta Marker in lpconfig for Mercedes EQ SoC

web/settings/systeminfo.php
Datum wurde unter Safari nicht korrekt bearbeitet, WLAN-Daten nur anzeigen wenn auch WLAN aktiv.
=> Systeminfo: Bugfix und Improvement

modules/soc_http/main.sh, runs/updateConfig.sh, web/settings/modulconfiglp.php
- zweiter Versuch, da ich versehentlich den vorherigen Fork gelöscht habe
- beta, da ungetestet
=> SoC HTTP Intervallvorgabe (beta V2)

runs/smarthomehandler.py
Neue Verbrauchszähler  (json und fronius )
=> json und fronius

web/values.php
- revert changes to values.php
=> fix gauges theme

modules/soc_bluelink/hyundaisoc.py, modules/soc_bluelink/main.sh, modules/soc_kia/kiasoc.py, modules/soc_kia/main.sh
Abruf-Intervall für Regelung "Sehr Langsam" gefixt
Timeout für Statusabruf vergrößert
Minimum Logging bei Debug Level 0
Retry, wenn Timeout bei Status-Abfrage
=> Diverse Fixes für Kia/Hyundai

web/themes/colors/powerdata.js, web/themes/colors/powergraph.js, web/themes/colors/powermeter.js, web/themes/colors/processAllMqttMsg.js, web/themes/colors/setupMqttServices.js, web/themes/colors/theme.html, web/themes/colors/yieldmeter.js
The theme allows now to have a look at the monthly energy values by pushing the new "calendar" button on top of the right graph. The arrow buttons can then switch between months
=> Color theme: added month view

runs/cronnightly.sh, runs/csvcalc.py, runs/initRamdisk.sh
csvcalc datum aufbereitung angepasst (dd.mm.yyyy)
aktivierung im initramdisk.sh und cronnighly.sh eingebaut
=> neue month excel aktivieren

modules/soc_vag/main.sh, web/settings/modulconfiglp.php
- Entfernung der nicht mehr unterstützten Fahrzeugtypen
- Verbesserungen der main.sh entsprechend EVCC und Tronity Modul
- Hinweistexte im VW ID und im Carnet Modul
=> Update VAG Modul

runs/cleanup.sh
https://man7.org/linux/man-pages/man1/find.1.html
=> Find needs a startpoint not a file pattern.

web/settings/modulconfigpv.php
fix copy/paste typo in select option value
=> fix: pvkit setting sdm

modules/wr2_kostalsteca/main.sh
Additional Logging required for debugging
=> KostalSteca additional Logging

modules/wr2_kostalsteca/main.sh
Pretty Print the XML to have Lines to grep
=> Bugfix wr2_kostalsteca

web/settings/modulconfiglp.php
https://openwb.de/forum/viewtopic.php?f=5&t=1789
=> Hinweis auf Go-e Firmware Update 0.40

modules/wr2_kostalsteca/main.sh
The Prettyprinting has problems with unicode Chars. python3 can handle that
=> Bugfix wr2_kostalsteca Unicode Characters

web/themes/colors/chargePointList.js, web/themes/colors/powerdata.js, web/themes/colors/powergraph.js
Two fixes as requested in the forum
- "charge at night" icon color changed
- remove vertical grid  lines in monthly graph view
=> Color theme: bug fixes

runs/csvcalc.py
Die gesamte Ladeleistung wird in dem neuen Monatsexcel (in 5 Minutenschritten) auf PV, EVU und Speicher aufgeteilt. Details siehe hier
https://openwb.de/forum/viewtopic.php?p=31096#p31096
=> aufteilen der gesamten Ladeleistung nach PV, EVU und Speicher

goecheck.sh, runs/set-current.sh
Siehe https://openwb.de/forum/viewtopic.php?f=5&t=1789
Mqtt Befehl abhängig von FW Version
=> go-e API: neuer Befehl zur Stromvorgabe

web/settings/modulconfiglp.php
- Alphabetische Reihenfolge der Fahrzeugtypen für LP1 und LP2
- Škoda Fahrzeugtyp zu LP1 und LP2 hinzugefügt
=> soc_evcc: alphabetische Fahrzeugtypen

modules/soc_eq/soc.py
Typo in  token_Refresh Handling in case of errors and additional Exception Handling
=> Bugfix Mercedes EQ Soc

modules/keballlp1/setcurrkeba.py, runs/smarthomehandler.py
Beim Smarthomehandler wird nun sichergestellt, dass ein Device welches bei Autoladenausschalten = JA nicht ungewollte ein PV gestützte Ladung veranlasst. (Konnte passierte beim umschalten von Manual auf Automatisch mit genügen langer Abschaltverzögerung)
Keba: Neue Current wird nur übertragen wenn Auto eingesteckt ist
=> smarthomehandler & keba

runs/mqttsub.py, runs/sendmonthgraphdatav1.sh, runs/sendyeargraphdatav1.sh, web/logging/monthlychartv1.js, web/logging/monthlyv1.php, web/logging/navbar.php, web/logging/yearlychartv1.js, web/logging/yearlyv1.php
Duplizieren der heutigen Monthly und Yearly Grafiken mit separaten mqtt topics, seperate .sh, seperate .php und .js
So dass online dann alte gegen neue Grafiken verglichen werden können
=> Vorbereitung neue Graphiken

runs/csvselmonth.py, runs/sendmonthgraphdatav1.sh, web/logging/monthlychartv1.js, web/logging/monthlyv2.php, web/logging/navbar.php
Der neue Monatsgrah basiert auf den neuen Excel Dateien die im Hintergrund vorgerechnet werden.
Zusätzlich hat es einen separaten Aufruf, womit die PV , EVU und Speicheraufteilung der Ladeleistung und vom Device 1 gezeigt wird.
=> Monatsgraph basiert auf neuen Excels

runs/csvcalc.py, runs/csvselmonth.py, web/logging/monthlychartv1.js
Gui
Alle 9 Smarthomedevices dazugefügt
Fehler im Smarthomedvice 1 bereinigt
Alert messages entfernt
Tage die fehlen (aktueller Monat) werden mit 0 Beträgen aufgefüllt
Csvcalc
Für alle 9 Smarthoemdeive wird die Aufteilung nach Pv, Speicher und EVU gemacht
=> neue monthly Graphiken erweitert

modules/speicher_studer/main.sh, modules/speicher_studer/studer_speicher.py, modules/wr_studer/main.sh, modules/wr_studer/studer_wr.py, runs/updateConfig.sh, web/settings/modulconfigpv.php
allows Monitoring Studer XTender (XTS/XTH/XTM) and MPPT Charger (VS + VT)
=> added Module for Studer WR

runs/csvcalc.py
Neu wird ein Jahresexcel gerechnet. Fürs aktuelle Jahr wird das auf der Ramdisk gespeichert, sonst auf der SD karte. Das wird später fürs Online gebraucht
=> csvcalc Jahresexcel rechnen

runs/csvselyear.py, runs/sendyeargraphdatav1.sh, web/logging/monthlychartv1.js, web/logging/navbar.php, web/logging/yearlychartv1.js, web/logging/yearlyv2.php
Die jährlichen Grafiken sind auf die neuen Excel umgestellt
=> Yearly logging auf neuer Datenbasis

modules/bezug_solarwatt/main.sh, modules/speicher_solarwatt/main.sh, modules/wr_solarwatt/main.sh, runs/updateConfig.sh, web/settings/modulconfigbat.php
=> Alternative EVU+Batterie-Module für Solarwatt/MyReserve-Geräte mit Gateway

web/themes/EvenDarker/theme.html, web/themes/Gauges/processAllMqttMsg.js, web/themes/Gauges/setupMqttServices.js, web/themes/Gauges/theme.html, web/themes/dark/theme.html
- smaller padding in heading section od standard, dark and even-darker themes
- added house daily yield to gauges theme
=> minor theme layout changes

modules/soc_evcc/main.sh, modules/soc_tesla/main.sh, zielladen.sh
- add missing log entry in zielladen.sh
- fix wrong ticksize in soc_evcc
- added ticksize to soc_tesla
=> debugging soctimer increment

modules/soc_audi/main.sh, modules/soc_carnet/main.sh, modules/soc_eq/main.sh, modules/soc_evnotify/main.sh, modules/soc_http/main.sh, modules/soc_i3/main.sh, modules/soc_id/main.sh, modules/soc_leaf/main.sh, modules/soc_manual/main.sh, modules/soc_myopel/main.sh, modules/soc_mypeugeot/main.sh, modules/soc_myrenault/main.sh, modules/soc_psa/main.sh, modules/soc_tronity/main.sh, modules/soc_volvo/main.sh, modules/soc_zerong/main.sh, modules/soc_zoe/main.sh
- changed logging to openwbDebugLog from helperFunctions
- unified timer increment for different regulation loop speed settings
=> unified usage of helperFunctions and soctimer

loadvars.sh, runs/mqttsub.py, slavemode.sh
* support RFID activation via MQTT
* reduce some debug level in slave mode
* send info about active slave mode via MQTT
=> Support more automatic provisioning in slave mode:

runs/pubmqtt.sh
Implements issue #1352 in a one-liner.
CPU temp degrees celsius in topic `openWB/global/cpuTemp`
=> Publish CPU temperature via MQTT

modules/speicher_lgessv1/main.sh, modules/wr_lgessv1/main.sh
=> convert ISO-8859-1 encoded files to UTF-8

modules/soc_evnotify/main.sh
increment timer in evnotify übernommen, anlog den anderen soc modulen
=> increment timer in evnotify

runs/atreboot.sh, runs/cron5min.sh
replaced simple output with `echo` by call of logging function
- atreboot.sh
- cron5min.sh
=> detailed logging

modules/soc_tesla/main.sh, runs/cronnightly.sh, runs/replaceinconfig.sh, runs/senddebug.sh, runs/updateConfig.sh, runs/wlanconnect.sh
=> Revert "Fix openwb.conf manipulations with sed when running in Docker"

runs/smarthomehandler.py
Smarthomehandler unterstützt "Spätestens fertig um" . Falls ein Device heute noch nicht gestartet wird wird es unter der Berücksichtigung der Mindestlaufzeit unabhängig vom Überschuss so gestartet , dass es an der angeben Uhrzeit fertig ist.
Mqtt Aufrufe wurden so bereinigt, dass immer nur bei Veränderungen MQTT upgedatet wird.
=> smarthomehandler Spätestens fertig um

runs/smarthomehandler.py
Ist nun im Smarthomehandler komplett ungesetzt, Beschreibung vom Feature siehe hier:
https://openwb.de/forum/viewtopic.php?p=27404#p27404
=> Anlauferkennung Teil 2

modules/wr2_json/main.sh, modules/wr_json/main.sh
Synced both main.sh files. So handling for both PVs is identical. Added some more debug Messages
=> Syncing wr_json and wr_json2

slavemode.sh
Load Management "Slave mode":
When controller sends 0 for `VehiclesChargingOnPhase...` but wallbox detects that it's contributing to load imbalance, a div/0 error occurs.
It's clear that this is actually an issue with the load management controller as at least 1 vehicle (ourself) must be charging. But with this fix we handle it gracefully (implicitly "heal" it) to prevent log spamming with errors and unexpected/undeterministic behviour of control loop.
=> Prevent div/0 for strange values from controller

openwb-install.sh, runs/atreboot.sh
- added mosquitto packages to install script
- changed "restart" command into "reload"
=> fix mosquitto in installer

modules/et_awattar/awattargetprices.py, modules/et_tibber/tibbergetprices.py
Bugfix: bei Exception war Variable zuvor nicht deklariert
=> Small bugfix

modules/soc_psalp2/main.sh
Copy/Paste mistake ; not tested, but should work ;)
=> Fix PSA SoC functionality on LP2

modules/smarthome/http/watt.py
Zählerwerte können analog aktuelle Leistungswerten auch Nachkommastellen haben
=> http Smarthomedevices

web/themes/colors/powergraph.js
Siehe https://openwb.de/forum/viewtopic.php?f=9&t=3685
=> Fix smarthome devices and battery in Colors theme monthly chart

web/settings/modulconfiglp.php
Solange https://github.com/snaptec/openWB/issues/1438 nicht umgesetzt ist per Hand
=> evcc: Add carwings for Leaf pre 2019

modules/smarthome/viessmann/off.py, modules/smarthome/viessmann/on.py, runs/smarthomehandler.py, web/settings/smarthomeconfig.php
Neu kann definiert werden, dass bei PV Überschuss ein Device nur innerhalb eines gewissen Zeitraums angeschaltet wird.
MQTT Topics im Gui beschrieben
Viessmann on / off Trigger besser protokoliiert
=> Smarthomehandler Startzeit / Endezeit und Viessmann

modules/bezug_discovergy/discovergy.py
wattbezug must have no decimals
=> fix discovergy wattbezug

web/settings/modulconfiglp.php
Use public API from evcc cloud to get available/supported vehicles.
This fixes #1438
=> Settings: evcc: Support dynamic vehicles selection

regel.sh
CP Unterbrechung for LP 2 is not aligned with code for LP 1 (there's no `cpulp2counter`).
This seems to cause oscillations in some cases (see [Ticket 49946775]).
The requested change introduces `cpulp2counter` in very much same way as for LP 1.  
Additionally it lowers the "not charging" limit from 200 W to 100 W so we use the same value as for LP 1 here, too.
Code for CP Unterbrechung of LP 2 should now be functionally identical to LP 1.
=> CP-Unterbrechung LP2 identisch zu LP1

modules/smarthome/sdm120/sdm120.py, runs/mqttsub.py, runs/smarthomehandler.py, web/settings/smarthomeconfig.php
sdm120 sollte nun als separate Leistungsmessung im Smarthomehandler gehen. Viessmann im Gui dokumentiert. Flag Im Hausverbrauch einrechnen im Gui korrigiert
=> sdm120, viessmann im Smarthomehandler

runs/readmodbus.py
Hatte etwas Probleme das zu testen. Jedoch vermute ich das dass Problem von einem/dem anderen Gerät kommt und die Fahlerbehandlung fehlt.
=> Fix für #1466

modules/smarthome/acthor/watt.py
Es wird nun beim jeden durchlauf immer ein Return file geschrieben
=> acthor leistungsabfrage

runs/setvirtips.sh
=> bugfix wlan0

modules/wr_plenticore/read_kostalplenticore.py
erster Beitrag mit klassenbasierter Version zum Review
=> KostalPlenticore - überarbeitete Version

web/settings/modulconfigevu.php
Solaredge hat a wrong label for Port
=> Fix Typo in moduleconfigevu

web/themes/EvenDarker/theme.html, web/themes/Gauges/theme.html, web/themes/colors/theme.html, web/themes/dark/theme.html
Angesichts der aktuellen Strompreise: Erhöhung Max-Preis für preisbasiertes Laden auf 50ct/kWh, so dass in Sofortladen zu jeder Zeit laden möglich ist
=> Max-Preis für preisbasiertes Laden erhöht

modules/wr_json/read_json.py
=> Fix Watt filename for WR2 in JSON WR Module

modules/wr2_mqtt/main.sh, runs/mqttsub.py, web/settings/modulconfigpv.php
New Module Config for MQTT on PV2.
=> New Module for MQTT at PV2

modules/wr2_json/main.sh
wrong variablename
fixes wr2 Problem of aiole
=> fix for WR2_JSON

modules/bezug_fronius_sm/fronius_sm.py, modules/bezug_fronius_sm/main.sh
Dieser Pull Request enthält die Fronius-relevanten Teile aus Pull Request #1519 und weitere Änderungen im Python Modul.
=> python module for Fronius SM

runs/mqttsub.py, runs/smarthomehandler.py, web/settings/smarthomeconfig.php, web/settings/topicsToSubscribe_smarthomeconfig.js
Parametererfassung für mehrfache Anlauferkennung pro Tag eingebaut
Parametererfassung für separate Leistungsmessung mit SMA Energie Meter eingebaut
=> Gui Anpassung Smarthomesettings

runs/mqttsub.py, web/settings/smarthomeconfig.php
Typos korrigiert
typ smaem nicht sma
=> typos smart energy meter

modules/wr_solarlog/main.sh
Add Debugging and error handling of invalid answers.
=> Sync wr_solarlog with wr2_solarlog

runs/updateConfig.sh
Fix for https://openwb.de/forum/viewtopic.php?p=46101#p46101
=> Speicher_varta Variable für 2. IP fehlt

modules/soc_tesla/tesla.php, modules/soc_tesla/tesla.py
- prepare for vehicle select by VIN (backend only, frontend to be done)
- adopt changes in login based on https://github.com/timdorr/tesla-api/discussions/362
=> fix tesla soc

modules/wr_json/read_json.py
Fix to get all numeric values as input. changing into integer before writing to File
=> Update WR_JSON read_json.py

modules/bezug_ethmpm3pmflex/main.sh, runs/updateConfig.sh, web/settings/modulconfigevu.php
Moduleconfig for EVU to use Protoss/Elfin connected Modbus Counters with flexible use of IP,PORT and Unit_ID
=> Flexevu config

modules/wr2_pvkitflex/main.sh, modules/wr_pvkitflex/main.sh, modules/wr_pvkitflex/test.py, runs/updateConfig.sh, web/settings/modulconfigpv.php
moduleconfig for PV, to use Protos/Elfin based modbus counters as PV modules with free choice of IP,Port and Unit_id
=> flexPV moduleconfig for PVKit

modules/bezug_ethmpm3pmflex/main.sh
=> flexevukit Bugfix

modules/soc_kia/kiaauth.py, modules/soc_kia/kiaif.py, modules/soc_kia/parameters.py
Rücknahme der Änderung zur GCMId aus dem letzten PR
=> [Kia/Hyundai] - Hotfix - GCM-SenderID + 12V-SoC

modules/soc_evnotify/evnotify.py
Now it starts get a little bit embarrassing... I got the validity check for the SoC the wrong way.
Follow-up for #1602
=> fix: Wrong validity check for SoC

modules/bezug_ethmpm3pmflex/main.sh
=> fix flexEVU Kitt

modules/simpleevsewifis1/main.sh
=> Change Current and Voltage to Integer - simpleevsewifi1 

modules/simpleevsewifis2/main.sh
=> Change Current and Voltage to Integer - simpleevsewifi2

modules/wr2_pvkitflex/main.sh
=> bugfix flexpvkit WR2

modules/wr2_ethlovato/main.sh, modules/wr2_ethlovatoaevu/main.sh, modules/wr_ethmpm3pmaevu/main.sh
=> fix Lovato IDs and pv2kitversion typo

modules/et_awattar/awattargetprices.py, modules/et_tibber/stromtarifinfo/infopage.php, modules/et_tibber/tibber.js, modules/et_tibber/tibbergetprices.py
Zeitumstellung hat bei diversen Berechnungen Fehler verursacht
=> Bugfixes preisbasiertes Laden

packages/helpermodules/compability.py, packages/helpermodules/compatibility.py, packages/helpermodules/log.py, packages/modules/alpha_ess/device.py, packages/modules/common/abstract_component.py, packages/modules/common/abstract_device.py, packages/modules/common/lovato.py, packages/modules/common/modbus.py, packages/modules/common/module_error.py, packages/modules/common/mpm3pm.py, packages/modules/common/sdm630.py, packages/modules/common/simcount.py, packages/modules/common/store.py, packages/modules/openwb/device.py, packages/modules/openwb_flex/device.py
Umsetzung der Anmerkungen zu #1673 für Common und Helper Module
=> Improve code style

.github/workflows/github-actions-python.yml, packages/modules/common/module_error.py, packages/modules/common/simcount_test.py, packages/testutils/mock.py
Mit diesem PR möchte ich Anregen sich mit den Vorzügen von Unittests zu befassen. Dieser PR macht den Anfang und bringt einen Test für `simcount` mit ins Projekt. Als Testframework habe ich `pytest` genommen. Nach meiner Internetrecherche erscheint mir die Meinung deutlich in die Richtung zu gehen, dass `pytest` besser sei als das in der stdlib bereits vorhandene `unittest`-Modul.
Außerdem bringe ich eine Konfiguration für GitHub-Actions mit. Ich habe dort konfiguriert, dass die Tests bei jedem PR ausgeführt werden. Außerdem ist ein style-checker (`flake8`) mit dabei, der automatisch den Code auf diverse Style-regeln überprüft. Ich habe den checker so eingestellt, dass er erstmal nur auf die Dateien in `packages` geht, sonst würden wir erschlagen von der Anzahl der Meldungen.
=> First unit test and GitHub actions

regel.sh
Follow-up to https://github.com/snaptec/openWB/issues/1674 which has a bug
/cc @snaptec
=> Fix swapped timestamp/date

modules/et_awattarcap/awattarcapgetprices.py
Ausgabe in Debug-Log
Array-Initialisierung fehlgeschlagen (verhindert Updates zwischen Mitternacht und 14 Uhr)
=> Awattar Hourly Cap - Bugfixes

web/display/colors/powergraph.js, web/themes/colors/powergraph.js
Korrektur des Codes zur korrekten Anzeige des Live-Graphen beim Tageswechsel
In beiden Varianten des Color-Themes, für Display und Browser
=> Colors theme: Fix midnight anomaly

runs/mqttsub.py
- add email separation from plain text messages
- add json message format for future use
=> fix SendDebug from Cloud

web/settings/network.php
- trigger update of wpa_supplicant.conf to remove old credentials
- directly reboot system
=> fix wlan reset

README.md
Also hint to Stretch and Buster.
=> Readme New Link to Raspbian Images

web/display/colors/chargePointList.js, web/display/colors/index.html, web/display/colors/pricechart.js, web/display/colors/style.css
Wie im Forum besprochen, ist das Konfig-Fenster teilweise zu gross fürs eingebaute Display. Das wurde korrigiert.
=> Fix: Colors theme for display: Reduce  size of config screen

runs/initRamdisk.sh
=> init isss.log in ramdisk

runs/mqttsub.py, runs/senddebug.sh
fixed missing "e" in "debugemail"
=> fix debuglog from cloud

runs/mqttsub.py, runs/senddebug.sh
- fix linebreak in header
- add email to debuguser message (same as local debugmessage)
=> debuglog fix linebreak

web/display/colors/chargePointList.js, web/display/colors/index.html, web/display/colors/pricechart.js
Eine weitere Anpassung der Fenstergrösse, damit der Config-Screen aufs interne Display passt
=> Colors theme fix: Adjust display size

slavemode.sh
Allows full 32 A charge current even in slow mode and start reducing charge current a bit earlier.
=> Handle corner case in slow mode of slave mode

web/display/colors/index.html
Korrektur des Config-Screens, wie im Forum besprochen.
=> Fix for color theme: Config screen corrected

web/status/status.php
logfiles are loaded if collapsible is opened by user to reduce initial loading time
=> async loading of logfiles on staus page

packages/helpermodules/log.py, packages/modules/alpha_ess/bat.py, packages/modules/alpha_ess/counter.py, packages/modules/alpha_ess/device.py, packages/modules/alpha_ess/inverter.py, packages/modules/common/component_state.py, packages/modules/common/fault_state.py, packages/modules/common/lovato.py, packages/modules/common/modbus.py, packages/modules/common/mpm3pm.py, packages/modules/common/sdm630.py, packages/modules/common/simcount.py, packages/modules/common/store.py, packages/modules/openwb/counter.py, packages/modules/openwb/device.py, packages/modules/openwb/inverter.py, packages/modules/openwb_flex/counter.py, packages/modules/openwb_flex/device.py, packages/modules/openwb_flex/inverter.py, packages/modules/openwb_flex/versions.py
Entfernen des try/except-Konstrukts wie in der Anmerkung zu PR #1710 beschrieben.
=> remove try except for imports

runs/updateConfig.sh, web/settings/autoLock.php, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php, web/settings/mqtt.php
- modulconfigevu
- modulconfigpv
- modulconfigbat
- mqtt bridge settings
- autolock settings
=> fix some html and php warnings

web/display/colors/chargePointList.js, web/display/colors/powerdata.js
Fix the setting of the maximum price with price based charging
=> Color theme fix: max price setting

web/settings/smarthomeconfig.php
Text in Smarthomeconfig angepasst für Shelly Plus
=> Smarthomeconfig shelly plus

web/display/colors/index.html
Korrektur der Darstellung, um Scrollbalken auf dem Display zu vermeiden
=> Colors theme: Fix display size

runs/mqttsub.py, slavemode.sh
In case of dynamic load management the imbalance shall be obeyed at the E-Mobility charge system connection. This is because we don't want to compensate imbalance for Heatings, Ovens or Washing machines etc. in flats connected to the same house's connection.  
The absolute load, however, will have to respect the those for not to overload the cable into the house.
For technical solution we need to send the load values of the E-Mobility system in addition to the already existing total load values.
This commit prepares for reception and processing of those values in imbalance handling.
Finally also removed a no longer used (written but never read) ramdisk file.
=> LoadManagement Slave: Independent Total Power values for Imbalance

modules/bezug_sonneneco/sonneneco.py, modules/speicher_sonneneco/sonneneco.py
- add type hinting for defined methods
- remove duplicate strings
- usage of method "check_write_value"
- add example json data for API V1
=> fix modules for sonneneco

web/themes/colors/chargePointList.js, web/themes/colors/powerdata.js, web/themes/colors/pricechart.js, web/themes/colors/style.css, web/themes/colors/theme.html
=> Colors theme: Optimize layout

runs/atreboot.sh, runs/cronnightly.sh
=> fix stalled atreboot.sh

modules/soc_evnotify/evnotify.py, packages/modules/alpha_ess/device.py, packages/modules/carlo_gavazzi/device.py, packages/modules/common/simcount.py, packages/modules/janitza/device.py, packages/modules/openwb/device.py, packages/modules/openwb_flex/device.py, packages/modules/powerdog/device.py, packages/modules/saxpower/device.py, packages/modules/siemens/device.py, packages/modules/solax/device.py, packages/modules/sunny_island/device.py, packages/modules/victron_inverter/device.py
Nutze den CLI parser aus #1793 wo es ohne große Umstände machbar ist.
=> use automatic CLI parse in modules where easily possible

modules/speicher_powerwall/main.sh, modules/speicher_powerwall/powerwall.py, modules/speicher_powerwall/powerwall_test.py
Das Powerwall-Script ist eindeutig kaputt. Siehe auch [dieser Thread im Forum](https://openwb.de/forum/viewtopic.php?f=5&t=4468). Seit commit 1fdbf18d979df4591260e9f6b9dc04c555c1dc69 bzw. #1508 
Dieser PR soll das beheben. Ob es tut...? Ich kann es nicht testen. Habe aber im Forum um einen Test gebeten.
=> Fix powerwall

packages/modules/http/device.py
Korrektur wie in PR #1825  vorgeschlagen.
=> fix to use IPv6 and hostnames

web/settings/modulconfigpv.php
Überarbeitung Beschreibung  für Auslesen zusätzliches SolarEdge SmartMeter.
=> Update Beschreibung in  modulconfigpv.php (SolarEdge)

modules/wr_sunways/main.sh, packages/modules/sunways/device.py, packages/modules/sunways/inverter.py
Überarbeitung wie in PR #1806 vorgeschlagen.
=> fix sunways

packages/modules/http/api.py, packages/modules/http/bat.py, packages/modules/http/counter.py, packages/modules/http/inverter.py
Fix für diesen Kommentar: https://github.com/snaptec/openWB/issues/1827#issuecomment-996871913
Kurz gesagt: Wenn "none" eingetragen war wurde die URL trotzdem aufgerufen. Das sollte nicht.
Nicht getestet! (Eigentlich wäre es natürlich auch hier gut, wenn es Unittests gäbe).
=> fix: HTTP-module: if a path is configures with "none", do not call the URL

modules/wr_solaredge/solaredgeall.py
Wie der Titel schon sagt... Motiviert durch [diesen Beitrag](https://openwb.de/forum/viewtopic.php?p=52810#p52810) im Forum und Folgende.
Nebenbei habe ich noch was in der Spec gelesen und dabei festgestellt, dass auch die Energiemenge einen Scale-Factor hat udn eigentlich ein uint32 ist. Das bisher hat es wohl bei der Scale noch niemand dem es wichtig war über 0 hinaus geschafft ;-).
Ich habe allerdings auch in der Spec gelesen, dass alle 32bit Werte wordorder=little endian haben. Das ist aber bei der Energie offenbar nicht der Fall. Merkwürdig. Das habe ich also nicht geändert.
=> fixed: filter currents for supported values, add scale factor to energy and filter power<0

packages/modules/http/bat.py, packages/modules/http/counter.py, packages/modules/http/inverter.py
small fix for wrong dictionary access leads to "KeyError" exception (came with PR #1831)
Fix tested with openWB series 2+ and http evu module
=> Fix http device counter dictionary access

modules/speicher_bydhv/byd.py, modules/speicher_bydhv/byd_test.py, modules/speicher_bydhv/byd_test_sample.html
Im Forum [erzählt](https://openwb.de/forum/viewtopic.php?p=52860#p52860) [man sich](https://openwb.de/forum/viewtopic.php?p=52722#p52722) dass BYD-Modul wäre kaputt.
Ich habe keine Batterie. Ich kann es nicht testen (außer durch den Unittest der anbei ist). Ich habe es nur programmiert auf Basis der Informationen die mir andere gegeben haben.
Wer kann sei eingeladen den PR zu testen.
=> Fix broken BYD module

packages/modules/carlo_gavazzi/counter.py, packages/modules/common/modbus.py, packages/modules/common/sdm.py
Carlo Gavazzi nutzt int16 zur Dekodierung der Frequenz.
=> Fix use int16 for carlo

packages/modules/common/fault_state.py, packages/modules/evnotify/EVNotify.py
Soc FaultStr im Faultstate-Modul ergänzt
=> pub soc faultstr, fix inverter topic for 2.x

modules/wr_kostalpikovar2/kostal_piko_var2.py, modules/wr_kostalpikovar2/kostal_piko_var2_test.py, modules/wr_kostalpikovar2/kostal_piko_var2_test_sample.html
Basierend auf [diesem Forenthread](https://openwb.de/forum/viewtopic.php?f=9&t=4529).
Bei genauerer Betrachtung konnte der bisherige Quelltext unmöglich funktionieren. Der PR ist zwar bisher ungetestet, aber mehr kaputt gehen kann dadurch auch nicht ;-).
=> fix kostal piko var2 (was completely broken)

packages/modules/fronius/inverter.py
Beim Abschalten eines 2. WR wird die Regellogik im Froniusmodul abgebrochen.
Mit diesem Fix wird die Leistung des 2. WR auf 0 gesetzt, wenn er nicht (mehr) erreichbar ist und die Regellogik fortgesetzt.
Damit kann der Hausverbrauch auch während des Nachtmodus eines 2. WR behandelt werden.
siehe https://openwb.de/forum/viewtopic.php?p=53730#p53730
=> Fronius: Fix Nachtmodus 2. WR

packages/modules/common/req.py, packages/modules/evnotify/api.py, packages/modules/evnotify/api_test.py, packages/modules/fronius/bat.py, packages/modules/fronius/counter_s0.py, packages/modules/fronius/counter_sm.py, packages/modules/fronius/inverter.py, packages/modules/http/api.py, packages/modules/json/device.py
Loggen der Get-Response, Prüfen auf Exceptions und Extrahieren des Text-/Json-Contents in einem eigenen Modul.
=> common module for get responses

packages/modules/fronius/bat.py, packages/modules/fronius/device.py
siehe https://openwb.de/forum/viewtopic.php?p=54093#p54093
Fix für Inverter-Pfad im JSON.
Außerdem wird dynamisch entschieden, wo der SoC im Response angegeben ist.
=> Fronius: SoC of battery

modules/bezug_discovergy/discovergy.py, modules/bezug_discovergy/discovergy_test.py
PR #1802 hat den Fix aus #1514 entfernt. Dieser wurde wieder hinzugefügt.
Alternative Antwortmöglichkeit zum Test hinzugefügt.
=> undo removing fix for different json-answers

modules/bezug_sungrow/main.sh, modules/speicher_sungrow/main.sh, modules/wr2_sungrow/main.sh, modules/wr_sungrow/main.sh, packages/modules/sungrow/device.py
Zum Zwecke der Performanceoptimierung (siehe #1837, #1838)
Außerdem habe ich die Funktion `legacy_run` für sungrow refactored um sie kürzer und verständlicher zu machen.
Das ganze ist noch NICHT getestet.
=> use legacy run for sungrow

packages/helpermodules/exceptions/requests.py, packages/modules/common/fault_state.py, packages/modules/json/device.py
fix requests registry log message
fix component update context for json module
fix topic mapping fault state
=> Fix exception handling

modules/speicher_studer/main.sh, modules/wr_studer/main.sh, packages/modules/studer/device.py
Zum Zwecke der Performanceoptimierung (siehe #1837, #1838)
Außerdem legacy_run refactored für kürzer und leichter zu verstehen.
=> use legacy run for studer and refactor legacy_run function

packages/modules/common/lovato.py, packages/modules/common/mpm3pm.py, packages/modules/common/sdm.py, packages/modules/common/store/_counter.py, packages/modules/openwb_flex/counter.py, packages/modules/openwb_flex/inverter.py
Vereinheitlichung der Topics für 2.x:
current -> currents
voltage -> voltages
power_phase -> powers
power_factor -> power_factors
=> unify topic names

packages/modules/alpha_ess/bat.py, packages/modules/alpha_ess/inverter.py, packages/modules/carlo_gavazzi/counter.py, packages/modules/fronius/bat.py, packages/modules/fronius/counter_s0.py, packages/modules/fronius/counter_sm.py, packages/modules/fronius/inverter.py, packages/modules/huawei/bat.py, packages/modules/huawei/counter.py, packages/modules/huawei/inverter.py, packages/modules/janitza/counter.py, packages/modules/json/bat.py, packages/modules/json/counter.py, packages/modules/json/inverter.py, packages/modules/openwb_flex/counter.py, packages/modules/powerdog/counter.py, packages/modules/powerdog/inverter.py, packages/modules/saxpower/bat.py, packages/modules/siemens/bat.py, packages/modules/siemens/counter.py, packages/modules/siemens/inverter.py, packages/modules/solax/bat.py, packages/modules/sungrow/bat.py, packages/modules/sungrow/counter.py, packages/modules/sungrow/inverter.py, packages/modules/victron/bat.py, packages/modules/victron/counter.py, packages/modules/victron/inverter.py
This reverts commit 5af1ecbb6d2c8b35a775a431bc0412e46fcad008.
=> Revert "simulation data in module get-topic"

slavemode.sh
Lines 684-695 are the relevant ones.
Rest is just improved debug output.
=> Slave mode: Improve robustness in case of heartbeat error

modules/sdm120modbusSocket/readsdm.py, slavemode.sh
The two recently integrated improvements have been cherry-picked to avoid interference esp. with openWB v 2.0 rework commits.
=> Two cherry-picked commits for yc/beta please

modules/bezug_powerwall/powerwall.py, modules/bezug_solaredge/solaredge.py, packages/modules/saxpower/bat.py
fix unify topic names -> solaredge, powerwall
fix reading two registers in saxpower battery
=> Fix solaredge saxpower

modules/wr_tripower9000/tripower.py
Anpassung zum Kommentar in PR #1915
=> remove headers in request

web/settings/modulconfiglp.php
fix copy/paste typo which was changing power module on cp1
=> fix modulconfiglp twcmanager settings on cp2

modules/bezug_fems/fems.py
Offenbar können nicht alle FEMS mit den Regex-Requests aus PR #1533 umgehen. Daher ein Fallback auf die Einzelabfrage.
=> fallback to non regex-request

web/display/colors/chargePointList.js, web/display/colors/powerdata.js
Wie im Forum diskutiert, Kürzen von kWh/km-Werten, um Zeilenumbrüche zu vermeiden
=> Fix for display color theme: number lengths

modules/sdm120modbusSocket/readsdm.py, slavemode.sh
Improvements of yc/beta to be integrated into yc/stable
=> Integrate latest yc/beta into yc/stable

loadvars.sh
- remove old simcount for EVU and Battery
- remove obsolete update of pvwatt
=> cleanup loadvars for new sonnenbatterie modules

modules/bezug_smartfox/smartfox.py
Module gefixed, funktioniert mit dem Fix bei mir in 1.9.250 wieder ohne Probleme. 
Fixes #1923
=> Fix module bezug_smartfox

runs/mqttsub.py
Mir fiel zufällig beim Lesen vom Code auf:
```python
if (msg.topic == "openWB/set/pv/1/WhCounter"):
if (float(msg.payload) >= 0 and float(msg.payload) <= 10000000000):
f = open('/var/www/html/openWB/ramdisk/pvkwh', 'w')
f.write(msg.payload.decode("utf-8"))
f.close()
if (msg.topic == "openWB/set/pv/2/kWhCounter"):
if (float(msg.payload) >= 0 and float(msg.payload) <= 10000000000):
pvkwhcounter=float(msg.payload.decode("utf-8"))*1000
f = open('/var/www/html/openWB/ramdisk/pvkwh', 'w')
f.write(str(pvkwhcounter))
f.close()
```
Das kann so nicht richtig sein, dass beide topics in die gleiche Datei schreiben. Wo ich schon dabei war habe ich den ganzen Block etwas vereinfacht.
Ist allerdings noch völlig ungetestet. Noch nichtmal überhaupt ausgeführt.
=> fix: openWB/set/pv/2/kWhCounter was delegating to same ramdisk file as openWB/set/pv/1/WhCounter

README.md, modules/bezug_e3dc/e3dc.py, modules/speicher_powerwall/powerwall.py, modules/wr_powerwall/powerwall.py, modules/wr_solarlog/solarlog.py, packages/modules/alpha_ess/counter.py, packages/modules/alpha_ess/inverter.py, packages/modules/common/component_state.py, packages/modules/discovergy/api.py, packages/modules/discovergy/api_test.py, packages/modules/fronius/inverter.py, packages/modules/json/inverter.py, packages/modules/openwb_flex/bat.py
- remove individual current calculation from packages modules
- add current calculation in `component_state.py`
- fix formatting and spelling
=> calc missing currents at component_state

packages/legacy_run_server.py
Aktuell, wenn eine Exception in einem legacy-run Prozess fliegt und nicht gefangen wird, tauch der Fehler nirgends auf. Eigentlich war meine Absicht das mit dem sys.excepthook zu verhindern, aber das geht nicht weil der nur für den main-thread greift.
Außerdem ist es auch ungünstig, dass Ausgaben auf stdout und stderr komplett ignoriert werden. Da sollte zwar auch nichts kommen, aber wenn doch, dann wäre es sinnvoll das zumindest zu loggen, damit man das Problem finden kann. Und leider lässt sich das in Python eingebaute argparse auch nicht so leicht davon überzeugen nicht einfach zu stderr zu loggen und exit aufzurufen (möglich wäre es, das nimmt dann aber größere Dimensionen an).
Mit diesem PR will ich das verbessern und dafür Sorgen, dass Probleme auch im Log landen.
=> Legacy run: log stdout, stderr, exceptions

packages/modules/common/component_state.py
fallback calculation of currents relies on powers
=> fix order of calculated states

web/display/colors/chargePointList.js, web/display/colors/index.html, web/display/colors/powerdata.js, web/display/colors/processAllMqttMsg.js
Wie im Forum besprochen, Unterstützung für RFID-Codes ergänzt und die Wahlmöglichkeit für EV/Batterie-Priorität wiederhergestellt.
=> Fix for colors theme for display: Add priority selection and rfid support

web/css/settings_style.css, web/settings/modulconfiglp.php
=> fetch vehicle list on demand only

packages/modules/sungrow/counter.py, packages/modules/sungrow/device.py, packages/modules/sungrow/inverter.py
word order for 32 bit is little endian
=> fix sungrow decoding

modules/wr_solaredge/solaredgeall.py
catch wrong configured setting "Weiteres SmartMeter auslesen" and report to debug log
=> catch extprod readiing error in wr_solaredge

runs/isss.py
fix errors reported by flake8 in isss.py for better readability
=> fix formatting

graphing.sh, regel.sh, runs/cron5min.sh, runs/cronnightly.sh, runs/csvcalc.py
- fix socmodule check in `graphing.sh`
- change regulation loop timing message to level debug if timing is normal in `regel.sh`
- add file extension to filename variable in `cron5min.sh` and `cronnightly.sh`
- cleanup and formating of `csvcalc.py`
=> formating and minor cleanup

modules/keballlp1/check502.py, modules/keballlp1/setcurrkeba.py, packages/helpermodules/pub.py, packages/modules/common/component_context.py, packages/modules/common/component_state.py, packages/modules/common/modbus.py, packages/modules/http/counter.py, packages/modules/http/device.py, packages/modules/huawei/device.py, runs/dac.py, runs/evsewritemodbus.py, web/settings/modulconfigpv.php
- fix mixup of powers/currents in http counter module
- add fallback to calculate powers from currents if available (counter components)
- fix some formatting and spelling
- breaking change introduced earlier: http inverter power has to be negative for production! updated description
=> Bugfix http counter

packages/modules/solax/counter.py, packages/modules/solax/inverter.py
- fix endianess for 32bit values
- add counter phase powers
- fix inverter counter scale
=> fix solax modbus wordorder

modules/wr_solarlog/main.sh, modules/wr_solarlog/solarlog.py
added debug output to wr_solarlog module
=> add wr_solarlog logging

packages/modules/siemens/bat.py, packages/modules/siemens/counter.py, packages/modules/siemens/inverter.py
- close connection after reading
=> fix siemens modbus connection

packages/modules/sunny_island/bat.py
missed sunny_island module in #1973
=> fix not closed modbus connection sunny_island

runs/isss.py
- mostly fixes reported by flake8
- fixed loglevel reading (L86)
=> formatting and bugfix

modules/wr_huawei/main.sh, packages/modules/huawei/device.py, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php
only read data for configured modules
=> huawei: read configured modules only

modules/soc_manual/soc_manual.py
=> manual soc: limit to 100%

packages/modules/common/mpm3pm.py
Import, Export und Power Factor müssen anders als in der Dokumentation angegeben faktorisiert werden.
=> fix factorization

.gitignore, helperFunctions.sh, modules/soc_tesla/main.sh, regel.sh, runs/cronnightly.sh, runs/senddebug.sh, runs/setvirtips.sh, runs/updateConfig.sh, web/settings/senddebug.php
- add 1min with debug=2 to debuglog
- add `__pycache__` to .gitignore
- fix warnings in helperFunctions.sh
=> extend debug log

packages/modules/sma/device.py
Bisher wurde nur das erste ankommende Datagramm geprüft, das ist hiermit behoben.
=> wait for several datagrams

packages/modules/common/simcount.py
Da das Auslesen der Zählerstände bei manchen Fronius-Geräten Probleme bereitet, wurden die Fronius-Module auf simcount umgestellt. Mit diesem PR startet simcount mit den vorhandenen Zählerständen, sofern diese existieren.
=> start simcount with existing counter values

modules/soc_vwid/README.txt, modules/soc_vwid/_secrets.py, modules/soc_vwid/main.sh, modules/soc_vwid/soc_vwid.py, runs/atreboot.sh, runs/updateConfig.sh, web/settings/modulconfiglp.php
fixes: 
- modules/soc_vwid: optionally add missing python3 module secrets.py - used on python3.5/stretch only
- modules/soc_vwid.py: clean obsolete code
- modulconfiglp.php: fix LP1 password name mismatch passwort/password
- updateConfig.sh: initialize missing interval config params for lp1
=> fix issues: secrets.py on stretch, etc.

web/themes/colors/powerdata.js, web/themes/colors/processAllMqttMsg.js, web/themes/colors/setupMqttServices.js, web/themes/colors/theme.html
Wie im Forum besprochen, wurde die Eingabe von Codes ergänzt, falls RFID aktiviert ist.
=> Color theme: Add RFID code input

runs/atreboot.sh
=> update package list only once

packages/modules/solax/counter.py
fix scale of read values ( /100 -> *10) to get total energy in Wh
=> fix solax import/export counter scale

packages/modules/sma_shm/device.py
fix default_config "type" after renaming module
=> fix missed sma reference

packages/modules/discovergy/device.py, packages/modules/sma_shm/device.py
=> rename __components to _components

modules/bezug_victrongx/main.sh, modules/wr_victron/main.sh, packages/modules/victron/counter.py, packages/modules/victron/device.py, runs/updateConfig.sh, web/settings/modulconfigevu.php
Auslesen des EVU-Zählers über Energy Meter oder AC Eingänge
=> Victron grid gx

modules/bezug_lgessv1/lgessv1.py, modules/bezug_lgessv1/main.sh, modules/speicher_lgessv1/lgessv1.py, modules/speicher_lgessv1/main.sh, modules/wr_lgessv1/lgessv1.py, modules/wr_lgessv1/main.sh
- fix auth check
- formatting
- fix quoting in main.sh
=> fix lg ess modules

packages/modules/sunways/device.py, packages/modules/sunways/inverter.py
- remove default ip
- fix read_legacy: add ip and password to device_config
- add missing params to inverter component request
- fix parsing values
- add example output
=> fix sunways inverter

packages/modules/sonnenbatterie/bat.py, packages/modules/sonnenbatterie/counter.py, packages/modules/sonnenbatterie/inverter.py
response from variant 2 is float
=> fix sonnenbatterie variant 2 datatype

modules/bezug_lgessv1/lgessv1.py, modules/bezug_lgessv1/main.sh, modules/speicher_lgessv1/lgessv1.py, modules/speicher_lgessv1/main.sh, modules/wr_lgessv1/lgessv1.py, modules/wr_lgessv1/main.sh
LG wird mit Hilfe des Legacy Run Servers ausgelesen. Alle weiteren Anpassungen sind in #2050 enthalten. Dieser soll allerdings erst nach Fertigstellung der Beta gemergt werden.
=> use legacy run server

runs/atreboot.sh, web/notready.html, web/settings/update.php
atreboot.sh:
- send current PID to kill command
- fix some quoting
update:
- do not allow concurrent update calls (only prevented in web gui, must be extended to update skript)
- add links to status and settings in "not ready" page
=> tweak update procedure

web/settings/update.php
=> fix checking updateinprogress in web gui

modules/bezug_powerwall/powerwall.py
- remove buggy parsing of firmware version
=> fix reading detailed measurements

modules/bezug_powerwall/powerwall.py
- fix declaration of multiple errors to catch
- fix list index access
=> fix except multiple errors

modules/bezug_mpm3pm/readmpm3pm.py, modules/bezug_varta/varta.py, modules/speicher_tesvoltsma/tripower.py, modules/speicher_varta/varta.py, modules/wr2_solaredge/solaredge.py
Durch die Umstellung von Python 2 auf 3 wird das decode nicht mehr benötigt.
=> fix decode

modules/wr2_kostalpiko/main.sh, modules/wr_kostalpiko/main.sh
fixes "ImportError: No module named '1'"
=> fix kostalpikovar1 typo

modules/bezug_mpm3pm/main.sh, modules/bezug_mpm3pm/readmpm3pm.py, modules/bezug_varta/main.sh, modules/bezug_varta/varta.py, modules/speicher_tesvoltsma/main.sh, modules/speicher_tesvoltsma/tripower.py, modules/speicher_varta/main.sh, modules/speicher_varta/varta.py, modules/wr2_solaredge/main.sh, modules/wr2_solaredge/solaredge.py, web/settings/modulconfigbat.php
- fix errors introduced by upgrade from python 2 to 3
- fix shellcheck warnings
- removed old debug output in modulconfig_bat.php (sonnenbatterie)
updated modules:
- bezug_mpm3pm
- bezug_varta
- speicher_tesvoltsma
- speicher_varta
- wr2_solaredge
=> really fix decode error

modules/wr_kostalpiko/main.sh
=> kostal piko add missing parameter

modules/soc_eq/auth.py
Fix for Quoting Issues in #2036 in soc_eq
=> Fixing Single Quote Issue in soc_eq

web/themes/colors/powerdata.js, web/themes/colors/powergraph.js
Wie im Forum vorgeschlagen, werden in Energy-Graph für den Tag oder Monat jetzt auch einzelne Devices angezeigt, nicht nur der summierte Wert
=> Colors theme fix: Einzelne Devices im Energy-Graph

web/themes/colors/chargePointList.js, web/themes/colors/powerdata.js
Neue Variante für die Darstellung von W / Wh, entsprechend Vorschlag im Forum
=> colors theme fix: modify decimal place display

modules/wr2_kostalpikovar2/main.sh, modules/wr_kostalpikovar2/main.sh, web/settings/modulconfigpv.php
- add parameter description for url
- add http as default protocol if missing
- fix debug output for wr2 to use right variables
=> kostalpikovar2 add default protocol

modules/wr2_ethsdm120/main.sh, modules/wr2_ethsdm120/readsdm120.py, modules/wr_ethsdm120/main.sh
- fix reading wrong ramdisk file
- cleanup of bash and python skripts
=> fix wr2_ethsdm120

loadvars.sh, modules/wr2_solaredge/solaredge.py
- return power as integer
- add info to debuglog if modules return unexpected values
=> Bugfix: wr2_solaredge

runs/senddebug.sh
- fix shellsheck warnings and errors
- remove reference to absolute path /var/www/html/openWB
- extend openWB.log to 1500 lines as we have much more detailed logging now
=> extend senddebug

modules/bezug_rct2/main.sh, modules/bezug_rct2/rct_lib.py, modules/bezug_rct2/rct_read.py, modules/bezug_rct2/rct_read_bezug.py, modules/bezug_rct2/rct_read_speicher.py, modules/bezug_rct2/rct_read_speicher_info.py, modules/bezug_rct2/rct_read_status.py, modules/bezug_rct2/rct_read_wr.py, modules/bezug_rct2/status.sh, modules/speicher_rct2/info.sh, modules/speicher_rct2/main.sh, modules/wr_rct2/main.sh
- fix shellsheck errors and warnings
- fix formating of python files (flake8)
- use context managers for resources where possible
- fix mqtt topics for fault strings and states
=> update rct2 modules

modules/smarthome/mqtt/watt.py
Devicenummer wird beim Subscribe mitgegeben. Somit können mehre MQTT devices parallel in smarthome 2.0 arbeiten.
Siehe auch:
https://openwb.de/forum/viewtopic.php?p=60220#p60220
=> samrthome mqtt

modules/soc_i3/index.php
Module update to fit new api.
This is just a quick fix. Please excuse my bad programming skills.
=> Update SoC BMW and Mini to new API

modules/soc_i3/index.php
Reverts snaptec/openWB#2105
Has to be merged into master
=> Revert "Update SoC BMW and Mini to new API"

modules/soc_i3/index.php
Newer PHP versions are more critical to this error.
=> Syntax error in line 209 fixed

web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php
add warning message in modulconfig pages to indicate beta state of rct v2 modules
=> add warnings to rct v2 modules

runs/updateConfig.sh
add missed upgrade for renamed "soc_http1"
=> fix: upgrade soc_http1 in updateConfig.sh

packages/modules/sma_modbus_tcp/device.py, packages/modules/sma_modbus_tcp/inverter_modbus_tcp.py, packages/modules/sma_modbus_tcp/inverter_webbox.py
=> Revert "sma changed modbus register"

modules/bezug_solarwatt/main.sh, modules/bezug_solarwatt/solarwatt.py, modules/speicher_solarwatt/main.sh, modules/speicher_solarwatt/solarwatt.py, modules/wr_solarwatt/main.sh, modules/wr_solarwatt/solarwatt.py
- fix shellsheck warnings
- fix dict usage in `speicher_solarwatt`
- change some variable names for readability
=> fix solarwatt battery module

modules/bezug_kostalplenticoreem300haus/kostal_plenticore.py, modules/bezug_kostalplenticoreem300haus/main.sh, modules/wr_plenticore/main.sh
fix missing file if the plenticore is configured without battery
=> fix bezug_kostalplenticoreem300haus without battery

web/themes/colors/powerdata.js, web/themes/colors/theme.html
Der neu eingeführte "Code" Button wurde bei manchen Bildschirmgrössen nicht korrekt angezeigt und war ein bisschen zu prominent auf der Hauptseite.
Er wurde ins Modal für die Lademodus-Auswahl verschoben.
=> Colors theme - layout fix

runs/usmarthome/smartbase.py
Temperatur sensoren werden bei Shelly wieder auf die Ramdisk geschrieben, sonst nicht im Log
=> shelly smarthome mq

runs/isss.py
With #1954 bare except statements were removed. This PR adds some more errors to catch and more detailed logging in case of errors.
=> catch ValueError and add more logging

modules/smarthome/acthor/watt.py, runs/mqttsub.py, runs/usmarthome/smartacthor.py, web/settings/smarthomeconfig.php
=> acthor & samrtmq

web/display/colors/chargePointList.js, web/display/colors/index.html, web/display/colors/style.css
Anpassung der Chargemode-Buttons gemäss Diskussion im Forum
=> Display colors theme - fix chargemode buttons

modules/soc_vwid/main.sh, modules/soc_vwid/soc_vwid.py
PR adds writing json reply of soc query to ramdisk file to make support easier
=> write reply to ramdisk/soc_vwid_reply_lpx

runs/isss.py
GPIO.input() returns an integer value, not bool
=> fix socket lock state in slave mode

loadvars.sh, modules/soc_i3/i3soc.py, modules/soc_i3/main.sh
- extend logging in method `run_soc_module` in `loadvars.sh`
- fix warnings and errors reported by flake8 in `i3soc.py`
- fix warnings and errors reported by shellcheck in `soc_i3/main.sh`
=> extend bmw soc module logging

modules/smarthome/vampair/off.py, modules/smarthome/vampair/on.py, modules/smarthome/vampair/watt.py, runs/mqttsub.py, runs/smarthomemq.py, runs/usmarthome/smartbase.py, runs/usmarthome/smartvampair.py, web/settings/smarthomeconfig.php, web/settings/topicsToSubscribe_smarthomeconfig.js
WP Vampair wird erstmalig unterstützt. Der gerechnete Überschuss wird laufend übertragen...
=> vampair WP

modules/bezug_ethmpm3pm/main.sh, modules/speicher_sdmaevu/main.sh, modules/wr_ethmpm3pmaevu/main.sh, packages/modules/openwb_bat_kit/bat.py, packages/modules/openwb_bat_kit/device.py, packages/modules/openwb_evu_kit/bat.py, packages/modules/openwb_evu_kit/device.py, web/settings/modulconfigbat.php
SDM630-Zähler kann als eigenständiges Kit oder als Zähler am EVU-Kit konfiguriert werden.
=> Speicher Zähler an EVU-Kit

modules/soc_i3/i3soc.py
Support für Mini hinzugefügt
Fehlermeldungen hinzugefügt
=> [BMW/Mini] - Support für Mini hinzugefügt

modules/bezug_solaredge/main.sh, modules/speicher_solaredge/main.sh, modules/wr_solaredge/main.sh, web/settings/modulconfigbat.php
- fix shellcheck warnings
- allow port setting in `modulconfigbat.php` with `IP:Port`
=> solaredge bat allow port setting

nurpv.sh, regel.sh, runs/set-current.sh
- fixed a bug in pv charging with multiple charge points; current was not updated if a chargepoint got enabled
- moved logging in `set-current.sh` to openWB.log
- fixed initialization of phase count for charge point 2
- fixed several shellcheck warnings
=> Bugfix: start pv charging

runs/updateConfig.sh, web/settings/modulconfigbat.php
- fix typo in `modulconfigbat.php`
- remove not used setting of `alphaessip`
=> fix alpha ess ip setting

packages/modules/batterx/device.py, packages/modules/common/fault_state.py, packages/modules/discovergy/counter.py, packages/modules/discovergy/device.py, packages/modules/discovergy/inverter.py, packages/modules/fronius/device.py, packages/modules/good_we/device.py, packages/modules/http/device.py, packages/modules/huawei/device.py, packages/modules/janitza/device.py, packages/modules/json/bat.py, packages/modules/json/counter.py, packages/modules/json/device.py, packages/modules/json/inverter.py, packages/modules/openwb_flex/device.py, packages/modules/powerdog/device.py, packages/modules/saxpower/device.py, packages/modules/siemens/device.py, packages/modules/sma_shm/counter.py, packages/modules/sma_shm/device.py, packages/modules/sma_shm/inverter.py, packages/modules/solax/device.py, packages/modules/sunny_island/device.py, packages/modules/sunways/device.py, packages/modules/tesla/device.py, packages/modules/victron/bat.py, packages/modules/victron/counter.py, packages/modules/victron/device.py
- remove sone not needed conversions to str
- tweaked some default config settings of devices and components
=> updated defaults for components

packages/modules/fronius/device.py
Bugfix zu [https://openwb.de/forum/viewtopic.php?p=65599#p65599](url)
=> fix second fronius inverter

packages/modules/sma_modbus_tcp/inverter_modbus_tcp.py, packages/modules/sma_modbus_tcp/inverter_version.py
Forum: [https://openwb.de/forum/viewtopic.php?p=65708#p65708](url), [https://openwb.de/forum/viewtopic.php?p=65800#p65800](url)
=> fix sma inverter version

modules/wr2_ethlovato/main.sh, modules/wr_pvkit/main.sh, web/settings/modulconfigpv.php
- fix version in settings page
- fix wrong variable in wr2_ethlovato/main.sh
=> fix pv2 pvkit version

modules/bezug_victrongx/main.sh, modules/speicher_victron/main.sh, modules/wr_victron/main.sh
[https://openwb.de/forum/viewtopic.php?p=66052#p66052](url)
=> pass modbus id for victron bat

runs/usmarthome/smarthttp.py
Überschuss als String übergeben für http devices
=> smartmq http devices

packages/modules/json/bat.py
Speicher_json hat bei mir nicht funktioniert, nach einigen Edits tut es nun für mich - bitte prüfen, bin kein Python-Entwickler, wollte nur etwas ans Projekt zurückgeben. hth
=> minor bug fixes; python-style equals NoneType

web/settings/helperFunctions.js, web/settings/setPassword.php
- add second input field for verification
- enable to show password by click on icon
=> user friendly passwort settings

web/settings/cloudconfig.php
- add implemented password check to cloudconfig.php
=> check password cloudConfig.php

ladelog.sh, runs/initRamdisk.sh, web/settings/settings.php
- fix shellcheck warnings and errors
- use a function and loop over all charge points
- enable average consumption for charge points 4 to 8 in settings
- add debug logging
- modify calculations for better accuracy
=> Ladelog rewrite

web/settings/settings.php
Info zu der Modulkonfiguration Ladepunkte ergänzt, da zumindest die Aktivierung von Ladepunkt 2 Auswirkungen auf den Betrieb als "nur Ladepunkt" hat.
=> add isss info regarding charge point configuration

modules/soc_i3/i3soc.py
API endpoint changed
Data fields changed
=> [BMW/Mini] - Hotfix - API changes

runs/atreboot.sh, runs/cron5min.sh, runs/ladetaster.py
- add message in `atreboot.sh`
- start/stop daemon in `cron5min.sh` similar to all other daemons
- refactor daemon and port to python3
- run daemon without `sudo` as user "pi"
=> rewrite push button daemon

runs/atreboot.sh
In Konkurrenz zu #2329 
Siehe auch Diskussion in #2328
=> in atreboot.sh kill using sudo

runs/atreboot.sh, runs/upgradeChargeLogs.py
- remove EUR sign in log message
=> fix error caused by euro sign

.gitignore
do not track changes in backup files in git
=> ignore changes in backup files

runs/mqttsub.py, runs/usmarthome/smartbase.py, web/settings/smarthomeconfig.php, web/settings/topicsToSubscribe_smarthomeconfig.js
Mit diesem Parameter wird die Möglichkeit geschaffen ab einer definierten Uhrzeit das Device auszustellen (für den laufenden Tag).Siehe auch:
https://openwb.de/forum/viewtopic.php?p=68452#p68452
=> immer aus ab

modules/wr2_solaredge/main.sh, packages/modules/sma_sunny_boy/bat.py, packages/modules/sma_sunny_boy/bat_smart_energy.py, packages/modules/sma_sunny_boy/counter.py, packages/modules/sma_sunny_boy/device.py, packages/modules/sma_sunny_boy/inverter.py, web/settings/modulconfigpv.php
- allow port selection for solaredge as PV2
- fix multiple modbus connections in sma sunny boy
=> modul fixes

runs/atreboot.sh
#2350
Prozesse, die im Hintergrund weiterlaufen, belegen nicht mehr STDOUT der `atreboot.sh`. Dadurch kann diese ordentlich beendet werden und es bleibt kein Prozess "übrig".
Weitere Fixes:
- SmartHomeMQ wurde mit ungültigem Redirect aufgerufen
- RSE wird ohne `sudo`gestartet. "pi" ist in der Gruppe "gpio" und kann daher selbst auf die GPIOs zugreifen
=> use nohup to detach from stdout

ladelog.sh, nachtladen.sh, u1p3p.sh
- configured phases to use were not honored for night and morning charging on charge point 2
- chargelog did not honor night and morning charging on charge point 2
- formatting of changed files
=> Bugfix: night charging on charge point 2

packages/modules/alpha_ess/bat.py, packages/modules/alpha_ess/counter.py, packages/modules/alpha_ess/device.py, packages/modules/alpha_ess/inverter.py, zielladen.sh
- only use a single connection for alpha ess devices
- change calculation in target charging for better accuracy
=> fix alpha ess and target charging calculation

evsedintest.sh, runs/pushButtons/pushButtonsHelper.sh, runs/rfid/rfidHelper.sh, runs/rse/rseDaemon.py, runs/rse/rseHelper.sh
- change loglevels in daemons for pushbuttons, rfid and rse
- fix wronf variable names in `evsedintest.sh`
=> silence daemons / fix evsedintest

modules/wr2_smamodbus/main.sh, packages/modules/sma_sunny_boy/device.py, web/settings/smarthome.php
- add missing defaults to wr2_smamodbus
- fix optional arguments in sma_sunny_boy/device.py read_legacy()
- add info about deprecated smart home
=> Bugfix SMA WR2

runs/cleanup.sh, runs/cleanupf.sh, web/settings/fehlerbericht.html, web/settings/senddebug.php
- added more fields to debug form to get detailed infos about used components and cars
- parse some values from openwb.conf into readable text
=> extend debug report

runs/mqttsub.py
1. Verwende Standard-Logsystem (weil so schön einheitlich dann und auch kürzer)
2. Logge jedes Mal, wenn eine Verbindung zum Broker hergestellt wurde, bzw. wenn die Verbindung nach einem Verlust der Verbindung erneut hergestellt wurde (das könnte helfen bestimmte Probleme mit dem Broker zu debuggen).
=> use python logging in MQTT client and log it when connection is established

web/themes/colors/powergraph.js, web/themes/colors/theme.html
Farbe des Hintergrunds beim Laden des Themes jetzt passend zum Farbschema
=> color theme: change bg of load screen

runs/atreboot.sh, runs/cron5min.sh, runs/services.sh
Es gibt da einige Dopplungen in der atreboot.sh und der cron5min.sh. Der PR hier soll das ganze zusammenführen um die Dopplung zu vermeiden.
=> extract starting and stopping services in atreboot.sh and cron5min.sh into a common script

modules/bezug_discovergy/main.sh
Nur eine harmlose Korrektur von Tippfehlern.
=> Fix: Tippfehler in Kommentar bei Discovergy

runs/isss.py
Es gab für den alten isss-Daemon Rückmeldungen, dass die Ladung für einen Zyklus unterbrochen wurde, obwohl Ladestrom freigegeben war. Im isss-Log tauchte die Fehlermeldung "Error reading configured current! Using default '0'." auf.
=> Fix: temporarily missing set_current file

modules/soc_eq/auth.py, modules/soc_eq/soc.py, web/settings/modulconfiglp.php
https://developer.mercedes-benz.com/content-page/migration_2022
=> Change for new Mercedes EQ Logins

modules/soc_evnotify/main.sh, modules/speicher_e3dc/main.sh, packages/modules/chargepoints/internal_openwb/socket.py
- fix evnotify
- fix openwb socket
- fix e3dc
=> Bugfix Python Module Path

web/themes/colors/powerdata.js, web/themes/colors/powergraph.js, web/themes/colors/processAllMqttMsg.js, web/themes/colors/theme.html, web/themes/colors/yieldmeter.js
- Im "Energie heute" bzw. "Energie Monat" - Graphen wird bei der Lade-Energie der Anteil angezeigt, der durch PV und durch Batteriestrom geliefert wurde.
=> Colors Theme: Show PV Charged energy 

web/themes/EvenDarker/style.css, web/themes/EvenDarker/theme.html, web/themes/Gauges/style.css, web/themes/Gauges/theme.html, web/themes/dark/style.css, web/themes/dark/theme.html, web/themes/standard/style.css
- minor layout fixes in themes "standard", "dark", "Gauges" and "EvenDarker"
- fixes #2512
=> main page fixes

packages/modules/devices/solaredge/device.py
Fix zu [https://openwb.de/forum/viewtopic.php?p=76192#p76192](https://openwb.de/forum/viewtopic.php?p=76192#p76192)
=> Fix Solaredge: charging bat from net

modules/soc_vwid/soc_vwid.py
openWB-Forum: https://openwb.de/forum/viewtopic.php?p=76165#p76165
Fehler lässt sich nicht analysieren ohne reply Datei.
Mit dem PR wird die reply-Datei in jedem fall geschrieben.
=> soc_vwid: add exception handling for missing soc field in reply

runs/atreboot.sh, web/files/boot_config.txt
- add section to update `/boot/config.txt` in `atreboot.sh`
- add gpio init to boot config template
=> init gpios in boot/config.txt

packages/modules/devices/sonnenbatterie/bat.py, packages/modules/devices/sonnenbatterie/counter.py, packages/modules/devices/sonnenbatterie/inverter.py, web/settings/modulconfigbat.php
add support for json api v2 in sonnenbatterie modules
=> add support for json api v2

web/themes/colors/powergraph.js, web/themes/colors/yieldmeter.js
- Anteil von PV und Speicher wird jetzt auch für den Hausverbrauch angezeigt
- Einheitliche Reihenfolge der Werte im Energie-Graphen
=> Colors theme: Show PV percentages for house consumption

modules/soc_kia/kiaauth.py
added AppId to device-registration
device-registration now after account data
=> [Kia/Hyundai] - Hotfix Login-Process

modules/soc_vwid/libvwid.py, modules/soc_vwid/soc_vwid.py
This PR completes https://github.com/snaptec/openWB/pull/2542
- use original libvwid.py.
- limit traffic between VW Server and openWB to SOC related data
=> soc_vwid: fix get_status problem, use original libvwid.py, reduce traffic

modules/soc_smarteq/README.txt, modules/soc_smarteq/_secrets.py, modules/soc_smarteq/main.sh, modules/soc_smarteq/soc_smarteq.py, runs/atreboot.sh, runs/updateConfig.sh, web/settings/modulconfiglp.php
Initial Version.
New python3 modules required: bs4, pkce - are added in atreboot.py
also secrets.py required, in stretch - same approach as in vwid.
Tested on buster and stretch, lp1 and lp2.
=> soc_smarteq: SOC Module for smart EQ vehicles

modules/soc_smarteq/soc_smarteq.py, web/settings/modulconfiglp.php
handle errors in more consistent way
python logging configured to use debug setting from openwb.conf
=> soc_smarteq: improve error handling and logging

modules/wr_kostalpikovar2/kostal_piko_var2.py, modules/wr_kostalpikovar2/kostal_piko_var2_test.py, modules/wr_kostalpikovar2/kostal_piko_var2_test_sample_off.html
If the inverter is offline, the actual power is printed as the string `xxx`. As the RegEx for validation did expect a number, it failed.
We consider this by not limiting the characters in the RegEx but catching an expected ValueError when converting the value into an integer.
Additionally we log the inverter state for debugging.
=> kostal-piko-var2: handle inverter state "Aus"

web/settings/pvconfig.html
=> allow up to 100% for speichersocminpv

packages/modules/chargepoints/internal_openwb/chargepoint_module.py, packages/modules/common/evse.py, packages/modules/common/store/_chargepoint.py, runs/isss.py
don't reset rfid, because it will be published only if it is changed
[https://openwb.de/forum/viewtopic.php?p=78029#p78029](https://openwb.de/forum/viewtopic.php?p=78029#p78029)
fix daemon mode: power of all chargpoints
=> fix isss rfid, daemon

modules/soc_smarteq/soc_smarteq.py
same fixes as in 2.0:
- fix comparison of old and new tokens
- store only when tokens changed
- handle missing store file at 1st run with a warning
=> soc_smarteq: fix token comparison, handle missing store file

runs/usmarthome/smartmeas.py
device_temperatur_configured wird mit 0 initialisiert....
=> Smarthome...Beta 1.9.290

web/display/minimal/index.php
fixes obsolete trim() after #2568
=> remove obsolete trim()

modules/soc_vwid/main.sh, modules/soc_vwid/soc_vwid.py
- use logging instead of log function
- show soc and ev timestamp  as info in soc.log
=> soc_vwid: use logging module, show ev timestamp in log

runs/mqttsub.py
The value of 300000 W can be exceeded in large installations.
=> Allow MQTT TotalPower up to 999999 W

packages/modules/chargepoints/internal_openwb/chargepoint_module.py, packages/modules/common/b23.py
[https://openwb.de/forum/viewtopic.php?p=78773#p78773](https://openwb.de/forum/viewtopic.php?p=78773#p78773)
=> isss: support former modbus ids

web/themes/colors/powerdata.js, web/themes/colors/powergraph.js, web/themes/colors/yieldmeter.js
Fehler in der Berechnung des PV-Anteils korrigiert.
=> Colors theme: Fix PV percentage calculation

modules/speicher_fems/fems.py
Fix Fems datapoints. Tested with Fenecon Home system.
=> fix Fenecon storage energy values

web/themes/colors/powerdata.js, web/themes/colors/smartHomeList.js
Korrektur der Anzeige von Smarthome-Temperaturen. Temperaturen über 200 Grad werden als "nicht vorhanden" interpretiert.
=> Colors theme Fix: Temperaturanzeige

packages/modules/devices/http/api.py, packages/modules/devices/http/bat.py, packages/modules/devices/http/counter.py, packages/modules/devices/http/inverter.py
fixes error in mqtt.log:
`openWB/set/evu/faultStr, Message: " () takes 0 positional arguments but 1 was given"`
=> Bugfix: http counter module

runs/isss.py
- init `old_phases_to_use = 0` to always trigger a phase switch after boot
- remove outdated `actor_cooldown_thread`
- fix spelling
=> minor isss fixes

modules/soc_vwid/libvwid.py
=> soc_vwid: fix modified urls

modules/soc_tronity/main.sh, web/settings/modulconfiglp.php
We updated the API endpoints. To the news API from the tronity platform
=> fix: update tronity api endpoints

runs/mqttsub.py
Die `mqttsub.py` und darin insbesondere die Funktion `on_message` ist extrem lang und unübersichtlich. Meine IDE kommt schon an ihre Grenzen wenn sie eine Code-Analyse macht. Und ich tue mich auch schwer...
Hier ist ein erster Schritt um die Datei besser zu strukturieren. Ich habe einigermaßen oben angefangen und den ersten Bereich der mit untergekommen ist - die Einstellungen für Smart-Home-Geräte - in eine seperate Funktion rausgezogen. Dabei habe ich:
- Code-Duplikate reduziert indem ich den immer wieder gleichen Code in Funktionen gesteckt habe
- Die Liste möglicher Konfigoptionen übersichtlicher gestaltet, durch die komprimierte Darstellung in einem `dict`.
- Das logging deutlich ausgeweitet und verbessert: Vorher wurden fehlerhafte Nachrichten in vielen Fällen komplett ohne …
=> refactor smart home device configuration MQTT-listener

modules/bezug_fems/fems.py, modules/speicher_fems/fems.py, modules/wr_fems/fems.py, packages/helpermodules/scale_metric.py
Adresses the major bugs reported for PR https://github.com/snaptec/openWB/pull/2629
Now also included code cleanup as suggested. Extended and commented a little bit.
@yankee42 I'd appreciate if you could check for the corner-cases.
=> FEMS / openEMS : Fix wrong case-senstive comparisions

modules/soc_vwid/libvwid.py, modules/soc_vwid/prepare_libvwid.sh
Use libvwid.py from skagmo 
prepare_libvwid.sh: replace f-Strings with stretch (python 3.5) compatible syntax
=> soc_vwid: sync libvwid.py from source repository

web/themes/colors/powerdata.js, web/themes/colors/style.css
- Korrektur eines Fehlers, der die permanente Anzeige von 1kw Batterieladung zur Folge hatte
- Fix der Icon-setting im Stylesheet
=> FIX for Colors theme: wrong battery preset

web/themes/colors/powermeter.js, web/themes/colors/style.css, web/themes/colors/yieldmeter.js
Korrektur der Font-Spezifikation für die Icons, damit sie korrekt angezeigt werden.
=> FIX for colors theme: ensure icons are displayed

web/display/cards/index.html, web/display/cards/style.css, web/display/colors/index.html, web/display/colors/style.css, web/display/gauges/index.php, web/display/minimal/index.php, web/display/minimal/minimal.css, web/display/parentwb/index.html, web/display/parentwb/style.css, web/display/simple/index.php
There are no consistent cli options for preventing swipe gestures in chromium. So we try to prevent the back and reload gestures by a css setting. Should be supported since chromium 63.
=> prevent display gestures

modules/wr2_shelly/main.sh, modules/wr_shelly/main.sh, packages/modules/devices/shelly/device.py, packages/modules/devices/shelly/inverter.py
- unify `main.sh` skripts
- remove duplicate code in `device.py`
- restructure method `total_power_from_shelly()` in `inverter.py`; method can be moved to `device.py` if other components are implemented
=> restructure shelly inverter module

runs/mqttsub.py, runs/services.sh
=> fix switch between parent and NurLP

modules/mpm3pmlls1/readmpm3pm.py
=> Revert "merge master into beta"

modules/mpm3pmlls1/readmpm3pm.py
=> Revert "fix Duo"

modules/mpm3pmll/main.sh, modules/mpm3pmll/readmpm3pm.py, modules/mpm3pmlllp1/main.sh, modules/mpm3pmlllp1/readmpm3pm.py, modules/mpm3pmlllp2/main.sh, modules/mpm3pmlllp2/readmpm3pm.py, modules/mpm3pmlllp3/main.sh, modules/mpm3pmlllp3/readmpm3pm.py, modules/mpm3pmlllp4/main.sh, modules/mpm3pmlllp4/readmpm3pm.py, modules/mpm3pmlllp5/main.sh, modules/mpm3pmlllp5/readmpm3pm.py, modules/mpm3pmlllp6/main.sh, modules/mpm3pmlllp6/readmpm3pm.py, modules/mpm3pmlllp7/main.sh, modules/mpm3pmlllp7/readmpm3pm.py, modules/mpm3pmlllp8/main.sh, modules/mpm3pmlllp8/readmpm3pm.py, modules/mpm3pmlls1/main.sh, modules/mpm3pmlls1/readmpm3pm.py, modules/mpm3pmlls2/main.sh, modules/mpm3pmlls2/readmpm3pm.py, modules/mpm3pmtripple/readmpm3pm.py
=> Revert "Fix legacy charge point access"

modules/mpm3pmll/readmpm3pm.py, runs/readmodbus.py
revert changes in `modules/mpm3pmll/readmpm3pm.py`and `runs/readmodbus.py`
https://www.openwb.de/forum/viewtopic.php?p=84605#p84605
=> remove modbus port detection

modules/mpm3pmll/main.sh, modules/mpm3pmll/readall.py
https://www.openwb.de/forum/viewtopic.php?p=84763#p84763
https://www.openwb.de/forum/viewtopic.php?p=84729#p84729
=> use python 2 for mpm3pmll module

packages/modules/smarthome/askoheat/off.py, packages/modules/smarthome/askoheat/on.py, packages/modules/smarthome/askoheat/smartaskoheat.py, packages/modules/smarthome/askoheat/watt.py, packages/smarthome/smartcommon.py, runs/mqttsub.py, web/settings/smarthomeconfig.php
Erstmalige Unterstützung Askoheat+, Analog Acthor und Elwa überschussgesteuert. Gui für Openwb 2.0 kommt als separater PR
=> Smarthome askoheat

modules/bezug_sungrow/main.sh, modules/speicher_sungrow/main.sh, packages/modules/devices/good_we/device.py, packages/modules/devices/sungrow/config.py, packages/modules/devices/sungrow/counter.py, packages/modules/devices/sungrow/device.py, web/settings/modulconfigbat.php, web/settings/modulconfigevu.php, web/settings/modulconfigpv.php
Bitte PR übernehmen
Fehler in den Bash Befehlen gefunden und weitere Feinheiten optimiert.
=> Sungrow Bash fixes (nightly) + style improvment 

packages/modules/devices/sma_sunny_boy/inv_version.py, packages/modules/devices/sma_sunny_boy/inverter.py, web/settings/modulconfigpv.php
Added a new version in PV-Module: SMA Cluster Controller/Data Manager.
This commit has been tested in live use.
=> Added new version in PV Module: SMA Cluster Controller/Data Manager

packages/modules/common/evse.py, packages/modules/internal_chargepoint_handler/chargepoint_module.py, packages/modules/internal_chargepoint_handler/clients.py, packages/modules/internal_chargepoint_handler/socket.py, runs/isss.py
=> hardware check, duo with two busses

runs/atreboot.sh
- add missing "-y" and "-qq" options to some calls
=> fix apt package installation

modules/bezug_rct2/main.sh, packages/modules/internal_chargepoint_handler/chargepoint_module.py, packages/modules/internal_chargepoint_handler/socket.py, runs/isss.py, runs/update.sh
=> fix bezug_rct2

packages/modules/devices/rct/rct_lib.py
- fix logging in `RCT.connect_to_server()`
- remove obsolete code
- fix typos and format
=> Bugfix RCTv2

web/logging/chargelog/ladelogexport.php
use first day to get month name and avoid duplicates
=> fix month name generation

packages/smarthome/smartbase.py, packages/smarthome/smartcommon.py, runs/smarthomemq.py
PV Leistung und chargestatus für openwb. Für 1.9 und 2.0 übernehmen,
=> pv Leistung und chargestatus

loadvars.sh
=> remove obsolet simcount modules from loadvars

web/display/minimal/index.php, web/display/minimal/setupMqttServices.js, web/status/processAllMqttMsg.js, web/status/status.php
- only subscribe topics for second charge point if configured
- filter second charge point connection module for local connections
- only display monthly and yearly total inverter yields if greater than zero (actually only valid for Plenticore module)
=> minor layout fixes

packages/modules/devices/batterx/external_inverter.py
=> BatterX: fix entity of external inverter

packages/modules/devices/varta/counter.py
[https://openwb.de/forum/viewtopic.php?p=91345#p91345](https://openwb.de/forum/viewtopic.php?p=91345#p91345)
=> Varta: invalid register

packages/modules/devices/solar_watt/device.py
=> fix solarwatt

packages/modules/smarthome/nxdacxx/watt.py
Übertragener modbuswert wird auch protokolliert...
=> Smarthome dac type = 3

packages/modules/devices/rct/bat.py, packages/modules/devices/rct/counter.py, packages/modules/devices/rct/rct_lib.py
=> RCT backport

web/settings/mqttapi.php, web/settings/saveconfig.php
=> fix command injection

packages/modules/common/b23.py
fix B23 registers, backport from https://github.com/openWB/core/pull/1420
=> B23 registers

modules/soc_smarteq/soc_smarteq_2fa.py
smart eq soc module: 2FA: change on server requires modifications:
- update versions
- request_pin requires now a get config
=> 2FA: update versions,  pre request_pin: add config get

modules/soc_i3/main.sh
Noch eine kleine Änderung; die env variablen wurden wegen sudo nicht in das python geliefert.
=> soc BMW: fix env issue in main.sh

.github/workflows/github-actions-python.yml
wie hier beschrieben https://github.com/actions/setup-python/issues/866
=> Fix pip SSL-error in github action

modules/soc_i3/main.sh
=> soc_i3: fix syntax

modules/soc_i3/i3soc.py
session_id was not initialized when earlier login failed.
please merge asap
=> soc_i3: fix issue with uninitialized session_id

modules/soc_i3/i3soc.py
Der PR wäre dringend, es gibt Anwender die darauf warten.
=> soc BMW&Mini: fix error handling when refreshToken fails
