- modules/soc_i3s1/main.sh
Auch an LP2 wird damit das Updateintervall während des Ladens entsprechend der Einstellung für LP1 verkürzt.
> Änderungen bzgl. Updateintervall auch für soc_i3s1 übernommen.

- nurpv.sh
Hi, 
ich habe einen kleinen Bug behoben. 
Wenn man "nur PV" lädt, aber kein SOC Modul konfiguriert hat und die Default Werte für Min/Max SOC lässt (45%/95%), funktioniert das PV laden nicht, da immer mit minimaler Stromstärke geladen wird. 
Der Fix überprüft daher, ob ein SOC Modul spezifiziert ist und überspringt den Teil, wenn nicht.
***
I fixed a small bug when charging PV only without an SOC module specified. In certain conditions openWB charged always with minimum current instead of regulating PV usage...
> fix nurpv when no soc module active

- runs/ladetaster.py
Ein weiterer Taster für den Modus Standby kann damit zwischen Ground und GPIO 21, PIN 40 angeschlossen werden.
> Ladetaster.py um Taster für Standby erweitert

- modules/bezug_smartme/main.sh
Liefern ActivePowerL1 oder CurrentL1 keine Werte wird auf ActivePower und Current zurückgegriffen.
> Smart-me Kompatibilität zu 1 Phasen Zähler wieder hergestellt

- web/index.php
Lehrzeichen für die Anzeige der geglätteten Leistung eingefügt.
In dem folgenden Codeschnippsel aus der der loadvars.sh wird in die Datei ramdisk/glattwattbezug noch ein Linefeed geschrieben. Der müsste, der Optik wegen, eigentlich raus. Übersteigt aber meine Fähigkeiten :-/. Wenn das geht, könnte das eingefügte Leerzeichen nach der öffnenden Klammer wieder entfallen.
#evu glaettung
if (( evuglaettungakt == 1 )); then
ganzahl=$(( evuglaettung / 10 ))
for ((i=ganzahl;i>=1;i--)); do
i2=$(( i + 1 ))	
cp ramdisk/glaettung$i ramdisk/glaettung$i2
done
echo $wattbezug > ramdisk/glaettung1
for ((i=1;i<=ganzahl;i++)); do
glaettung=$(<ramdisk/glaettung$i)
glaettungw=$(( glaettung + glaettungw))
done
glaettungfinal=$((glaettungw / ganzahl))
echo $glaettungfinal > ramdisk/glattwattbezug …
> Schönheitskorrektur Anzeige Bezug/Einspeisung auf Hauptseite

- modules/soc_i3/main.sh
Bei Ladeabbruch, auch bei Ladungen nicht an openWB, wird eine Pushover Benachrichtigung geschickt.
> Modul soc_i3 - Benachrichtigung bei Ladeabbruch

- modules/soc_i3s1/main.sh
Bei Ladeabbruch, auch wenn nicht an openWB geladen wird, wird eine Pushover Benachrichtigung generiert.
> Modul soc_i3s1  - Benachrichtigung bei Ladeabbruch

- web/modulconfig.php
Hi @snaptec ,
I noticed that in web/modulconfig.php there is a lot of code duplication. To make it a bit more understandable and maintainable I took the freedom of reducing that duplication. 
Now in each block handling the visuals is structured like this:
- function to encapsulate the visuals handling (`display_*`)
- first hide all elements
- then walk through the options and display elements accordingly
- anonymous function calls `display_*`
- when entering
- when change is triggered
Adding more elements should now be much easier:
- add element once in the "hide" list
- add if statement to display when needed
I hope you find this simplification helpful and will accept it in the code. 
However I recommend testing it before integrating (I still might have overlooked some typos or …
> simplify options handling in modulconfig.php

- web/modulconfig.php
Reverts snaptec/openWB#210
Not working,
if activating anything, no div is shown.
f.e. activating LP2 does not show the divs for it.
if a div, f.e. LL lp1 is activated, all divs for all components are shown.
Safari 12.1.1 under OS X
> Revert "simplify options handling in modulconfig.php"

- loadvars.sh
Der Fix verhindert die Pushbenachrichtigung beim Einstecken, wenn sofort geladen wird.
> Update loadvars.sh (Fix PushPlug)

- web/setGaugeScaleCookie.php
- web/setThemeCookie.php
- web/themes/dark_gauges_1/index.html
- web/themes/dark_gauges_1/updateGauges.js
Kleine Bugfixes. Erste Werte werden jetzt umgehend nach Page-Load angezeigt. Zudem: Gauges für PV, Batt und EVU passen die Skala nicht mehr automatisch nach unten an. Maximalwerte der jeweiligen Skalen werden als Cookies gespeichert, bei neuen Maximalwerten angepasst und bei Page-Reload geladen. Änderung erfolgt, weil man so optisch besser zwischen "viel" und "wenig" unterscheiden kann, was nicht geht, wenn die Skala auch automatisch nach unten korrigiert wird und dabei ein Zeiger auf "Anschlag rechts" innerhalb einer Gauge mal 1kW und mal 8kW entspricht. Skala der Gauge für Hausverbrauch passt sich weiterhin auch nach unten an, aber langsamer. Dies deswegen, um Ausreißer durch Berechnungsfehler auszugleichen.
> Anpassung Theme Dark_Gauges_1

- loadvars.sh
It seems the bulk publish is missing for `global/ChargeMode` and the `mosquitto_pub` command line is missing the `-r` flag. Hence ChargeMode is not retained by MQTT Broker.
The PR includes  `global/ChargeMode` in bulk publish which is using retention anyway.
Fix for observation reported in [this](https://openwb.de/forum/viewtopic.php?f=6&t=577&start=50#p4495) forum post.
> Bugfix: Bulk publish (and hence retain) also for ChargeMode

- loadvars.sh
- regel.sh
- runs/atreboot.sh
Hallo und erst einmal Vielen Dank an alle Aktiven für die Arbeit an der openWB Hard- und Software !  
**Ich hätte eine kleine Ergänzung anzubieten die das Display der openWB series2 beim Anstecken eines Fahrzeugs für die unter "Einstellungen -> Misc" eingestellte Zeit aktiviert.  
Die Funktion wird über das Config-Setting `displayEinBeimAnstecken` aktiviert. Der Default (in `atreboot.sh`) wäre `ein`.**
Weder im Forum noch per Google-Suche noch per Reverse-Engineering habe ich eine entsprechende Funktion gefunden. Ich finde das aber sehr praktisch da ich nach dem Anstecken des Autos sowieso an der Box vorbei gehe und mir so ganz einfach, ohne Antippen des Displays, einen Überblick über den Stand der Anlage verschaffen kann.
Da ich aber neu bin in openWB (hab das E-Auto noch nicht lange) …
> Beim Anstecken eines Fahrzeugs das Display einschalten

- web/misc.php
- web/tools/savemisc.php
After I've learned some minimal web development for the MQTT feature, I've now added the setting for the recently merged PR #253 to the "Misc" tab (Display section).
The should allow all users to enable the "Display on when plugged in" feature.
> Allow UI configuration of display-on on plugin

- runs/mqttpub.py
As part of [this forum discussion](https://openwb.de/forum/viewtopic.php?f=9&t=637&start=20) it was hard for me to identify whether the `mqttpub.py` script is actually submitting data.  
After some investigation it turned out that the script's connection look like
```
1575996586: New client connected from ::1 as 7c2933e8-b437-4385-9f53-20a82c1bf156 (c1, k60).
```
which is kind-of odd (nothing in this line points to the python script).
But paho-mqtt has the possibility to set the client name.
With this very simple PR I've used that possibility to send a client name made of the constant prefix
'openWB-python-bulkpublisher-' concatenated with the current process id. An approach pretty similar to what 'mosquitto_pub' seems to be doing.
On Mosquitto `mqttpub.py` connections will then look like …
> Giving client name to MQTT bulk publisher

- web/tools/savemqtt.php
I had to notice that I missed out the openwb/system topics in bridge config.  
Hence timestamps are currently not available on remote MQTT server, making it impossible to track how up-to-date the retrieved data is.
To apply the change on an already configured bridge, after updating openWB, simply re-save the unmodified settings in "Settings -> MQTT" tab.
Additionally a wrong (left-over) comment for the set topic bridge setting has been removed.
> Adding openwb/system topic to bridge

- modules/wr_fronius/main.sh
Ein paar Änderungen am Skript für die Abfrage der PV-Leistung und des PV-Energiezählers.
**Bugfix:**
In "if [[ wrfronius2ip != "none" ]]; then" fehlte ein "$" vor "wrfronius2ip", was dazu geführt hat, dass immer der Zweig ausgeführt wurde, der eigentlich für das Vorhandensein von 2 Fronius Wechselrichtern gedacht war.
**Vereinfachung:**
Bei Fronius Wechselrichtern mit neuerer Firmware dauert die FastCGI-Abfrage von "$wrfroniusip/solar_api/v1/GetPowerFlowRealtimeData.fcgi?Scope?System" im Schnitt ca. 0.2 Sekunden, während die CGI-Abfrage von "$wrfroniusip/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System" zwischen 1-2 Sekunden (manchmal noch länger) dauert.
Letztere ist aber (zumindest in meiner Konfiuguration mit einem Wechselrichter) gar nicht nötig, da die Gesamt-PV-Energie auch in …
> Bugfix, cleanup and simplification.

- web/themes/standard/index.html
Ich wollte eigentlich nur die fehlenden Leerzeichen zwischen den Werten und der zugehörigen Einheit korrigieren und war etwas erschlagen von den vielen Ergebnissen in meiner Suche nach "A Soll" im Repository.
Wenn ich das überall korrigieren möchte, muss ich offenbar die folgenden Dateien anfassen:
- web/simplemode.html
- web/themes/standard/index.html
- web/display/index.html
- web/display/standard.html
- web/themes/dark19_01/index.html
- web/themes/dark_gauges_1/index.html
Sehe ich das richtig? Oder werden die Dateien automatisch erzeugt und es gibt irgendwo eine Art "Template"?
Ich habe es jetzt erst mal nur in "web/themes/standard/index.html" angepasst, weil es so in meiner meistgenutzten Ansicht korrekt angezeigt wird...
> Fixed some missing spaces between value and unit in the standard theme.

- web/tools/savemqtt.php
Based on [this forum entry](https://openwb.de/forum/viewtopic.php?f=9&t=673&p=5243#p5234).
The "delete" control path was missing call to `checkmqttconf.sh` and UI refresh similar to the "add/modify" control-path.
Missing steps have been added and both calls to `checkmqttconf.sh` is now backgrounded so UI refreshes immediately.
> Fix for MQTT bridge deletion

- modules/wr_fronius/main.sh
Even with "?" it was working as the parser in the frequency inverter seems to be tolerant here, but the correct request is with "=".
> Scope request fix in wr_fronius

- modules/bezug_fronius_sm/main.sh
Even with "?" it was working as the parser in the frequency inverter seems to be tolerant here, but the correct request is with "=".
Sorry for creating two pull requests regarding this "problem", but I have done it directly on GitHub via the edit-function in the browser.
> Scope request fix in bezug_fronius_sm

- loadvars.sh
Only for modbusevse (similar to LP1)
Also corrected indentation in previous implementation for LP1.
Couldn't test it due to lack of openWB Duo here.  
But at least verified to not break anything for openWB "single".
> Support display-on-when-plugged-in for LP2

- loadvars.sh
- runs/atreboot.sh
I have a very specific use-case for which it is very helpful to get the RFID tag ID via MQTT together with the (approximate +- control interval) timestamp when that ID has been scanned. The timestamp is exactly the same as reported via `openWB/system/Timestamp`.
I'd therefore highly appreciate if this PR could be accepted.
Topics added are:
```
openWB/lp/1/lastRfId=${arfidlp1},${timestamp}
openWB/lp/2/lastRfId=${arfidlp2},${timestamp}
openWB/system/lastRfId=${arfidlast},${timestamp}
```
`atreboot.sh` has been extended to add to the ramdisk the "mqttrfid*" topics matching the "rfid*" topics.
Anything else I need to add?
> Send RFID tag ID via MQTT

- runs/mqttsub.py
**As mentioned in [this forum post](https://openwb.de/forum/viewtopic.php?f=4&t=833#p6866) I think it would be beneficial to subscribe the MQTT set topics with QoS 2 (ExactlyOnce) and always the same client ID.**   
This will allow the MQTT server to do its best to provide all latest values to openWB even though server or client got restarted and/or connections (re-)established.
The correponding changes required are included in this PR.
**To be safe and prepared for any kinds of setups where multiple openWB might subscribe to a single MQTT server (even though such setups do not exist atm) the RASPI CPU serial number is included with the client ID.**  
This will result in always the same ID while ensuring that subscriptions of multiple, different, openWBs to the same MQTT server could be …
> Subscribe to MQTT set topics with QoS 2 and always the same client ID

- modules/bezug_ksem/main.sh
- modules/bezug_ksem/readksem.py
- runs/atreboot.sh
- web/settings/modulconfig.php
- web/tools/savemodul.php
Support für den Kostal Smart Energy Meter respektive TQ EM410. Zur Zeit wird der KSEM nur zusammen mit Kostal Plenticore und Piko IQ unterstützt. Zusammen mit dem Piko (ohne IQ) wird dieser nicht unterstützt. Da die Daten nicht an den Wechselrichter gesendet werden, können die Informationen auch nicht vom WR ausgelesen werden.
Diese Implementation unterstützt das direkte auslesen der KSEM über Modbus TCP. Vermutlich wird auch der TQ EM300 unterstützt.
> Kostal smart energy meter Bezugsmodul

- web/themes/dark19_01/processAllMqttMsg.js
- web/themes/dark19_01/theme.php
Dark-Theme: Anzeige "Gesamt-Ladeleistung" verschoben vom Block "LP-Anzeige" in den oberen Block der aktuellen Werte. Erscheint entweder anstelle der Zeile Hausverbrauch (wenn diese ausgeschaltet) oder daneben.
> Ladeleistung-Anzeige verschoben

- web/settings/settings.php
Extended list of Schieflast values down to 10A.
This makes sense if the car only supports charging with 2 Phases. e.g. VW e-golf. In this case one may want to switch from 1 to 3 phase at a lower current than 16A. E.g. After 1 Phase 11A it shall change to 2 Phase 6A instead of going to 1 Phase 12A.
> Allow lower Schieflast values

- web/live.js
- web/logging/dailychart.js
- web/logging/monthlychart.js
- web/settings/setupMqttServices.js
- web/themes/dark19_01/setupMqttServices.js
- web/themes/dark_gauges/processAllMqttMsg.js
- web/themes/standard/processAllMqttMsg.js
Da es nicht gewünscht zu sein scheint, den Benutzern generell anzubieten ihre openWB über die Einstellungen einfach sicherer zu betreiben, habe ich dies nun darauf reduziert dass es durch die Implementierung von openWB nicht mehr verunmöglicht wird dies wenigstens selber so einzurichten zu können.
Die Änderung benutzt anhängig vom HTTP/HTTPS Protokoll das richtige WebSocket Protokoll ws/wss.
> Allow running openwb an a webserver accessed by https

- rfidtag.sh
- slavemode.sh
* Bugfix: Don't enable CP if in Slave mode and EV is already plugged as that constellation could not be handled properly for accounting: It would be unclear which CP the tag is for if another CP of the same box is also "plugged-in".
* Improvement: Avoid `rfidtag.sh: Zeile 29: [: 0002392926: Einstelliger (unärer) Operator erwartet.` message on empty tag by using string comparison.
* Improvement: Avoid `Slave Mode INTERNAL ERROR: chargingVehiclesAdjustedForThisCp == 0 - skipping slave loop for CP#1 - is your CONTROLLER USING A TOO HIGH LIMIT FOR DETECTING CHARGING PHASES ??` error message in transient situations when master has not yet detected us as charging but we have already detected ourself as charging and at same time no other car is charging
* Improvement: Made some more bash …
> rfidtag.sh bugfix and slavemode improvement

- runs/mqttsub.py
- slavemode.sh
At least with MPM3PM meter which only delivers Amps with 2 decimal digits it
seems that the heartbeat falsely triggers far too often.
With this commit, the LastControllerPublish MQTT message is the preferred
heartbeat value while current on phase with maximum current (the previous
implementation) is now the fallback in case LastControllerPublish message is
not published by master at all.
> Optional master heartbeat via LastControllerPublish

- rfidtag.sh
Setting lp?enabled right away in `rfidtag.sh`.
As that script is now called very early from `loadvars.sh` it makes sense
to modify the global vars so they become effective in the same control loop.
Additionally fixed issue when, for example, EVSE readout failed and plugstat or chargestat are not available. In this case we used to send garbage (e.g. `1586549462,0001234567,7.628,1586583932,,,7.943`) for accounting.
Now this case is being detected and the data will be ignored and not accounting data update will be sent in that loop at all.
Charge start data is now written to a persistent location instead of ramdisk to survive power outages.
RFID tag of "AllowedRfidsForLpX" now written to files for ladelog.
> Improve RFID responsiveness and fix glitches and persistent start data storage

- rfidtag.sh
- runs/atreboot.sh
- slavemode.sh
With this commit the slave mode respects the phase(s) on which the last chargings have occurred instead of blindly checking all 3 phases.
The behaviour can be disabled in `openwb.conf` using `slaveModeUseLastChargingPhase=0`. That should be done if user is known to run different EV on the same charge point.  
If always the same EV is connected it's preferable to use the smart default `slaveModeUseLastChargingPhase=1`.
> Optionally use last known charging phase for slave mode load mangement

- runs/mqttsub.py
- slavemode.sh
This MR enables steering of slave mode according to EVU total power limit in addition to per-phase-current.
Two more values are required from master. If provided, the slavemode will now respect it and adjust the allowed charge current accordingly.
> Slave mode steering according to EVU power limit (if specified)

- rfidtag.sh
- slavemode.sh
Previously it was required to scan RFID tag at least one control interval _prior_ to EV plugin.
Now both can happen in same interval (see line 226).
Also included little Bugfix for slave mode which counted number of charging phases improperly (and hence always assumed 3 phases charging).
> Allow RFID scan and plugin in same control interval

- runs/atreboot.sh
- runs/mqttsub.py
- slavemode.sh
**In order to avoid osciallation and accomodate for EVs not immediately following allowed current within the first 10 seconds:**
1. a "slow mode" has been introduced which adjusts charge current by +1, -1 or -3 A steps (instead of the full computed difference to the possible value)
This allows more smooth control of charge current but might cause slightyl longer time in which total system allowed current is exceeded (even though -3 A steps will be done if difference is < -3 A).
Usage of this mode depends on the typical consumption of the overall system.
2. a "minimum adjustment interval" is checked: After every actual adjustment of charge current, no further adjustments will be done for at least this amount of time.
This will allow the values to settle and get updated consistently and …
> Slave slow ramping & min adjustment interval

- web/api.php
- web/tools/dailychargelp1.php
- web/tools/dailychargelp2.php
- web/tools/dailychargelp3.php
- web/tools/dailychargelpg.php
- web/tools/debugmode.php
- web/tools/getsofortll.php
- web/tools/lademodus.php
- web/tools/programmloggerinfo.php
The correct Media Types / MIME type for json is `application/json` (https://www.iana.org/assignments/media-types/application/json and https://www.ietf.org/rfc/rfc4627.txt).
This enables xml like formatting with either https://developer.mozilla.org/en-US/docs/Tools/JSON_viewer or https://addons.mozilla.org/en-US/firefox/addon/jsonview/.
> change json content-type to application/json

- ladelog.sh
- loadvars.sh
- rfidtag.sh
Scanned RFID tags won't be re-transmitted via MQTT if tag ID doesn't change.
Sometimes the point of time of the last scan is relevant even if tag ID didn't change.
This PR fixes the behaviour.
> Fix: Transmit RFID tag with time of actual last scan

- web/settings/settings_style.css
Auf aktuellen Geräten (Android, Mac, Win10) kann zwischen einem dunklen und hellen Design gewählt werden. Als Vorschlag habe ich das CSS für die neuen Einstellungen entsprechend erweitert. Da ein @media Query genutzt wird, hat es ansonsten keinen Einfluss auf die Darstellung.
> initial support for dark-mode in settings

- slavemode.sh
In slave mode we need to use the highest number of charging
vehicles across all phases on which we're currently charging.
Up to now, incorrectly, the number of vehicles on the phase with
highest charge current has been used. But that's not necessarily the phase
that is shared with the highest number of vehicles.
Second change affects the case where EV doesn't consume the allowed current which would result in too large values for current to set which could even exceed total allowed current.  
In this case it used to be limited to AllowedTotalCurrent / NumberOfChargingVehicles. But the better behaviour seems to be, to simply not change and keep the current that has last been calculated without exceeding allowed current.
Annotation to viewing the diff: Many lines just changed the casing of …
> Bugfix: Wrong number of charging vehicles

- web/themes/dark/processAllMqttMsg.js
- web/themes/dark/style.css
- web/themes/dark/theme.html
Das Laden des Theme-CSS mittels .append erfolgt je nach Browser asynchron, so dass das css des Preloaders noch nicht geladen ist, während er schon angezeigt wird. Style des Preloaders fest hinzugefügt: verhindert Flickern beim Laden.
> Flicker-Fix

- runs/mqttsub.py
Accept `yc/` release trains in `mqttsub.py`.
> Make yc/ release trains really work

- rfidtag.sh
- runs/mqttsub.py
- slavemode.sh
**Includes the following changes:**
* **Bugfix:** for handling CP2 of openWB Duo in Slave mode.
* **New feature:** Allow load imbalance limit in slave mode.
**Details:**
Default imbalance limit is set to 20 A.
Can be adjusted via the optional MQTT topic `SlaveModeAllowedLoadImbalance`.
To disable load imbalance limit, set the MQTT value of `SlaveModeAllowedLoadImbalance` >= the value of topic `AllowedTotalCurrentPerPhase`
Minor debug printout correction in `rfidtag.sh` included.
> Handling of load imbalance and Duo in slave mode

- web/settings/modulconfig.php
Bei der Anbindung von SolarView ist aufgefallen, dass die Beschreibung der Weboberfläche noch etwas missverständlich formuliert ist. Eine Stolperfalle ist, dass der angebundene TCP-Server Default-mäßig auf Port 15000 läuft, die openwb-Doku aber Port 80 als Beispiel angibt. In diesem Pull Request wird die Doku deshalb präzisiert.
Gibt es die Möglichkeit darauf hinzuweisen, dass der TCP-Server in SolarView eingeschaltet werden muss?
> docs: improve docs for configuration of SolarView

- runs/atreboot.sh
This problem could only be detected after previous MR had been included:
The `loadvars.sh` approach seems not to work reliably for `updateInProgress`.
Fixed by additionally explicitly publishing at end of `atreboot.sh`.
> Bugfix MQTT updateInProgress

- hook.sh
- modules/verbraucher/abb-b23remote.py
- web/settings/smarthome.php
Initiales Python Skript für die Kommunikation mit ABB-B23 Zählern. Beim Anschluss bitte aufpassen, A und B sind ggü. der Beschriftung am Zähler sowie Anleitung vertauscht. Meine Zähler funktionieren nur, wenn ich A am Zähler an B eines anderen Geräts anschließe (und B an A). Dies ist analog zur Anleitung von LG für den Anschluss an den LG PCS, auch hier wird der Anschluss derart empfohlen.
Das ganze ist getestet und funktioniert auf bei mir mit 3 ABB Zählern und einem USR einwandfrei.
> Support for ABB-B23 Verbraucher

- modules/bezug_fronius_sm/main.sh
- runs/atreboot.sh
- web/settings/modulconfig.php
- web/tools/savemodul.php
Seit Wochen passe ich nach jedem Update das Modul von Hand wieder an. Es wird also Zeit das ganze mal vernünftig einzupflegen:
Die aktuellen Fronius SmartMeter kommen ab Werk mit der Modbus Adresse 1 und werden auch über die DeviceID=1 in der JSON API angesprochen. OpenWB fragt derzeit allerdings immer DeviceID=0 als Smartmeter ab, vermutlich aus historischen Gründen. Hier antwortet mir der WR allerdings nur, dass es kein SmartMeter mit ID=0 gibt.
(Auszug aus der Anleitung des aktuellen Fronius 63A SmartMeters)
Nur in dieser Konfiguration funktioniert OpenWB bei mir ordentlich (neuste Software auf dem Fronius). Die bisherigen Programmierungen im Modul sind sicherlich nicht ohne Grund gemacht worden, daher habe ich einen Schalter hinzugefügt, der bei Bedarf die ID von 0 auf 1 schaltet. …
> Fronius SM - Support for Meter with ID=1

- modules/soc_tesla/main.sh
Now the tesla api is only called, if we read the SoC.
This will prevent a locked account within a minute if a wrong password was set.
> [soc-tesla] fix: reduce calls to api

- modules/soc_tesla/main.sh
Enables logging to ramdisk and limits size of logfile to 500 lines.
User is noticed if auth with tesla api failed.
fix: show number for chargepoint 1 in logfile
> [soc-tesla] enable logging

- runs/atreboot.sh
I think that's the way to prevent `atreboot.sh` launching a more and more readrfid.py for every update.
Otherwise, please comment back.
> Kill old readrfid.py before launching a new one

- loadvars.sh
Value is hard-coded to 1 as LP1 always exists.
But if omitted entirely, different (and hence special) handling on MQTT subscriber side would be needed for LP 1.
> Send boolChargePointConfigured also for LP1 (hard-coded to 1)

- web/themes/Gauges/theme.html
Doppelklick auf die Gauge PV bzw. EVU setzt die automatisch erhöhten Maximalwerte wieder zurück (auch Mobilgeräte).
> Reset Gauge Limits per Doppelklick

- web/settings/settings.beta.php
Die Einträge sind vom Testen mit in den letzten PR gerutscht. Der PR deaktiviert den Speichern-Button und setzt die richtige Form Action.
> fix form action in beta settings

- web/settings/misc.beta.php
- web/settings/pvconfig.beta.html
- web/settings/settings.beta.php
Einige Labels wurden umgebrochen, da die Breite falsch angegeben war. Jetzt wird die komplette Zeile genutzt.
> fix layout on small devices

- web/settings/cloudconfig.php
- web/settings/debugging.php
- web/settings/fehlerbericht.php
Aktionen, die eine Einwilligung in die Datenschutzerklärung benötigen, sind deaktiviert, falls die Einwilligung nicht gegeben wurde. Eine Warnmeldung erklärt, warum die Buttons deaktiviert sind und verlinkt auf die Datenschutzerklärung, um nachträglich einzuwilligen.
> disable buttons if data usage is declined

- regel.sh
Very small change as I had cases where a timestamp on "CP Unterbrechung" would have been very helpful.
> Add timestamp to "CP Unterbrechung" printouts

- modules/smart_elwa/off.py
- modules/smart_elwa/on.py
- modules/smart_elwa/watt.py
- runs/smarthomehandler.py
a) smarthomehandler.py mit python Anschluss für die Geräteansteuerung erweitert
b) Smarthome.ini
Ein pyt Gerät unterscheidet sich nur durch den Typ «pyt» von tasmota
**Hier muss noch das GUI angepasst werden**
c) Aufruf aus smarthomehandler.py
1) Gerät anschalten bei erkanntem Überschuss (Regelung wie tasmota)
Aufruf von:
/var/www/html/openWB/modules/smart_ (Name des Geräts in Lowercase) /on.py
Wenn die Datei nicht da ist, passiert nichts
2)	Gerät ausschalten bei zu wenig Überschuss (Regelung wie tasmota)
/var/www/html/openWB/modules/smart_ (Name des Geräts in Lowercase) /watt.py
Wenn die Datei nicht da ist, passiert nichts
3)	Gerät periodisch abfragen (Regelung wie tasmota)
/var/www/html/openWB/modules/smart_ (Name des Geräts in Lowercase) /watt.py
Wenn die Datei nicht da ist, passiert …
> ELWA Heizstabunterstützung durch Smarthome

- web/settings/sofortconfig.php
Bei den Ladepunkten 3-8 wurde auch ein SoC-Limit angeboten. Zumindest bei mir funktionierte das Speichern der Einstellungen nicht. Ich wurde nicht zur Hauptseite weitergeleitet. Mit den Änderungen passt es wieder.
> fix sofortconfig for chargepoints 3-8

- loadvars.sh
- regel.sh
- runs/cronnightly.sh
In order to avoid that multiple, time-synced openWBs execute their control loop in almost the same millisecond, this PR introduces a random sleep in range 0.0 - 8.9 seconds before the control loop.
Hence the loop doesn't run a 0, 10, 20, 30, 40 and 50 seconds but 0+random, 10+random, ...
The random value is re-computed once every night such that no openWB will have continuous disadvantages over other boxes e.g. because it's always "the last" one.
Randomness is disabled if not in slave mode or by writing `0` into `ramdisk/randomSleepValue`. In that case even the re-randomize at night will be skipped. The default, however, is to randomize.
Also fixes a little copy-and-paste bug causing `openWB/system/updateInProgress` being sent in each and every loop.
I'm filing this as a draft for …
> Perform random sleep before loop

- modules/smart_elwa/watt.py
- runs/smarthomehandler.py
Wenn "Auschalten beim Laden " im smarthomedevice gesetzt ist, werden smarthomedevices beim Starten vom Ladevorgang ausgeschaltet respektive nicht eingeschaltet. Funktioniert bei min+pv. für nur pv muss noch nurpv.sh angepasst werden. Die aktuelle Leistungsaufnahme der aktuellen Devices die (jetzt) abgeschaltet werden können werden in /ramdisk/devicetotal_watt geschrieben. (Mindeseinschaltdauer wird berücksichtigt)
Elwa Einrückung korrigiert
> Smarthome ausschalten beim Laden

- runs/cleanup.sh
- runs/cleanupf.sh
- runs/cron5min.sh
Neu werden alle *.Log Dateien auf der Ramdisk  gleichartig durch cron5min bearbeited (tail 1000) . openWB.Log ist ausgenommen, da nur link auf der Ramdisk.
Cleanup.sh sind Suchparameter. Cleanupsf.sh ist das Tailkommando welches für jede Datei durchlaufen wird,
Ebenso wird der Output vom Smarthomehandler.py neu in eine separates *.log geschrieben
> Generelle Bearbeitung .log Dateien durch cron5min.sh

- web/settings/modulconfiglp.php
Typo im Ladeleistungsmodul beseitigt. Wert wurde dadurch nicht in der openwb.conf gespeichert.
> fix modulconfiglp lp3 ll

- web/themes/Gauges/settings.css
- web/themes/dark/settings.css
fix white text on light background in dark themes
> wizzard fix: dark themes

- runs/atreboot.sh
Currently `openWB.log` is filling up with lines
```
loadvars.sh: Zeile 1386: ramdisk/mqttpvvorhanden: Datei oder Verzeichnis nicht gefunden
```
for every single control loop (i.e. one line every 10s).
As that will not really help extending sd-card life this PR will create the missing file with a value of 0 in `atreboot.sh`.
Please double-check if 0 is a reasonable default and correct if necessary.
> Create ramdisk/mqttpvvorhanden at reboot

- web/display2/display.html
Wenn ein Name für den ersten Ladepunkt gesetzt ist, wurde der falsche DIV-Tag aktualisiert.
> fix: typo bei Ladepunkt 1

- runs/update.sh
Update.sh tries to publish to configured extopenwb even if the chargepoint is currently disabled. As a result the update takes very long time because we have to wait for a timeout several times.
So we only publish if the chargepoint is actually enabled.
> fix: do not publish if chargepoint is disabled

- web/settings/fehlerbericht.html
Safari scheint das Formular nicht zu senden, wenn der Submit-Button deaktiviert wird.
> fix fehlerbericht Safari

- loadvars.sh
- runs/atreboot.sh
- runs/pubmqtt.sh
Avoid wrong values for "Geladen seit Einstecken" when openWB gets reboot (ramdisk loss).
Tested with reboot.
Could not yet test with SW-Update as that obviously overwrites the files until the changes are part of official repo.
> Persist plugin meter value accross restart

- slavemode.sh
In rare occasions at low charge power it could happen that the if-clause at the end of which the `ChargingVehiclesAdjustedForThisCp` is changed from 0 to 1 (assuming the own box always charges) is not executed.
Hence `ChargingVehiclesAdjustedForThisCp` stays at 0 causing a div/0 error in algorithm which again causes charge current to be set to 0.
Once the EV stops charging, another control flow is taken which is finally re-granting charge. End of the story is a nasty oscillation.
The  `ChargingVehiclesAdjustedForThisCp` = 0 compensation has simply been moved out of the critical if statement.
> Slavemode: Fix div/0 in rare cases at low charge currents

- runs/rfid.py
- change of tag handling in mode 2: int -> str
- tags for mode 2 might have changed if there were leading zeros!
> fix: rfidtag as string in all modes

- web/settings/modulconfiglp.php
- added missing checks in select element
- added missing field "evsesources1" for chargepoint 2
- modified help text
> fix configuration of openWB DUO on chargepoint 2

- runs/pubmqtt.sh
- slavemode.sh
This PR adds transmission of a topic `openwb/lp/#/lmStatus` with values
Superseded=0
InLoop=1
DownByLm=2
DownByEv=3
DownByError=4
DownByDisable=5
in order to avoid that part of algorithm needs to be re-implemented in controller side in order to identify, for example, whether the EV or control loop caused a charge stop.
The value will be transmitted only when input file actually exits. The input file only gets written in `slavemode.sh`.
The changes are "informative" only and will not at all affect the actual control of slave mode, either.
> Slave mode: Signal charge status via MQTT

- regel.sh
`atreboot.sh` unconditionally creates randomization value of 0.  
It causes `regel.sh` to not create a random value any more. Similarly `cronnightly.sh` will not delete the file containing 0.  
In other words: The implementation didn't consider reboot where ramdisk gets lost.  
Since randomization is happening in slave mode only, implementation has been changed such that a value of 0 now also triggers creation of new random value.
**Important:** With the new implementation randomization will always be active in slave mode. If that's not acceptable we need a persistent setting in `openwb.conf` (feel free to coment in that case).
> Reliably activate randomization in slave mode after reboot

- modules/smarthome/http/off.py
- modules/smarthome/http/on.py
- modules/smarthome/http/watt.py
- modules/smarthome/sdm630/sdm630.py
- modules/smarthome/shelly/watt.py
- runs/smarthomehandler.py
Der Geräte typ http  wird unterstützt
Die urls werden in folgenden Variablen erwartet:
device_type = http
device_einschalturl
device_ausschalturl
device_leistungurl
device_measuretype = http
device_measureurl
Wenn in der device_leistungurl oder der  device_measureurl
der Platzhalter "<openwb-ueberschuss> übergeben wird, wird diese String zur Laufzeit mit dem aktuellen Überschuss (0 oder positiver Wert) ersetzt.
Beispiel init FIle:
device_einschalturl2 = 127.0.0.1//cust/on.php
device_ausschalturl2 = 127.0.0.1/cust/off.php
device_leistungurl2 = 127.0.0.1/cust/wattd.php?meinParameter=<openwb-ueberschuss>
device_measuretype_3= http
device_measureurl3 = http://127.0.0.1/cust/wattd.php
Zusätzlich wird Leistungsabfrage Shell EM unterstützt
> http Geräte im smarthomehandler Unterstützung

- modules/smarthome/shelly/watt.py
It is possible to add a shelly3EM as a SmartHome-device, but the home page only shows the power consumption of phase 1. This PR fixes that.
I am missing some automated tests... Should there be some tests somewhere?
> Add support for shelly3EM

- runs/atreboot.sh
- runs/cron5min.sh
- runs/cronnightly.sh
- runs/mqttsub.py
- runs/smarthomehandler.py
- web/settings/helperFunctions.js
- web/settings/processAllMqttMsg.js
- web/settings/smarthomeconfig.php
- removed some code still referencing device 10
- changed static limit of 9 devices to global variable in several scripts
- removed color formating in logging of smarthomehandler (not compatible with displaying in browsers)
- added missing underscore "_" for new url parameters (http device type)
- temporary added some js console logging to smarthome config page
- changed clearing of set messages in mqttsub.py to always clear topics (also for wrong payloads)
- proper init of all form fields in smarthomeconfig (fixes initially wrong hidden sections and infinite waiting on save)
- setting all text input fields to required (only validated if visible/not disabled)
- moved "Einschalt-URL" and "Ausschalt-URL" for http devices down into "device can switch" section
- always display "Leistungs-URL" …
> several smarthome fixes

- runs/mqttsub.py
- runs/sendyeargraphdata.sh
- web/logging/yearly.php
- web/logging/yearlychart.js
Neu kann die Jahressicht im Logging abgefragt werden. Ein Klick auf den Datenpunkt springt dann grad aufs Monthly Logging von diesem Monat.
Es werden keine zusätzlichen Log CSV benötigt, sonder alles läuft mit den Monthly CSV-
Zwei Punkte noch zu definieren / fixen:
1) Im Logging Jahressicht kann kein Jahr gewählt werden (disabled)
2) Ab wann wurde von openWB auf eine gesammelte monatslog csv umgestellet ?
Diese Startjahr sollte in yearly.php auf Zeile 123 (startDate: '2017',eingeliefert)  geändert werden.
> Logging Jahressicht

- runs/sendyeargraphdata.sh
Auch Jahre ohne Jan csv Dateien werden korrekt geschickt
Temporär Datei wird nun separat initialisiert
> Auch Jahre ohne Jan csv Dateien werden korrekt geschickt

- web/settings/modulconfiglp.php
- hyundai and kia shared same settings in modulconfig for lp1
- PIN was disabled for hyundai (and accidential for kia)
- moved PIN to kia section and enabled form field
> fix kia soc on lp1

- runs/mqttsub.py
Commit fa08865aeffa43d7ee5226132fe8da35f21d2c81
added lines 1022-1024 of `mqttsub.py`:
```python
if ( not(setTopicCleared) ):
client.publish(msg.topic, "", qos=0, retain=True)
```
But at least for `openWB/set/configure/#` topics, the MQTT server is used intentionally to preserve old value
when openWB reboots or updates or ramdisk gets deleted for whatever other reasons.
**NOTE:** The change of commit fa08865aeffa43d7ee5226132fe8da35f21d2c81 generally affects all
topics that are received by `mqttsub.py` and which do not explicitly have `setTopicCleared = True` added
to their if-condition.
**I'm afraid this change might delete other topics for which deletion is not actually expected. In my understanding,
it is a valid approach to persist some data in MQTT server's database.**
@benderl Did …
> Set setTopicCleared for openWB/set/configure/

- web/settings/settings.php
- web/themes/standard/style.css
Im Standard-Theme war eine Schriftfarbe so hell, dass man die damit erzeugte Schrift auf dem weißen Hintergrund nicht lesen konnte. Es "fehlten" somit einige Überschriften.
> Schriftfarbe auf weißem Hintergrund nicht sichtbar: korrigiert

- web/display/cards/index.html
- introduced global section in charge point settings
- new section is shown for all charge points
This is a workaround as this setting for min+pv is in global scope. Must be changed if this setting is charge point specific in 2.x.
> fix cards display min+pv settings

- runs/smarthomehandler.py
Im Smarthomehandler wurde die Hardcoded device liste entfernt und  durch Range Anweisung ersetzt. Ebenso wird zusätzlich zum device Status der letzte on / off request  separat gespeichert.
> remove hardcoded list in smarthomehandler

- runs/smarthomehandler.py
Detaillierte Fehlermeldung im Smarthomehandler für Speicher und EVU für die Überschussberechnung
> Detaillierte Fehlermeldung im Smarthomehandler

- modules/wr_plenticore/read_kostalplenticore.py
Wenn zB während Update der WR nicht erreichbar ist, landen bisher irreführende Log-Einträge im Log
> Fehlermeldung Modul Plenticore präzisiert

- modules/smarthome/avmhomeautomation/avmcommon.py
- modules/smarthome/avmhomeautomation/credentials.py
- modules/smarthome/avmhomeautomation/off.py
- modules/smarthome/avmhomeautomation/on.py
- modules/smarthome/avmhomeautomation/watt.py
- runs/smarthomehandler.py
This PR adds three scripts `on.py`, `off.py`, and `watt.py` that fulfill the same role as for other smarthome devices. The actors are addressed via a master device (usually a AVM FRITZ!Box router) which itself communications via DECT with the individual actors.
As the AVM Home Automation requires authentication to the DECT master and selection of the actor (here: via name), the call interface to smarthome scripts has been extended to take three additional call arguments. The subprocess call has been slightly refactored as the argument list is constructed explicitely prior to the call to `subprocess.Popen`.
> Add smart home module for AVM Home Automation (FRITZ!Box) switches 

- modules/smarthome/avmhomeautomation/avmcommon.py
I forgot to substitute a variable `sessionid` with the data member `AVMHomeAutomation.sessionID` in #831. The relevant line was not reached outside of an openWB environment where the ramdisk does not exist.
> Fix writing AVM session ID to ramdisk

- runs/smarthomehandler.py
tasmota als gerät kann schalten = nein wieder unterstützt.
> tasmota als gerät kann schalten = nein

- web/tools/wlan/wlan0.sh
Werden Repeater mit gleicher SSID eingesetzt, wurden diese mehrfach erkannt und angezeigt.
Bei SSIDs mit Leerzeichen werden die SSID mit  umgebrochen
Durch die Änderung wie folgt:
> Mehrfache Anzeige von identischen  SSIDs eliminiert

- modules/smarthome/http/watt.py
Leistungsaufnahme kann nun auch bei http mit nachkommas angliefert werden (z.b. 5.2). Wurde von Holgerwolf getested.
https://openwb.de/forum/viewtopic.php?p=22084#p22084
> http requests mit nachkommastellen

- modules/bezug_fronius_sm/main.sh
Die Variable $froniuserzeugung wurde innerhalb des jq Aufrufs nicht als Variable interpretiert.
Diese Version ist live getestet mit froniuserzeugung=0 und froniusvar2=1
> Fronius Bugfix + improved variant handling

- modules/smarthome/avmhomeautomation/avmcommon.py
Log messages will be appended to ramdisk/smarthome.log so they can be
read from status page. ramdisk/smarthomeloglevel is respected.
This is supposed to be helpful in debugging the issue described at https://openwb.de/forum/viewtopic.php?f=5&p=22499#p22499
> Improve logging of AVM Home Automation module

- web/tools/wlan/wlan.php
- web/tools/wlan/wlan1.php
Set autocomplete for ssid and wifi password to off so Browser doesn't save Password in local formular cache.
Trim SSID and Password to avoid whitespaces at beginning or end if copying via clipboard
> WLAN Konfig Enhancement

- runs/atreboot.sh
I believe the following needs to be inserted as the ladelog is not working without this folder.
> Update atreboot.sh as ladelog directory is missing

- modules/soc_mypeugeot/main.sh
- runs/atreboot.sh
- web/settings/modulconfiglp.php
Ersetzt PR899
PSA liefert während des Ladens derzeit keine SoC Aktualisierung. In der Modulkonfiguration für Peugeot kann nun zusätzlich Manuell+Berechnung aktiviert werden.
Dies sorgt dafür dass der initiale SoC zu Ladebeginn über die API abgerufen wird, während des Ladevorgangs wird der SoC dann basierend auf dem Ladezähler berechnet.
> SoC Peugeot: kombiniere manuell+berechnung und PSA modul, ersetzt #899

- runs/smarthomehandler.py
Sofen in einer Openwb Installation kein Speicher vorhanden ist, wird der pro Smarthomedevice vorhandene speichersocbeforestop falsch vorbelegt (heute 0, sollte 100 sein)
> Falsche Vorbelegung im Smarthomehandler korrigiert

- modules/soc_eq/auth.py
- modules/soc_eq/callback_lp.php
- web/settings/modulconfiglp.php
Optimizazion to use a single callback URL for every chargepoint.
Make use of state field in OAuth API to set the chargepoint lp1, lp2, may be extended up to 9 chargepoints as I use only the last character of state field!
> Mercedes EQ SoC Module change to single callback URL for max 9 Chargepoints

- runs/smarthomehandler.py
- web/settings/smarthomeconfig.php
Neue Definition vom  Smarthomedevice Parameter "Speicherbeachtung beim Einschalten":
Parameter in % Ladezustand.
0% deaktiviert die Funktion.
Bei deaktivierter Funktion oder wenn der Ladezustand grösser gleich Parameter wird die Speicherleistung bei der Berechnung der Ein und Ausschaltschwelle berücksichtigt (analog heute).
Unterhalb dieses Wertes ist für die Berechnung der Ein und Ausschaltschwelle nur die direkt am EVU-Punkt gemessene Einspeisung/Bezug relevant.
Somit kann neu bei maximaler Speicherladung ein Smarthomedevice aktiviert werden, auch wenn der gewünscht Ladezustand vom Speicher noch nicht erreicht ist. 
Textvorschlag im GUI gemacht, bitte anpassen. 
Smarthomelogging ausgebaut.
> maximale Speicherladung für smarthomehandler berücksichtigen

- runs/initRamdisk.sh
Temporary files in ramdisk `mqtt....` are used to avoid publishing the same value over and over. But after a reboot it is intended to publish all values. So we initialize these files with something to force an update.
> init temp mqtt files in ramdisk to force update

- runs/smarthomehandler.py
- web/settings/smarthomeconfig.php
Bei der Ueberschussberechnung "EVU" muss auch eine eventuelle Speicherentladung mit einbezogen werden. Anderenfalls wird ein Bezug nicht richtig erkannt, da der Speicher ausgleicht.
Siehe auch:
https://openwb.de/forum/viewtopic.php?p=23027#p23027
> smarthomehandler Ueberschussberechnung "EVU" 

- runs/atreboot.sh
- runs/initRamdisk.sh
- runs/smarthomehandler.py
atreboot.sh
Der Smarthomehandler wird immer mit output umleitung (in smarthomehandler.log) gestartet
initRamdisk.sh
vom Gui/MQTT wird der maxBatterypower Wert vom Smarthome nur in dem MQTT openWB/config/get/SmartHome/maxBatteryPower gespeichert.
Der Smarthoemhandlery.py erwartet diesen auf der Ramdisk in ramdisk/smarthomehandlermaxbatterypower.
Bei einem Reboot / Neustart der openwb wird diese Variable ramdisk/smarthomehandlermaxbatterypower mit dem MQTT Wert ersetzt (das gleicher Verfahren ist auch in der loadvars für mehrere Simcount Variablen im Einsatz:
2021-02-05 18:06:31: loadvars read openWB/evu/WHImported_temp from mosquito 28578202616 (LV0)
2021-02-05 18:06:35: loadvars read openWB/evu/WHExport_temp from mosquito -8691007530 (LV0)
2021-02-05 18:06:39: loadvars read …
> samrthomehandler wartet beim boot und maxbatterypower aus ramdisk

- modules/smarthome/mystrom/off.py
- modules/smarthome/mystrom/on.py
- modules/smarthome/mystrom/watt.py
- modules/smarthome/shelly/watt.py
- runs/atreboot.sh
- runs/smarthomehandler.py
Unterstützung von mystrom Steckdosen (analog shelly)
Die Temperatursensoren Shelly (optional 1 bis 3) und Mystrom (immer 1) laufen wieder.
Diese Temperaturen werden nur angezeigt, wenn unter Smarthomedevice 1 oder 2 definiert.
> mystrom switches und  temp sensoren im smarthomehandler

- web/themes/EvenDarker/theme.html
- web/themes/Gauges/theme.html
- web/themes/dark/theme.html
Geänderte JS-Datei scheint (warum auch immer) von einigen Browsern trotz anderem Query-String nicht immer neu geladen zu werden, sondern kommt teilweise noch aus dem Cache. Im PR wurde der String geändert, um zu sehen, ob das Problem bestehen bleibt.
> Erzwinge JS reload

- modules/smarthome/shelly/watt.py
- runs/mqttsub.py
- web/settings/misc.php
- web/settings/smarthomeconfig.php
- rearrange display settings (better support for external displays)
- added smarthome 2.0 device "none" to support replacement for old "Verbraucher" (work in progress, just config options)
- fix function call in `shelly/watt.py`
> fix display settings, new smarthome device none

- modules/smarthome/acthor/watt.py
- modules/smarthome/http/watt.py
- runs/smarthomehandler.py
Neu können für HTTP Geräte in separater Leistungsmessung optional auch Zähler (mittels separater URL) übergeben werden.
Für Acthor werden Typ und installierte Leistung zur Berechnung vom Skalierungsfaktor genommen.
AVM Geräte mit Gerät kann schalten = Nein werden wieder gemessen
> smarthomehandler HTTP / acthor / AVM

- modules/bezug_json/main.sh
- modules/soc_eq/main.sh
- modules/speicher_json/main.sh
- modules/wr_json/main.sh
Anpassung der Debug Funktionen auf die helperfunction
@benderl : kannst du dir erklären, warum die Ausgaben des caller bei den beiden LPs unterschiedlich ist?
2021-02-14 16:11:34: Lp2: Nothing to do yet. Incrementing timer. 0 < 6 (LV1) at 54 main /var/www/html/openWB/modules/soc_eq/main.sh
2021-02-14 16:11:36: Lp1: Nothing to do yet. Incrementing timer. 0 < 6 (LV1) at 54 main modules/soc_eq/main.sh
2021-02-14 16:11:44: Lp2: Nothing to do yet. Incrementing timer. 1 < 6 (LV1) at 54 main /var/www/html/openWB/modules/soc_eq/main.sh
2021-02-14 16:11:46: Lp1: Nothing to do yet. Incrementing timer. 1 < 6 (LV1) at 54 main modules/soc_eq/main.sh
2021-02-14 16:11:53: Lp2: Nothing to do yet. Incrementing timer. 2 < 6 (LV1) at 54 main /var/www/html/openWB/modules/soc_eq/main.sh
2021-02-14 16:11:55: …
> SO_EQ umbau auf openwbDebugLog

- modules/smarthome/avmhomeautomation/avmcommon.py
Unplugged devices still have the relevant XML subtrees for powermeter in
the AVM API, but with empty inner text. Filtering out non-present
devices prevents an exception when casting an empty string to float.
> avmhomeautomation: Filter non-present devices

- modules/soc_eq/main.sh
With the change to global function openwbDebugLog, the variable LOGFILE was overloaded so the standard soc output from the python module was written to openwb.log instead of soc.log.
> Soc_EQ Fix Logfile

- modules/smarthome/tasmota/watt.py
Neu wird bei tasmota wie bei Shelly zuerst der On /Off Status abgefragt, bevor auf den Workaround mit der aktuellen Leistungs ausgewichen wird.
Details siehe
https://github.com/snaptec/openWB/issues/1081
> tasmota an shelly angleichen

- modules/bezug_fronius_sm/main.sh
- fixed bug introduced by refactoring of the bezug_fronius_sm module
- wrong power source was used when smartmeter is in load path
> fix: fronius sm in load path

- modules/soc_manual/main.sh
Zeile 102 scale=5; ergänzt. Ansonsten ergeben sich durch die Rundung innerhalb der Rechnung zu zuhohen Werten bei currentSocDiff.
> Update main.sh in soc_manual

- web/themes/EvenDarker/style.css
- web/themes/EvenDarker/theme.html
- web/themes/Gauges/livechart.js
- web/themes/Gauges/style.css
- web/themes/Gauges/theme.html
- web/themes/dark/livechart.js
- web/themes/dark/processAllMqttMsg.js
- web/themes/dark/style.css
- web/themes/dark/theme.html
- größere Schrift bei kleinen Screens für Leistungswerte in Standard, Dark, Even Darker, Gauges
- Wort "SoC" unter Ladestand entfernt, da überflüssig und mehr Platz für Schrift
- Pumpen des Charts nach erstem Laden verhindert
> Schriftgröße Mobilgeräte geändert

- runs/smarthomehandler.py
HTTP Devices haben keine IP Adresse . Fehler im On / Off behoben
> smarthomehandler 2.0

- processautolock.sh
Setting was read from openwb.conf but never used. Autolock always waited for current charging to stop before locking charge point.
> fix autolock: respect waitUntilFinished setting

- web/settings/mqtt.php
- web/tools/savemqtt.php
Der Code war ja eigentlich größtenteils schon darauf ausgelegt mit mehreren Brücken zu arbeiten, hat man das bewusst entfernt?
Die Änderung zeigt jetzt einfach immer eine Eingabemaske für eine neue Brücke an, egal wie viele Brücken schon konfiguriert sind.
Das CleanAndExit war nötig, falls:
- Der User Brücke A ungültig ändert und eine Fehlermeldung bekommt
- Der User dann zurück geht auf die Einstellungsseite
- Der User jetzt Brücke B gültig bearbeitet
--> beide Brücken sind gelöscht worden
> Möglichkeit mehrere MQTT-Brücken einzurichten

- modules/smarthome/avmhomeautomation/avmcommon.py
FritzOS versions before 6.98 do not include voltage values in
the getdevicelistinfos API call we use in this module.
> avmhomeautomation: Allow voltage to be unavailable

- modules/bezug_discovergy/main.sh
Just added "" to the password variable to support spaces in password.
Tested on command line, outside of openWB.
> Update curl call to support password with spaces

- modules/wr_discovergy/main.sh
Just added "" to the password variable to support spaces in password.
Tested on command line, outside of openWB.
> Update curl call to support spaces in password

- modules/soc_psa/main.sh
- runs/updateConfig.sh
- web/settings/modulconfiglp.php
- Dauerschleife der Onlineabfrage beseitigt, wenn der Abruf beim Ladestart fehlschlägt
- Der abgerufene SoC wird verworfen, wenn er gleich dem SoC vor Ladestart ist und der Wagen angesteckt ist (verhindert ein zurückfallen auf Startwert der Ladung, wenn falsche Werte geliefert werden)
- Der online abgerufene SoC wird auch übernommen, wenn er bis zu 90s älter ist als der bekannte SoC (verhindert, dass der Wert obwohl er korrekt ist nicht übernommen wird, wenn es eine geringe Uhrzeitabweichung zwischen Server und openWB gibt)
-Onlineabfrageintervall konfigurierbar
> Update PSA SoC

- runs/smarthomehandler.py
Nur  Device (mit bei Autoladen ausstellen = Ja) die von Openwb aktiviert oder in Pv Modus gesetzt wurden bei der Berechnung der Leistungsaufnahme abschaltbar berücksichtigen
> Korrektur Leistungsaufnahme abschaltbar

- openwb-install.sh
Loading the deprecated Module Adafruit_MCP4725 via pip.
Include Installation for pip and pip3 into installer.
Please change Installation Description in README.md to use bash instead of shell
curl -s https://raw.githubusercontent.com/snaptec/openWB/master/openwb-install.sh | sudo bash
> Fix Installer

- runs/smarthomehandler.py
Die Tagescounter für alle devices werden einmalig um 0:00 zurückgestellt, zugleich wird ein Flag gesetzt das die Aktion für heute durchgeführt wurde. Ebenso wird genau um 2:00  dieses Flag zurückgesetzt, so dass am beginn vom nächsten Tag das zurücksetzten wieder erfolgen kann,. Da mit dem Wechsel auf Sommerzeit die Uhr von 2:00 auf 3:00 vorspringt, wurde das Flag per gestern nicht zurückgesetzt, so dass die Tageszähler heute falsch  sind. Das zurücksetzten vom Flag wird neu um 1:00 gemacht
> sommerzeit umstellungsproblem

- web/display/cards/setupMqttServices.js
- web/display/gauges/live.js
- web/display/minimal/setupMqttServices.js
- web/display/parentwb/setupMqttServices.js
- web/display/simple/live.js
- web/live.js
- web/logging/chargelog/ladelog.js
- web/logging/dailychart.js
- web/logging/monthlychart.js
- web/logging/yearlychart.js
- web/settings/setupMqttServices.js
- web/status/setupMqttServices.js
- web/themes/Gauges/setupMqttServices.js
- web/themes/colors/setupMqttServices.js
- web/themes/dark/setupMqttServices.js
`location.host` includes the port number, so if one is specified, the resulting address is invalid as another port number is appended (hostname:port:9001). Use `location.hostname` instead.
This also allows to configure httpd to serve from a non-default port.
> Fix MQTT clients when a port number is specified.

- runs/cron5min.sh
If WLAN (and Bluetooth) is disabled (e.g. to reduce power consumption a bit) using `/boot/config.txt` entries
```
dtoverlay=pi3-disable-wifi
dtoverlay=pi3-disable-bt
```
the `cron5min.sh` issues errors like
```
SIOCSIFADDR: Kein passendes Gerät gefunden
wlan0:0: ERROR while getting interface flags: Kein passendes Gerät gefunden
SIOCSIFNETMASK: Kein passendes Gerät gefunden
wlan0:0: ERROR while getting interface flags: Kein passendes Gerät gefunden
/var/www/html/openWB/runs/cron5min.sh: Zeile 257: /sys/class/net/wlan0/carrier: Datei oder Verzeichnis nicht gefunden
```
While it's probably not the default setting of openWB, it might be helpful for manual installations w/o WLAN and it really shouldn't cause any harm for the default case (2 additional "if" conditions every 5 minutes).
> Check for presence of WLAN before try to config it

- web/settings/modulconfigevu.php
Beschreibung in den Einstellungen von kWh auf Wh geändert,
Der Wert wird intern zwar weiterhin mit kWh Variablennamen weitergeleitet (vzloggerkwhline, vzloggerekwhline) Aber der Anwender weiß nun, dass die Daten in Wh übergeben werden sollen.
Damit wird auch der Daily Log und die kWh Summary auf der Anzeige richtig dargestellt.
Forum: https://openwb.de/forum/viewtopic.php?f=9&t=3004
Gruß, Stefan
> Update modulconfigevu.php VZlogger kWh -> Wh

- runs/atreboot.sh
- runs/cleanup.sh
- runs/senddebug.sh
- do not cleanup logfiles if senddebuglog is running (prevents incomplete debug files)
- create backup folder at reboot
- do not send tronity auth data in debuglog
> fix backup and debug.log

- runs/smarthomehandler.py
Die Runningtime  wird um 0:00 zurückgesetzt. Das wird neu im Log protokolliert und ein Update im MQTT erzwungen. Die  Runningtime und die Anzahl Ein / Ausschaltung wird ebenso neu ins smarthome.log geschrieben.
Siehe auch
https://openwb.de/forum/viewtopic.php?p=30475#p30475
> Rücksetzen  Running time im smarthomehandler

- modules/sdm120modbusSocket/readsdm.py
Add missing, but crucial, sleep before second modbus register read.
Read is failing from time to time without it.
> sdm120modbusSocket: Missing delay before reg read

- loadvars.sh
Retrieve dailychargelp[1-3] by reading the CSV file from `loadvars.sh` instead of POSTing to 127.0.0.1:80 which doesn't work if httpd is serving from a different port.
> Avoid hardcoding 127.0.0.1:80

- modules/soc_manual/main.sh
- modules/soc_psa/main.sh
Bei Verwendung des man/calc und PSA+man/calc SoC Moduls wurde die SoC Datei erst geschrieben nachdem der SoC um einen Zähler erhöht wurde. Dies führt zu Lücken im Logging. 
Der bisher verwendete Weg über sed kommt mit Zahlen kleiner 1 nicht klar da diese nur als '.123' ausgegeben werden, nicht als '0.123'. Der Weg über awk löst dieses Problem.
> fix fehlende SoC Datei nach Ladestart

- modules/bezug_solarwatt/main.sh
- modules/speicher_solarwatt/main.sh
- modules/wr_solarwatt/main.sh
Web Module for Speicherconfiguration configures speicher1_ip as IP for the information gathering. Modules reference speichersolarwatt which is not set up.
> Solarwatt Modules use wrong variable for URL

- runs/smarthomehandler.py
Manuel geschalteten Devices werden immer unter nicht abschaltbaren Devices geführt (und lösen somit kein PV laden aus)
> Manuelle geschaltete devices

- runs/mqttsub.py
SBFSpot sendet die PACTot als Float, Python kann aber aus einem Float-String nicht direkt ein Int machen.
Workaround ist die Dekodierung der Message nach Float, dann nach Int.
Beispiele:
```
>int('12345')
12345
>float('12345.0')
12345.0
>float('12345')
12345.0
>int(12345.0)
12345
>float(12345)
12345.0
>int('12345.0')
File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '12345.0'
>int(float('12345.0'))
12345
```
> ermöglicht das Senden der aktuellen PV-Leistung als Float

- modules/keballlp1/check502.py
- modules/keballlp1/info.py
- modules/keballlp1/main.sh
- modules/keballlp1/setcurrkeba.py
- modules/keballlp2/main.sh
- runs/set-current.sh
Sofern Keba Ladestation mit der Firmware-Update V3.10.27 (keba -c ) oder Firmware-Update  V1.12 (keba-x) ausgerüstet sind, können diese neu über Modbus Schnittstelle angesteuert werden. Openwb überprüft beim ersten Zugriff (pro OpenWB Boot) auf die Keba Wallbox, ob der Port 502 auf ist. Wenn das der Fall ist, wird die Keba nur mit Modbus angesteuert / ausgelesen. Sofern der Port 502 nicht auf ist, wird die Keba mit der alten UDP Schnittstelle angesteuert. Parameter im GUI braucht es keine. Das ganze wurde mit zwei Keba  Wallboxen getestet.
Das Kommando zur Anzeige der Sollvorgabe (z.b. S8) wird im Modbus Protokoll nicht unterstützt.
> Keba mit Modbusansteuerung

- web/settings/cloudregistrate.php
creating a cloud bridge failed if settings are password protected due to missing auth headers
> fix cloudconfig auth headers

- loadvars.sh
- last valid value is kept for three cycles
- value is set to zero, if still invalid afterwards
> handling of invalid house consumption

- runs/smarthomehandler.py
- web/settings/smarthomeconfig.php
Neu wird ein Auto erst dann als Ladend betrachtet, wenn mehr wie 1000 Watt Leistungsaufnahme durch die Wallbox vorliegt
> Smarthomehandler Autoladen

- loadvars.sh
- runs/mqttsub.py
- clicking the "force soc update" button in web gui sets soctimer to 20005
- this timer value forces an update even if the car is not plugged in
credits: Ulrich Bartelheimer
> forced soc update if not plugged

- rfidtag.sh
- slavemode.sh
Fix two minor issues with "standard socket":
* Standard socket deactivation was executed so fast that deactivation indication didn't reach controller
* Standard socket couldn't be deactivated using a valid socket RFID tag
> Fix two glitches in standard socket deactivation

- web/themes/dark/processAllMqttMsg.js
Berechnung der Laufzeit von Smarthomedevices fürs Gui korrigiert (Rundung ausgeschaltet)
Nur im Dark Thema, Standard referenziert auf Dark
> Smarthomedevices Laufzeit im Gui

- modules/mpm3pmll/readall.py
- modules/mpm3pmll/readmpm3pm.py
- modules/sdm120modbusSocket/readsdm.py
- runs/pubmqtt.sh
Target topics:
`openWB/lp/1/MeterSerialNumber`
`openWB/socket/MeterSerialNumber`
Currently supported for SDM120 and SDM630.
Are there any other meters that support S/N read via Modbus (afaik Lovato and MPM3PM don't)?
For now implemented for LP1 and standard socket.
Due to lack of hardware I cannot test for LP2-8 but
I can implement for those LPs if somebody can take the testing. So feel free to comment if you want me to adapt LP2-8, too as part of this PR.
> Read and MQTT publish meter serial numbers

- .editorconfig
Ich habe gerade einen PR aufgemacht und dann viel mir doch noch ein... Bei dem letzten PR habt ihr geschimpft, weil ich Leerzeichen als Einrückung verwendet habe anstatt Tabs. Das habe ich dann nochmal schnell geändert. Doof ist es trotzdem, denn das ist nirgendwo dokumentiert und wenn Tabs auf die gleiche Breite eingestellt sind wie man üblicherweise Leerzeichen verwendet fällt es auch nicht auf.
Ganz offensichtlich bin ich nicht der einzige, der das "falsch" gemacht hat. Ich habe mal gezählt welche Dateien welche Einrückung verwenden:
|Endung   |Tabs|Leerzeichen|
|---------|----|-----------|
|.conf    |1   |0          |
|.css     |16  |25         |
|.eot     |4   |3          |
|.htaccess|0   |1          |
|.gif     |2   |           |
|.html    |25  |5          |
|.idx     |4   |0 …
> Editorconfig hinzufügen um Verwirrung um Einrückung etc. auszuräumen

- modules/soc_tesla/main.sh
- runs/cronnightly.sh
- runs/replaceinconfig.sh
- runs/senddebug.sh
- runs/updateConfig.sh
- runs/wlanconnect.sh
`sed -i` creates a temporary file and replaces the original file when successful. This fails with "Device or resource busy" when openwb.conf is mounted from a Docker host because it would change the inode.
This change replaces all invocations of `sed -i` on openwb.conf so that the replacement result is stored in memory and then written to the target file in a separate step.
See https://github.com/IngmarStein/openwb-docker/issues/3
> Fix openwb.conf manipulations with sed when running in Docker

- runs/atreboot.sh
These got lost in https://github.com/snaptec/openWB/commit/a49e67ffb92bb6187360713bf06da8ee233608ac
Fixes
```
/var/www/html/openWB/runs/atreboot.sh: line 171: syntax error near unexpected token `else'
/var/www/html/openWB/runs/atreboot.sh: line 171: `else'
```
> Restore missing lines in atreboot.sh

- rfidtag.sh
As promised in https://github.com/snaptec/openWB/pull/1420#issuecomment-854493022 this is the minimal change needed to support display unlock in case of _valid_ RFID tag scan in "mode 1".
**Note:**
The code (also the original one of https://github.com/snaptec/openWB/pull/1420) has a behaviour that is important to notice: Even in case of valid RFID tag there can be publishes on the `tagScanInfoLp*` with validity "0" (invalid).
A proper fix for this would require significant refactoring of `rfidtag.sh`.
Currently that effort seems not to be justified as the "invalid tag" publishes do not have any impact on UI behviour (UI just ignores it).
A more simple work-around could be to not publish immediately but just update ramdisk file. This would, however, reduce responsiveness of display as it …
> Send tag scan info also for RFID mode 1

- web/display/yourcharge/js/main.js
Unfortunately in https://github.com/snaptec/openWB/pull/1420 we accidentially included an R&D setting that disabled screen lock in case of browser refresh.
This PR re-enables locking in case of refresh.
The rest of diff should be white-space-only (indentation).
Sorry for the additional effort.
> YourCharge Display Theme: fix lock screen on browser refresh

- modules/smarthome/avmhomeautomation/avmcommon.py
Smarthome log mit der geichen Encoding fortschreiben wie der smarthomehandler selbst
f = open( logfile_string , 'a',encoding='utf8')
> smarthome.log encoding für avm

- modules/soc_eq/soc.py
API sometimes lacks the soc value. Added a handling for that case. Soc is set to 0 and Message including the response is written in soc.log
> Additional Handling of incomplete responses

- modules/soc_eq/soc.py
Define variables for soc and range to prevent errors when the API doesn't deliver a value.
> Bugfix SOC_EQ

- modules/soc_bluelink/main.sh
- modules/soc_bluelinklp2/main.sh
- modules/soc_kia/abrp.py
- modules/soc_kia/main.sh
- modules/soc_kia/parameters.py
- modules/soc_kia/soc.py
- modules/soc_kia/trigger.py
- runs/updateConfig.sh
- web/settings/modulconfiglp.php
Dummy-Modul für Hyundai entfernt und Kia+Hyundai komplett zusammengeführt
Weitere Daten für ABRP-Push hinzugefügt und Anzahl der Uploads verringert
Neue Konfigurationsmöglichkeiten unter "Erweiterte Einstellungen" verfügbar
> [Kia/Hyundai] Abschaltung Hyundai-Dummy / ABRP / Erweiterte Einstellungen

- modules/smarthome/sdm630/sdm630.py
- runs/mqttsub.py
- runs/smarthomehandler.py
- web/settings/smarthomeconfig.php
- web/settings/topicsToSubscribe_smarthomeconfig.js
Port für sdm630 auswählbar gemacht (Smarthomehandler und Gui)
Im Gui pro Smarthomedevice
StartTime, Endtime und Homecosumtion hinzugefügt (nur Gui)
> Sdm630/Elgris Port auswählbar , Gui für Smarthomehandler erweitert

- web/themes/colors/powerdata.js
- web/themes/dark/processAllMqttMsg.js
Smarthome runtime used toFixed(0) for fractional hours which rounds up
for everytime the fractional part becomes larger than .5. Replacing with
Math.floor leads to the desired outcome.
> Fix smarthome runtime after 30 min elapsed for every full hour

- loadvars.sh
- runs/smarthomehandler.py
Bisher wurde die Leistungsaufnahme aller Devices vom Hausverbrauch abgezogen. Neu kann das pro Device einzeln definiert werden. Der Smarthomehandler errechnet die abzuziehende Leistungsaufnahme der Devices und in Loadvars.sh wird der aktuelle Hausverbrauch nun anderes gerechnet. Diese Änderung bezieht sich auf die Startseite und das Langzeitlogging. Die Tages, Monats und die Jahreslogs werden später noch angepasst.
> Smarthomeerweiterung Hausverbrauch

- modules/smarthome/mqtt/off.py
- modules/smarthome/mqtt/on.py
- modules/smarthome/mqtt/watt.py
- modules/smarthome/viessmann/off.py
- modules/smarthome/viessmann/on.py
- modules/smarthome/viessmann/watt.py
- runs/mqttsub.py
- web/settings/smarthomeconfig.php
Viessmann Wärmepumpe hinzugefügt. Bei ON wird die "Einmalige Warmwasserbereitung" über Modbus ausgelöst.
Bei OFF wird die "Einmalige Warmwasserbereitung" über Modbus gestoppt.
MQTT Modul hinzugefügt, hier noch keine topics, nur Gui und Modulrahmen
> smarthomehandler Viessmann und MQTT (nur Gui)

- modules/smarthome/viessmann/off.py
- modules/smarthome/viessmann/on.py
Die WP von Viessmann braucht zwingend einen close auf die modbus Schnittstelle anderenfalls hängt sich die Steuerung der WP auf.
> smarthomehandler viessmann

- web/api.php
- web/settings/mqttapi.php
Ich habe mal überlegt, wie man weiter das iOS-Widget verwenden kann wenn openWB mit 2.0 keine Ramdisk mehr hat.
Daher die Idee der "MQTT-HTTP-Brücke". Über die HTTP-API können so alle MQTT-Topics gelesen und geschrieben werden.
Beispiel schreiben: `http://IP/openWB/web/api.php?topic=openWB/set/pv/1/W&message=-1000`
Beispiel lesen: `http://IP/openWB/web/api.php?topic=openWB/pv/W`
Vielleicht ist es ja auch jetzt schon für manche Anwendungsfälle sinnvoll, da die HTTP-API schon sehr dünn ist. Ihr müsst es aber auch nicht mergen wenn irgendwas dagegen spricht, ist wie gesagt eher als Überlegung entstanden.
> MQTT mit HTTP-API

- runs/smarthomehandler.py
Devices, die vom Hausverbrauch abgezogen werden müssen (je nach Parametrisierung vom Device) werden zusätzlich neu in der
mqtt Variable openWB/SmartHome/Status/wattnichtHaus
gepublisht. Der Hausverbrauch rechnet sich dann so:
hausverbrauch=$((wattbezugint - pvwatt - ladeleistung - speicherleistung - shdall_w - verb1_w - verb2_w - verb3_w))
Wobei shdall_w aus openWB/SmartHome/Status/wattnichtHaus kommt und alle aktuellen Liestungsaufnahmen der einzelnen Devices ersetzt.
Im Status wird neu der Coutner für die Anlauferkennung ausgegeben (onstandby)
> aktuelle Leistungsaufnahme für smarthomehandler

- loadvars.sh
- modules/speicher_alphaess/readalpha.py
- modules/speicher_alphaess/readv123.py
- modules/wr_alphaess/main.sh
- modules/wr_alphaess/readalpha.py
- modules/wr_alphaess/readv123.py
- web/settings/modulconfigpv.php
Anwender des AlphaESS-Speichermoduls, welche die PV-Watt-Werte vom
Speicher auslesen wollen, muessen jetzt explizit das dazugehoerige
PV-Modul waehlen. Die Konfiguration ueber die Firmwareversion verbleibt
auf der Config-Seite vom Speicher (wie auch beim AlphaESS-EVU-Modul).
> Trenne AlphaESS Speicher und Wechselrichter

- web/settings/cloudregistrate.php
- web/settings/mqtt.php
- web/settings/savemqtt.php
Setting `try_private` is not compatible with many non-Mosquitto brokers but beneficial for Mosquitto.
This PR allows to configure it via UI.
Addresses issue #1498.
> Bridge setting 'try_private' configurable via UI

- modules/bezug_fronius_s0/fronius_s0.py
- modules/bezug_fronius_s0/main.sh
- modules/bezug_fronius_sm/main.sh
Siehe Diskussion: https://openwb.de/forum/viewtopic.php?f=9&t=3861
Änderungen in modules/bezug_fronius_s0/fronius_s0.py:
* Parametervergleich für Primo-Mode zeichenbasiert
* Zusammenrechnen des Bezugs zahlenbasiert
* Korrektur des Zugriffs auf JSON-Response mit Zählerdaten
Änderungen in modules/bezug_fronius_s0/main.sh:
* Korrektur des Parameters $froniusprimo
Außerdem wurde bei der Frequenzbestimmung für GEN24 Geräten versucht auf einen falschen/unbekannten Wert zuzugreifen.
> Fronius mit S0

- runs/cron5min.sh
Die Parametrisierung vom Device "Im Hausverbrauch einrechnen" wird nun auch in der Berechnung der KWH vom Hausverbrauch korrekt berücksichtigt.
> KWH vom Hausverbrauch korrigiert

- runs/readmodbus.py
Commit https://github.com/snaptec/openWB/commit/d117a6eaadf609d7a0a803bb068c897430fdc64e introduced a bug in `runs/readmodbus.py` causing duplicate property access:
The original single line
```python
print(rq.registers[0])
```
has been split into two lines:
```python
result = request.registers
print(result.registers[0])
```
So first the `request.registers` is assigned to variable `result`. `result` now directly contains the array. However, `result.registers[0]` is being printed afterwards which obviously leads to an error because the array doesn't have a property `registers`:
```
File "runs/readmodbus.py", line 26, in <module>
print(result.registers[0])
AttributeError: 'list' object has no attribute 'registers'
```
Not sure why this is only discovered …
> Remove duplicate property access in readmodbus.py

- modules/bezug_json/main.sh
- modules/bezug_json/read_json.py
- modules/speicher_json/main.sh
- modules/speicher_json/read_json.py
- modules/wr2_json/main.sh
- modules/wr_json/main.sh
- modules/wr_json/read_json.py
From Shell -- Python3.
Requires python jq for python3. Should be present, as it is still used
Be careful with URLS, that don't contain a http://. Worked in curl but doesn't work in Python request.
> Generic JSON Modules in Python

- modules/bezug_fems/fems.py
Here's my adaption of FEMS EVU module.
It now delivers all EVU values except for Power Factor. So per-phase powers are now available, too.  
Per-phase currents are now computed from power and voltage as power is signed to distinguish import and export while the per-phase current obtained directly from openEMS is always positive.
It greatly increases performance by only issuing two REST requests to openEMS. This is achieved by using the [Regex Feature](https://openems.github.io/openems.io/openems/latest/edge/controller.html#_get) of openEMS.
Using a single request for all per-phase values also has another important advantage: The values queried are as consistent as possible. The original approach, for example issued REST request for phase voltage and current indepently. This could result …
> FEMS / openEMS improvements

- modules/smarthome/smaem/speedwiredecoder.py
- modules/smarthome/smaem/watt.py
- runs/smarthomehandler.py
English:
I've reused the existing speedwiredecoder.py and created a module for using a SMA EnergyMeter for measuring.
The ret-file contains the current consumption (watt) and the total consumption (wattc).
My EnergyMeter is used for my heatpump and the heatpump is shut down twice a day. During this time the energy won't send and the current consumption is wrong. So I've implemented a workaround for handling an existing ret-file but changing the current consumption to 0 while the powerc remains.
Deutsch:
Ich habe ein Smarthome-Modul entwickelt um einen SMA EnergyMeter zur  Leistungsmessung zu verwenden.
Dabei habe ich die bestehende speedwiredecoder.py verwendet.
Es wird die aktuelle Leistungsaufnahme (watt) und die Summe der Leistungsaufnahme (wattc) ausgelesen.
Mein EnergyMeter misst …
> Smarthome: Use SMA EnergyMeter as measuring module

- modules/smarthome/elwa/watt.py
Return file wird bei jedem Durchlauf geschrieben (analog Acthor)
Standard Einrückungen  für python verwendet
> watt.py elwa

- web/themes/colors/yieldmeter.js
Aktuell werden die Kategorien immer voll ausgeschrieben und überlagern sich daher. Zukünftig werden diese abhängig von der Anzahl der Elemente gekürzt,
> Theme Colors: Yieldmeter truncate categories

- modules/wr_json/read_json.py
WR liefert kein numerisches Ergebnis. Fehler wird jetzt abgefangen und Watt auf 0 gesetzt. Bei einschlafenden WR bleibt sonst der letzte Wert über die ganze Nacht bestehen.
https://openwb.de/forum/viewtopic.php?p=46176#p46176
> fix wr_json für einschlafende WR

- runs/smarthomehandler.py
- web/settings/smarthomeconfig.php
Autoladen Ausschalten
Ist dahingehen geändert, dass ein Device bei einer Autloladung nicht hart ausgeschaltet wird sondern die Ausschattschwelle auf 0 gesetzt wird (wenn es vorher ein Bezug) war und dann die Steuerung dem Smarthomehandler überlassen wird.
Die Anlauferkennung kann nun abgeschaltet werden
> smarthome Autoladen

- modules/soc_i3/index.php
It seems the new name is "charging_status". Without the change query for SoC still works but reports
```
PHP Notice:  Undefined property: stdClass::$chargingSystemStatus in /var/www/html/openWB/modules/soc_i3/index.php on line 176
PHP Notice:  Undefined property: stdClass::$chargingSystemStatus in /var/www/html/openWB/modules/soc_i3/index.php on line 177
```
every time.
**Additional notice:**  
BMW is using a LetsEncrypt certificate for its server(s). Due to expiry of cross-signing certificate, an "apt update && apt upgrade -y" was necessary to get trust for the new LetsEncrypt root CA !
@snaptec How will this be handled for openWBs without root access? I don't think any update UI feature is available for OS updates yet.
Separate issue https://github.com/snaptec/openWB/issues/1595 has …
> BMW has renamed JSON field "chargingSystemStatus"

- modules/bezug_ethmpm3pm/main.sh
- modules/bezug_ethmpm3pm/readlovato.py
- modules/bezug_ethmpm3pm/readmpm3pm.py
- modules/bezug_ethmpm3pm/readsdm.py
Anpassung der EVU-Kit Module. Die Module können jetzt Parameter für IP, Port und Unit_id übernehmen.
Ohne Parameter werden die bisherigen Defaults verwendet. 
Es können 1-3 Parameter übergeben werden
1. IP 
2. Port
3. UNIT_ID
In dieser Reihenfolge sind die Parameter auch beim Aufruf zu übergeben, um die entsprechende Variable im Programm zu überschreiben. 
@benderl : Bitte eingehend überprüfen, ob das für openWB so funktioniert.
Ich habe auch auf meiner openWB mal geschaut, wie es mit den pymodbus Versionen aussieht.
pi@openWB:~ $ pip list |grep -i modbu
**pymodbus (2.5.1)**
pi@openWB:~ $ pip3 list |grep -i modbu
**pymodbus (2.4.0)**
Es sind unterschiedliche Package Versionen installiert. Aktuellste Version wäre pymodbus 2.5.2.
> Flexible evu-Kit Modules (parameters)

- modules/wr2_ethlovato/main.sh
- modules/wr2_ethlovatoaevu/main.sh
- modules/wr_ethmpm3pmaevu/main.sh
- modules/wr_pvkit/main.sh
- modules/wr_pvkit/readlovato.py
- modules/wr_pvkit/readmpm3pm.py
- modules/wr_pvkit/readsdm.py
Anpassung der PV-Kit Module. Die Module können jetzt Parameter für PV (1/2), IP, Port und Unit_id übernehmen.
Ohne Parameter werden die bisherigen Defaults verwendet.
Es können 1-4 Parameter übergeben werden
1. PV (1 oder 2)
2. IP
3. Port
4. UNIT_ID
In dieser Reihenfolge sind die Parameter auch beim Aufruf zu übergeben, um die entsprechende Variable im Programm zu überschreiben.
Da es sich hierbei auch um Standard Module der openWB handelt (PV-Kit), bitte gut testen. ein erster erfolgreicher Test des SDM630 Moduls duch einen User im Forum ist bereits erfolgt.
Ziel ist es, SDM630, Lovato, mpm3pm hinter einem Elfin/Protos ModbusTCP Gateway mit eigendefinierter IP/Port/unit_id zu betreiben, ohne eine weitere Kopie des immer gleichen Sourcecodes zu machen.
@benderl: bitte auch testen …
> Flexible pv-kit Modules (Parameters)

- modules/bezug_powerwall/main.sh
sudo entfernt
2021-10-01 17:23:56: RET: 1 (LV2) at 22 main modules/bezug_powerwall/main.sh
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Debug = int(os.environ.get('debug'))
File "/var/www/html/openWB/modules/bezug_powerwall/powerwall.py", line 11, in <module>
https://openwb.de/forum/viewtopic.php?p=46739#p46739
> Bezug Powerwall fix

- modules/soc_evnotify/evnotify.py
- modules/soc_evnotify/main.sh
It looks like in the moment EVNotify integration with openWB [is broken](https://openwb.de/forum/viewtopic.php?f=9&t=4107). I have no idea why. I check the source code and if I try to imitate what it is doing locally it works fine.
However the current implementation does not give good log messages. Like what is the actual response from EVNotify? Was there maybe a non 2xx response?
This PR does not fix the underlying problem, but improves error logging if something is wrong. Hopefully it helps to identify the problem linked and other similar problems in the future.
Note that I only tested the code isolated in my stubbed development environment. It still needs to be tested on an actual system.
> Improve error logging if EVNotify SoC cannot be retrieved

- modules/soc_evnotify/main.sh
My previous PR #1602 does not work. Nothing is logged. I suspect that maybe on openWB `python` links to `python2`. However my script needs `python3`. At least I found that many other script explicitly call `python3`.
This PR changes that to also call `python3`. At the same time I also improved error logging further: In case the python-call fails, an error is logged as well.
> fix: call python3 instead of python and log error if call fails

- modules/soc_kia/kiaif.py
Der 12V-SoC wird nicht nur beim gecachten, sondern auch beim Live-Abruf nicht mehr übertragen.
> [Kia/Hyundai] - Hotfix 12V-SoC (Part 2)

- modules/soc_evnotify/evnotify.py
I got the feedback for my previous PR #1602 that it is not working for LP2. It took me quite a while, but I eventually found the source. The files for LP2 are: "soctimer**1**", "soc**1**" but configuration is "evnotifyakeylp**2**" and "evnotifytokenlp**2**". So I was writing to the SoC-file "soc2" instead of "soc1".
Also while fixing that I also use %g for logging SoC so that it looks better in the logs than %f and does not truncate fractions (like %d).
> fix soc evnotify for LP2 (was writing to wrong file)

- web/themes/EvenDarker/theme.html
- web/themes/Gauges/theme.html
- web/themes/colors/theme.html
- web/themes/dark/theme.html
Aufgrund der extrem teuren Strompreise wurde die obere Grenze des Sliders erneut angehoben.
> Erneute Anpassung max Preis für preisbasiertes Laden

- runs/pubmqtt.sh
Es geht um die Bereitstellung der Systemdaten per MQTT. Die Daten selber sind dabei identisch zum UI unter Einstellungen / System / System-Info.
Bisher wurden ähnliche Daten bereits unter verschiedene Pfaden veröffentlicht:
- openWB/system/Date
- openWB/system/IpAddress
- openWB/system/Uptime
- openWB/global/cpuTemp
Unter openwb/global werden die Informationen zur CPU, Speicher und SD-Karte ergänzt.
- openWB/global/cpuFreq
- openWB/global/cpuModel
- openWB/global/cpuUse
- openWB/global/memFree
- openWB/global/memTotal
- openWB/global/memUse
- openWB/global/diskFree
- openWB/global/diskUse
> Systeminfo per MQTT

- modules/goelp2/main.sh
- modules/goelp3/main.sh
Im Moment werden RFID Tags die an einem go-e Charger eingelesen werden nur verwendet, wenn es sich hierbei um den ersten Ladepunkt handelt.
Um den bzw. die Tag(s) auch einzulesen falls der oder die go-e Charger LP2 oder LP3 sind ist eine Anpassung der main.sh Dateien im jeweiligen modules Verzeichnis analog zum goelp1 notwendig.
Diese wurden mit diesem Request implementiert.
Getestet auf meiner openWB als LP1 sowie einem goe-Charger als LP2
> Check for RFID Tag on Go-e Charger also if it is second or third LP

- modules/et_tibber/stromtarifinfo/infopage.php
- modules/et_tibber/stromtarifinfo/stromtarifinfo_style.css
- modules/et_tibber/stromtarifinfo/tibberElectricityPricechart.js
- modules/et_tibber/stromtarifinfo/tibberHourlyConsumptionchart.js
- modules/et_tibber/tibber.js
Bisher war Tagesverbrauch nur für gestern abrufbar, jetzt kann Datum in Vergangenheit per Datepicker frei gewählt werden.
> Tibber-Stromtarifinfo: Datum für Ansicht Tagesverbrauch frei wählbar

- helperFunctions.sh
Currently the script in the "modules"-directory cannot use any of the useful shared libraries in the "packages"-directory without hassle. E.g. it would be useful for modules to use the new logging library by writing
```python
from helpermodules import log
log.MainLogger().debug("here is my debug message")
```
currently this is only possible by inserting the "packages"-directory to `sys.path` first. It would be easier if that would be the default.
This PR will add the packages path to `PYTHONPATH` in the helperFunctions.sh. Since that file is always sourced (so far as I can tell) that would make the modules in the "packages"-directory available globally without the need to fiddle with `sys.path` in any individual file that wants to use it.
> enable all python scripts to import from the "package"-directory without fiddling with sys.path individually

- modules/bezug_powerwall/powerwall.py
cookie file was always deleted due to false comparison of time diff
> fix powerwall typo

- web/settings/modulconfigbat.php
- web/settings/modulconfigpv.php
Da es bei der Kombi Plenticore + BYD anscheinend zu Problemen bei der korrekten Modul-Konfig kam, wurden die Hinweistexte in den Modulen angepasst.
> Hinweistexte BYD am Plenticore angepasst

- runs/updateConfig.sh
tibber settings were not always added to openwb.conf
> fix initial tibber config

- packages/helpermodules/compatibility.py
- packages/helpermodules/log.py
- packages/helpermodules/pub.py
- packages/modules/alpha_ess/bat.py
- packages/modules/alpha_ess/counter.py
- packages/modules/alpha_ess/device.py
- packages/modules/alpha_ess/inverter.py
- packages/modules/common/abstract_component.py
- packages/modules/common/abstract_device.py
- packages/modules/common/component_state.py
- packages/modules/common/lovato.py
- packages/modules/common/modbus.py
- packages/modules/common/module_error.py
- packages/modules/common/mpm3pm.py
- packages/modules/common/sdm630.py
- packages/modules/common/simcount.py
- packages/modules/common/simcount_test.py
- packages/modules/common/store.py
- packages/modules/openwb/counter.py
- packages/modules/openwb/device.py
- packages/modules/openwb/inverter.py
- packages/modules/openwb_flex/counter.py
- packages/modules/openwb_flex/device.py
- packages/modules/openwb_flex/inverter.py
Dieser PR behebt die folgenden Dinge über die `flake8` meckert:
```
packages/modules/openwb/inverter.py:8:1: E722 do not use bare 'except'
packages/modules/openwb/inverter.py:42:9: F841 local variable 'e' is assigned to but never used
packages/modules/openwb/device.py:9:1: E722 do not use bare 'except'
packages/modules/openwb/device.py:35:9: F841 local variable 'e' is assigned to but never used
packages/modules/openwb/device.py:60:9: E722 do not use bare 'except'
packages/modules/openwb/device.py:77:5: E722 do not use bare 'except'
packages/modules/openwb/device.py:101:5: E722 do not use bare 'except'
packages/modules/openwb/counter.py:9:1: E722 do not use bare 'except'
packages/modules/openwb/counter.py:45:9: F841 local variable 'e' is assigned to but never used …
```
> Fix style errors reported by flake8

- packages/helpermodules/log.py
- packages/modules/alpha_ess/bat.py
- packages/modules/alpha_ess/counter.py
- packages/modules/alpha_ess/device.py
- packages/modules/alpha_ess/inverter.py
- packages/modules/common/abstract_component.py
- packages/modules/common/abstract_device.py
- packages/modules/common/lovato.py
- packages/modules/common/modbus.py
- packages/modules/common/module_error.py
- packages/modules/common/mpm3pm.py
- packages/modules/common/sdm630.py
- packages/modules/common/simcount.py
- packages/modules/common/store.py
- packages/modules/openwb/counter.py
- packages/modules/openwb/device.py
- packages/modules/openwb/inverter.py
- packages/modules/openwb_flex/counter.py
- packages/modules/openwb_flex/device.py
- packages/modules/openwb_flex/inverter.py
Follow-up für #1695 ... Das war leider noch nicht ganz fertig. Einen Fehler habe ich noch gefunden.
Nämlich habe ich gerade noch gelernt, dass "attempted relative import beyond top-level package" ein `ValueError` und kein `ImportError` ist. Mysterious aus meiner Sicht, aber was will man machen.
Das sollte es jetzt hoffentlich gewesen sein. Nur mergen, wenn der automatische Check grün wird, sonst stimmt noch was nicht...
> Fix: Also catch `ValueError` when importing

- modules/bezug_powerwall/powerwall.py
- separate cookie files for shell and python skripts (maybe different format!)
- fix reading saved cookie from file
> fix bezug_powerwall cookie handling

- runs/mqttsub.py
Erlaube das Senden des PV Zählerstandes als kWh-Float (z.B. via Bluetooth von alten SMA-WR und/oder über SBFSpot).
Hierfür wird einfach ein weiteres Topic erstellt (kWhCounter). Die weitere Behandlung ist nicht notwendig, da in der Topicbehandlung direkt wieder zu Wh umgewandelt wird.
Notwendig analog zu #1338, da SBFSpot die Werte nicht vor dem Senden modifizieren kann.
> ermögliche das Senden des PV-Counters als kWh

- modules/smarthome/shelly/watt.py
Neu wird beim Shelly einmalig (pro reboot) die Version (Gen 1 oder Gen 2) abgefragt. Die Leistung und der Switchstatus sind bei Gen 2 von shelly anders übergeben.
> shelly plus und shelly in Smarthome

- packages/modules/common/modbus.py
Mit #1741 musste ein Bug gefixt werden, der hätte schon viel früher auffallen können, wenn es einen static-type check gegeben hätte.
Dieser PR fügt overloads hinzu, die lediglich dem type-checking dienen. Damit wäre der Fehler früher aufgefallen:
> ModbusClient: add overloads for reading methods for better type checking

- web/themes/dark/processAllMqttMsg.js
Lädt das Price Chart neu, wenn der maximale Preis auf einem anderen Screen, z.B. Display, geändert wurde. Farben werden damit jetzt korrekt angezeigt, wenn der Maxpreis auf dem Display geändert wurde.
> Fix for dark/standard theme: update pricechart on max price change

- .github/workflows/github-actions-python.yml
- modules/soc_evnotify/evnotify.py
- packages/helpermodules/exceptions/__init__.py
- packages/helpermodules/exceptions/registry.py
- packages/helpermodules/exceptions/registry_test.py
- packages/helpermodules/exceptions/requests.py
- packages/modules/alpha_ess/device.py
- packages/modules/common/component_context.py
- packages/modules/common/component_state.py
- packages/modules/common/fault_state.py
- packages/modules/common/store.py
- packages/modules/evnotify/EVNotify.py
- packages/modules/evnotify/EVNotify_test.py
- packages/modules/evnotify/api.py
- packages/modules/evnotify/api_test.py
- packages/modules/openwb/device.py
- packages/modules/openwb_flex/device.py
Passt EVNotify auf das neue Paketsystem an.
Anmerkungen:
- Ich bin immernoch unglücklich darüber, dass die Methode `AbstractDevice.get_values()` so heißt, wie sie es tut. Eine Methode die nichts zurückgibt sollte nicht mit `get` beginnen.
- Ich habe mir darüber Gedanken gemacht, wie es möglich ist die einzelnen Module vom Handling zu vieler kleiner Fehler zu bewahren. EVNotify bekommt seine Daten per HTTP wie viele andere Module auch. Es wäre unnötig, wenn jedes Modul die immer gleichen Fehlermeldungen fangen muss. Ein System was Exceptions global behandelt ist aber auch nicht ganz unkritisch, denn es besteht die Gefahr, dass es zu einem unkontrolliertem Monster anwächst. Ich habe hier in diesem PR einen Kompromiss angewandt und eine `ExceptionRegistry` gebaut. Das ist zwar auch eine …
> Refactor Evnotify auf das neue Paketsystem

- modules/soc_evnotify/main.sh
Da habe ich in der #1765 doch noch was falsch gemacht... Da ist noch ein Parameter zu viel, deswegen läuft EVNotify nicht. Im Log sagt es:
```
2021-12-03 20:13:36: Lp1: Calling python failed (1): unable to parse arguments. Expected: <akey> <token> <charge point>
ValueError: too many values to unpack (expected 3) (LV0)
akey, token, charge_point_str = sys.argv[1:]
File "/var/www/html/openWB/modules/soc_evnotify/evnotify.py", line 7, in <module>
```
Dieser PR behebt das... Hoffe ich ^^
> fixup for #1765: unused parameter "debug level" prevents evnotify from working

- modules/soc_manual/soc_manual.py
- packages/helpermodules/cli/__init__.py
- packages/helpermodules/cli/_run_using_positional_cli_args.py
- packages/helpermodules/cli/_run_using_positional_cli_args_test.py
Dieser PR fügt ein kleine Hilfsfunktion hinzu, die das parsen der CLI-args vereinfachen soll. Für das erste wird das ganze im SoC-Modul verwendet mit dem ich das ganze auch im Livebetrieb getestet habe.
Beispiel
-----------
Auszüge davon wie `packages/modules/openwb/device.py` aufgerufen wird:
modules/wr2_ethlovato/main.sh:
```bash
python3 ${OPENWBBASEDIR}/packages/modules/openwb/device.py "inverter" "${pvkitversion}" "2">>${MYLOGFILE} 2>&1
```
modules/speicher_mpm3pm/main.sh:
```bash
python3 ${OPENWBBASEDIR}/packages/modules/openwb/device.py "bat" "${speicherkitversion}" >>${MYLOGFILE} 2>&1
```
Man sieht hier die Anforderung: Es gibt 3 Argumente, das dritte ist Optional.
In Python selbst werden dann die Argumente wie folgt geparst:
```python
def read_legacy(argv: List[str]): …
```
> add automatic CLI args parser

- modules/speicher_fems/fems.py
- modules/wr_fems/fems.py
It seem pyhton 3.5 "re.search" only takes strings and does not do implicit conversion.
Errors in `openwb.log` were:
```
TypeError: expected string or bytes-like object
File "/var/www/html/openWB/modules/speicher_fems/fems.py", line 30, in write_ramdisk
if re.search("^[-+]?[0-9]+\.?[0-9]*$", value) == None:
File "/usr/lib/python3.5/re.py", line 173, in search
return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
File "/var/www/html/openWB/modules/wr_fems/fems.py", line 41, in <module>
if re.search(regex, pvwatt) == None:
File "/usr/lib/python3.5/re.py", line 173, in search
return _compile(pattern, flags).search(string)
```
> Fix FEMS broken by changes on Dec 10

- modules/wr_solaredge/main.sh
- modules/wr_solaredge/solaredgeall.py
- packages/modules/common/component_state.py
Da ich selber einen SolarEdge-WR habe ich mir mal den Code zu Gemüte geführt, der den SE-Wechselrichter abfragt. Also kleine "Vorbereitung" auf dann demnächst die Anpassung des Codes für die neue API habe ich den Code erstmal ordentlich aufgeräumt. Sonst blick ja niemand durch ;-).
Code ist jetzt runter von ursprünglich 237 Zeilen auf 72 Zeilen. Sollte sich aber inhaltlich genau so verhalten wie der alte auch.
Ich habe PR auf mehrere commits aufgeteilt, damit man die einzelnen Schritte die ich durchgeführt habe nachvollziehen kann.
Mein Wechselrichter hat allerdings eine ganze einfache Konfiguration. Keine Batterie, keine weiteren slaves... Wäre natürlich nicht falsch, wenn das jemand testen würde, der ein komplexeres Setup hat.
Und dann finde ich vielleicht noch raus, was die ganzen …
> Refactor SolarEdge: Clean-up code

- runs/atreboot.sh
- runs/cron5min.sh
- runs/pubmqtt.sh
I'd really like to see the git details also via MQTT.
This PR adds topics  
* `openWB/system/CommitHash`
* `openWB/system/CommitBranches`
In contrast to the display info of Web-UI (which takes the 'train' from `openwb.conf` file) this implementation takes all info from Git only. It first determines the last commit hash and then queries the **list of branches** that this hash can be found on. So watch out: Branch info might be a list!
The querying of the details runs on `atreboot.sh` and, just to be sure and safe, also in `cron5min.sh`.
> Send git details via MQTT

- modules/wr_kostalpiko/kostal_piko_var1.py
- modules/wr_powerwall/powerwall.py
- modules/wr_smartme/smartme.py
- modules/wr_solarlog/solarlog.py
- modules/wr_tripower9000/tripower.py
Nochmal so ein kleiner Schritt in Richtung schönerer Code, der sich leichter später zu oWB2 migrieren lässt.
Außerdem ist Smartme so wie es war nicht lauffähig, das habe ich noch gefixt.
Tripower dürfte so meines Erachtens auch nicht funktionieren, da hier noch `str.decode` aufgerufen wird (siehe auch [mein Kommentar hier](https://github.com/snaptec/openWB/pull/1578/files#r768052045).
Mir ist auch aufgefallen, dass sunways/sunwaves etwas völlig anderes tun als das alte Script. Ich gehe davon aus, dass die nicht funktionieren. Ich habe schonmal angefangen das neu zu implementieren, aber mir ist das Konstrukt suspekt: Ich finde im Internet keine Hinweise auf "sunwaves". "sunwayes" dagegen gibt es wirklich. Bis auf zwei Parameter, die möglicherweise Optional sind, sind die Skripte auch …
> Inverter Value Store verwenden

- modules/wr_solaredge/solaredgeall.py
- packages/modules/common/modbus.py
Scheint so als würde mein tolles neues SolarEdge-Modul (#1685) nicht richtig funktionieren, wenn eine Batterie angeschlossen ist. Nach nochmaligem genauen Studium des alten Codes glaube ich, dass es an der wordorder liegt, die bei Floats plötzlich Little Endian ist.
Wenn das so stimmt, dann würde dieser PR das Problem beheben. Im Forum habe ich einen betroffenen noch um einen Test gebeten, der noch aussteht: https://openwb.de/forum/viewtopic.php?p=52594#p52594
Außerdem habe ich ein paar Logausgaben hinzugefügt.
> fix endianness for SolarEdge battery values

- packages/modules/json/device.py
[Aus dem Forum](https://openwb.de/forum/viewtopic.php?p=52626#p52626):
> Das neue JSON Modul für PV funktioniert nicht mehr 
> ```
> 2021-12-16 13:44:53: PID: 3929: root: Json Wechselrichter: FaultState FaultStateLevel.ERROR, FaultStr Unbekannte PV-Nummer 1, Traceback:
> Traceback (most recent call last):
>   File "/var/www/html/openWB/packages/modules/json/device.py", line 65, in update
>     self._components[component].update(response)
>   File "/var/www/html/openWB/packages/modules/json/inverter.py", line 58, in update
>     self.__store.set(inverter_state)
>   File "/var/www/html/openWB/packages/modules/common/store/_inverter.py", line 27, in set
>     raise FaultState.from_exception(e)
>   File "/var/www/html/openWB/packages/modules/common/store/_inverter.py", line 20, in set
> …
```
> fix: component id must be a number, not string

- modules/soc_i3/index.php
As recommended by hint in [openWB forum](https://openwb.de/forum/viewtopic.php?p=52754#p52754) there's still a URL at which the old API can be accessed.
Additionally removed the debug output which confused the
JSON parsing in `main.sh`. That was another reason why no SOC could be shown even if API worked.
The changes are tested on LP 1 only.
> Switch to yet another URL for BMW API

- modules/wr_http/main.sh
- packages/modules/http/device.py
Problem ist mit issue #1833 beschrieben - http pv/wr modul funktioniert seit umstellung auf "packages" nicht mehr.
Mit diesen Änderungen geht es wieder - getestet auf meiner openWB mit HTTP PV Modul
> fix issue #1833 - wr_http: fix use http module from packages and convert pv-num to int

- packages/helpermodules/cli/_run_using_positional_cli_args.py
- packages/helpermodules/cli/_run_using_positional_cli_args_test.py
- packages/modules/http/device.py
Zwei Dinge:
1. Die Funktion `read_legacy` ist lang. Sehr lang. Ich finde die recht umständlich zu lesen und zu verstehen. Ich fände es schöner das ganze wäre unterteilt in kleine logische Funktionen mit passenden Parametern. Das habe ich in diesem PR gemacht. Dazu habe ich den CLI-Argument-Parser erweitert um die Funktionalität mehrere Kommandos zu unterstützen. Das hat nebenbei den auch hier wieder den netten Vorteil, dass man eine brauchbare Fehlermeldung bekommt, wenn mit den CLI-Argumenten was nicht stimmt.
2. Aktuell nimmt das Modul Protokoll+Domain von der ersten URL die ihm in die Hände gerät und von allen anderen URLs wird der Pfad einfach abgeschnitten, wohl in der Erwartung, dass das schon gleich sein wird. Wenn das mal abweichen sollte, dann kann die Fehlersuche schwierig …
> HTTP Module: Multi command CLI-Parser & URL validation

- modules/wr_tripower9000/main.sh
Wenn man logging aktiviert hat funktioniert das SMA-Modul nicht.
Kein Wunder: Der Output-Redirect für das Log fehlt. Ausgabe soll aber nur die Leistung sein und nicht das ganze log.
> fix SMA: add missing redirect for log output

- modules/soc_i3/index.php
- modules/soc_i3/main.sh
There seem to be cases of corrupt token file causing
```
thrown in /var/www/html/openWB/modules/soc_i3/index.php on line 66
#3 {main}
#2 /var/www/html/openWB/modules/soc_i3/index.php(260): Battery_API->__construct('1', 'meinBenutzername', 'meinPasswort', 'WBY8meineVIN')
#1 /var/www/html/openWB/modules/soc_i3/index.php(27): Battery_API->get_token()
#0 /var/www/html/openWB/modules/soc_i3/index.php(88): Battery_API->get_cached_token()
Stack trace:
PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/openWB/modules/soc_i3/index.php:66
thrown in /var/www/html/openWB/modules/soc_i3/index.php on line 66
#3 {main}
```
Though I cannot reproduce this case I've tested with various corruptions in file and missing file.
Adresses …
> Improve soc_i3 error handling

- modules/soc_i3/index.php
This should now really cover the `Cannot use object of type stdClass as array` error.
> Catch Throwable instead of Exception

- packages/modules/fronius/counter_sm.py
- packages/modules/fronius/device.py
- packages/modules/fronius/inverter.py
- packages/modules/fronius/meter.py
Nach der Umstellung auf die Fronius Pakete werden keine Daten des WR mehr in der Übersicht angezeigt.
Siehe https://openwb.de/forum/viewtopic.php?p=52700#p52700 und https://openwb.de/forum/viewtopic.php?p=53087#p53087.
Angepasst werden:
- Position des Zählers im Verbrauchszweig
- Bessere Fehlerbehandlung bei der Berechnung der PV-Erzeugung
> Fronius WR keine Daten bei Zähler im Verbrauchszweig

- runs/atreboot.sh
As the cron job runs as normal user `pi` it causes
```
/var/www/html/openWB/runs/cron5min.sh: Zeile 390: /var/www/html/openWB/ramdisk/currentCommitHash: Keine Berechtigung
/var/www/html/openWB/runs/cron5min.sh: Zeile 391: /var/www/html/openWB/ramdisk/currentCommitBranches: Keine Berechtigung
```
Added chmod 777, similar to other files, in atreboot.sh so the files
can be updated by cron job as regular user.
> chmod the git commit detail files of atreboot

- modules/bezug_smashm/main.sh
- modules/bezug_smashm/sma_em_measurement.py
- modules/bezug_smashm/sma_em_measurement_test.py
Mit diesem PR füge ich einen Unittest für den SMA Energy Meter hinzu. Genau genommen einen Test der prüft ob das Datagram korrekt dekodiert wird.
Das Ziel von dem PR ist es die Datei so wenig wie möglich anzufassen (weil sie funktioniert). Allerdings hat sich laut [diesem Thread im Forum](https://openwb.de/forum/viewtopic.php?f=9&t=4215) etwas geändert und der Test soll dabei helfen sicherzustellen, dass potentielle Fixes kompatibel sind mit dem SMA EM, der aktuell funktioniert.
Um Testdaten zu erzeugen habe ich folgendes Script geschrieben:
```python
import base64
import socket
import struct
ipbind = '0.0.0.0'
MCAST_GRP = '239.12.255.254'
MCAST_PORT = 9522
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, …
```
> Add test for SMA Energy Meter

- runs/mqttsub.py
- runs/smarthomehandler.py
- web/settings/smarthomeconfig.php
Im smarthomehandler wurde die Option  bei Autoladen... erweitert.
Neu gibt es drei Möglichkeiten:
a) nichts tun
b) Ausschaltschwelle anpassen
c) ausschalten / nicht einschalten
c ist die neue Möglichkeit a und b ist wie heute.
Diese Option (bei Auschaltschwelle anpassen oder auschalten/nicht einschalten) sorgt dafür, dass die aktuelle Leistungsaufnahme von diesem Gerät in den die Pv Überschussberechnung miteinbezogen wird. Wenn dann ein Auto geladen wird (> 1000 Watt Leistungsaufnahme),
wird bei Ausschaltschwelle anpassen: Die Ausschaltverzögerung auf 0 gesetzt und die Ausschaltschwelle (sofern eine Bezugsschwelle definiert ist) auf 0 gesetzt. Dadurch werden diese Geräte als erstes abgeschaltet, wenn das Auto lädt und der Überschuss nicht ausreicht.
wird bei ausschalten/nicht einschalten: …
> Bei Autoladen reduzieren / abschalten überarbeitet

- loadvars.sh
- modules/soc_evnotifys1/main.sh
- modules/soc_manuallp2/main.sh
Zwei Dinge gehe ich hier an. Die Hauptmotivation ist, dass es unschön ist, dass es jede Menge SoC-Module doppelt gibt. Das bläht das "modules"-Verzeichnis unnötig auf und sorgt für doppelten Code. In Vergangenheit hat das offensichtlich immer wieder dazu verleitet für die Unterstützung von einem 2. Ladepunkt einfach das Script vom ersten Ladepunkt zu kopieren und dann nur ein paar Pfade anzupassen. Bei den geschickteren Modulen gibt es im Verzeichnis für den LP2 ein Script welches mit Parameter auf das Script vom LP1 umleitet. Dennoch ist das wieder ein unnötiger weiterer Prozessstart und unnötig kompliziert zu verstehen.
Dieser PR ist ein erster Schritt dazu das zu ändern. Die niemand Lust auf einen Monster-PR hat in der alle Module sich plötzlich ändern muss das ganze aber …
> automatically detect SoC-Modules that support multiple charge points

- modules/soc_audilp2/main.sh
- modules/soc_carnetlp2/main.sh
- modules/soc_eqlp2/main.sh
- modules/soc_evcclp2/main.sh
- modules/soc_i3s1/main.sh
- modules/soc_idlp2/main.sh
- modules/soc_kialp2/main.sh
- modules/soc_leafs1/main.sh
- modules/soc_myopellp2/main.sh
- modules/soc_mypeugeotlp2/main.sh
- modules/soc_myrenaultlp2/main.sh
- modules/soc_psalp2/main.sh
- modules/soc_teslalp2/main.sh
- modules/soc_tronitylp2/main.sh
- modules/soc_vaglp2/main.sh
- modules/soc_volvolp2/main.sh
- modules/soc_zeronglp2/main.sh
- modules/soc_zoelp2/main.sh
Seit #1818 werden SoC-Module, die mehrere LPs unterstützen für den LP2 automatisch mit einem Parameter "2" aufgerufen. Die "Weiterleitungsskripte" werden nicht mehr gebraucht und werden von diesem PR entfernt.
> delete files obsolete thanks to #1818

- packages/modules/carlo_gavazzi/counter.py
Ich bin im Forum über [diesen Thread](https://openwb.de/forum/viewtopic.php?f=9&t=4499) gestolpert und habe den alten Code und den neuen Code verglichen. Aufgefallen ist mir, dass der alte Code Little-Endian-Word-order verwendet hat:
```python
all = format(resp.registers[1], '04x') + format(resp.registers[0], '04x')
```
Da der Codeausschnitt nicht sonderlich intuitiv ist: An der Stelle werden zwei aufeinanderfolgende Register Hex-encoded und dann die Hexwerte aneinander gefügt und später wird das Hex wieder geparst. Ein sehr komplizierter Weg, aber einer der funktioniert.
Wichtig dabei ist zu sehen, dass zuerst Register [1] und danach Register [0] genommen wird. Das entspricht der Little-Endian-Wordorder.
Wenn ich das so richtig interpretiert habe müsste der PR das Problem fixen. Ich habe …
> Fix extremely incorrect values for carlo gavazzi caused by incorrect word order

- modules/bezug_solaredge/main.sh
- modules/bezug_solaredge/solaredge.py
Motiviert dadurch, dass jemand [im Forum mit dem Modul Probleme hat](https://openwb.de/forum/viewtopic.php?p=53181#p53181).
Mit dem Fehler den der Nutzer da bekommt:
```
AttributeError: 'ExceptionResponse' object has no attribute 'registers'
value1 = resp.registers[0] 
File "/var/www/html/openWB/modules/bezug_solaredge/solaredge.py", line 19, in <module>
```
Kann man leider Debugtechnisch so gut wie garnichts anfangen.
Früher oder später sollte der garnicht schöne Bestandscode ohnehin überarbeitet werden, insofern ist hier der Umschrieb auf etwas moderner.
Getestet ist das ganze noch nicht. Ich selbst habe leider keinen SE-Modbuszähler.
> refactor SolarEdge EVU for readability and a step toward 2.0 compatibility

- runs/smarthomehandler.py
Falsche Einrückung führt dazu das die Geräte mit Autoladen ausschalten nicht richtig funktionieren.
Siehe auch
https://openwb.de/forum/viewtopic.php?p=53321#p53321
> Bei Autoladen abschalten Korrektur

- modules/speicher_solaredge/main.sh
- modules/speicher_solaredge/solaredge.py
Nachdem ich es schon mit dem WR-Modul von SolarEdge (#1685) und dem EVU-Modul (#1857) getan habe kenne ich mich jetzt mit SolarEdge aus und kann auch gerade noch das Batteriemodul nachziehen, als ein erster Schritt in Richtung 2.0-Modul.
So ganz viel kann eigentlich nicht schief gehen, da der Code doch recht einfach ist und ein erheblicher Teil einfach vom WR-Modul copy&paste ist, dennoch ist die Änderung so ungetestet, weil ich mangels Batterie keine Möglichkeit dazu habe.
> refactor SolarEdge battery module to use 2.0 style libraries

- modules/bezug_fronius_s0/main.sh
- modules/bezug_fronius_sm/main.sh
- modules/speicher_fronius/main.sh
- modules/wr_fronius/main.sh
- packages/modules/fronius/bat.py
- packages/modules/fronius/counter_s0.py
- packages/modules/fronius/counter_sm.py
- packages/modules/fronius/device.py
- packages/modules/fronius/inverter.py
- runs/updateConfig.sh
- web/settings/modulconfigevu.php
Nach der Umstellung auf die neue Paketstruktur für Fronius WR wurden im Forum Probleme gemeldet (https://openwb.de/forum/viewtopic.php?f=9&t=4489).
Dieser Pull Request enthält folgende Anpassungen:
- S0-Zählermodul liefert korrekte Daten
- Die absoluten Erzeugungswerte werden für S0-Zähler simuliert. Es wird die SimCount-Klasse benutzt, das ersetzt #1707.
- Der Kompatibilitätsmodus für die Primo Reihe wird als Standardmodus benutzt. Das ist etwas provokativ, aber im Forum habe ich keine Meldungen gefunden, wo der andere Modus jemals Daten geliefert hätte. Weiterhin ist der dahinterliegende Aufruf der Fronius SolarAPI so nicht korrekt. Die benutze Funktion 'GetPowerFlowRealtimeData' enthält den erfragten Parameter 'PowerReal_P_Sum' einfach nicht. Wenn die Rückmeldungen meine These …
> Anpassung Fronius mit S0 Zähler

- packages/modules/huawei/device.py
Im Forum [wird berichtet](https://openwb.de/forum/viewtopic.php?p=53077#p53077), dass Huawei kaputt ist. Dem Stacktrace nach zu urteilen und einem Vergleich aus altem und neuen Code liegt es daran, dass die modbus_id nicht als `int` sondern als `str` vorliegt. Wenn das alles ist, dann würde dieser PR das Problem beheben. Allerdings soweit genau null getestet.
> fix huawei: modbus_id must be an int

- packages/modules/fronius/device.py
Fix:
Die Konfiguration der IP-Adresse für einen 2. Fronius WR wurde in die Hauptdaten der WR-Komponente übernommen. Dadurch blieb die eigentlich Konfiguration weiterhin nicht konfiguriert.
Mit dieser Änderung wird die IP-Adresse an die richtige Stelle der Komponentenkonfiguration geschrieben.
> Fronius: handle WR2 ip-address as configuration

- .gitignore
- modules/bezug_discovergy/discovergy.py
- modules/bezug_discovergy/discovergy_test.py
- modules/bezug_discovergy/main.sh
- modules/soc_manual/soc_manual.py
- packages/modules/common/store/__init__.py
- packages/modules/common/store/_battery.py
- packages/modules/common/store/_car.py
- packages/modules/common/store/_counter.py
- packages/modules/common/store/_inverter.py
- packages/modules/common/store/ramdisk/files.py
- packages/modules/common/store/ramdisk/files_test.py
- packages/modules/common/store/ramdisk/io.py
Welche Dateien gibt es in der Ramdisk? Wie heißen die jetzt? Ob der LP1 eingesteckt ist steht in der Datei `plugstat`, ob LP2 eingesteckt ist in der `plugstats1` und ob LP3 eingesteckt ist in der `plugstatlp3`. Wo ist das System?
Muss in die Datei nun ein `int` oder ein `float`? Nimmt man ein `float` bei `wattbezug` zeigt das System garnichts mehr an. Nimmt man einen `int` bei der EVU-Stromstärke geht die Genauigkeit dramatisch den Bach runter.
Schön wäre es, wenn das ganze ordentlich dokumentiert wäre. Und zwar am liebsten im Code. So dass jeder verwendet, die Regeln durchgesetzt werden, die IDE einem direkt per Code-Completion vor die Auswahl stellt was geht und was nicht. Und das man nicht über die unterschiedlichen Muster der Dateinamen überhaupt nachdenken muss.
Dieser PR setzt genau …
> Ramdisk structure as Python-Code

- packages/modules/victron/counter.py
- packages/modules/victron/inverter.py
Spannungen sind in uint
Reg 789 liefert keine Daten, wenn keine Leistung vorhanden ist.
> Fix victron voltages, reg 789

- modules/speicher_powerwall/main.sh
- modules/speicher_powerwall/powerwall.py
- modules/speicher_powerwall/powerwall_test.py
- runs/atreboot.sh
- update outdated python3 urllib3 (root cause for SSL Error)
- add email to login form data (not verified, but used on login page, so add it to be compatible)
> fix powerwall login

- packages/modules/fronius/inverter.py
Die Zusatzwerte für den tagesaktuellen Zählerstand des WR sind nicht konstant, sondern ändern sich täglich.
Daher passen sie besser in den PV-Zweig zum eigentlichen Zählerstand.
Sie sind kein Teil der Konfiguration und können nur dynamisch ermittelt werden.
> Fronius: MQTT-Topics für Erzeugerwerte angepasst

- packages/modules/alpha_ess/bat.py
- packages/modules/alpha_ess/inverter.py
- packages/modules/carlo_gavazzi/counter.py
- packages/modules/fronius/bat.py
- packages/modules/fronius/counter_s0.py
- packages/modules/fronius/counter_sm.py
- packages/modules/fronius/inverter.py
- packages/modules/huawei/bat.py
- packages/modules/huawei/counter.py
- packages/modules/huawei/inverter.py
- packages/modules/janitza/counter.py
- packages/modules/json/bat.py
- packages/modules/json/counter.py
- packages/modules/json/inverter.py
- packages/modules/openwb_flex/counter.py
- packages/modules/powerdog/counter.py
- packages/modules/powerdog/inverter.py
- packages/modules/saxpower/bat.py
- packages/modules/siemens/bat.py
- packages/modules/siemens/counter.py
- packages/modules/siemens/inverter.py
- packages/modules/solax/bat.py
- packages/modules/sungrow/bat.py
- packages/modules/sungrow/counter.py
- packages/modules/sungrow/inverter.py
- packages/modules/victron/bat.py
- packages/modules/victron/counter.py
- packages/modules/victron/inverter.py
Analog zu PR #1868 werden auch die Simulationswerte des Simcounts unter dem Modul und nicht unter der Komponente abgelegt. (Änderung betriftt nur 2.x)
> simulation data in module get-topic

- modules/wr_kostalpikovar2/kostal_piko_var2.py
- modules/wr_kostalpikovar2/kostal_piko_var2_test.py
Der Wert "Gesamtenergie" vom Kostal var2 kommt in kWh. Muss dann wohl noch mit Tausend multipliziert werden. Mein Fehler.
Siehe auch [forum](https://openwb.de/forum/viewtopic.php?p=54436#p54436)
> fix kostal var2: Value received is in kWh, not Wh

- modules/wr2_ethlovatoaevu/main.sh
- modules/wr_ethmpm3pmaevu/main.sh
- packages/modules/openwb_pv_evu/device.py
Zum Zwecke der Performanceoptimierung (siehe #1837, #1838)
Außerdem `legacy_run` refactored für kürzer und leichter zu verstehen.
> use legacy run for openwb pv evu and refactor legacy_run function

- modules/wr_kostalpikovar2/kostal_piko_var2.py
- modules/wr_kostalpikovar2/kostal_piko_var2_test.py
Und was habe ich in #1872 noch vergessen? openWB erwartet, dass die PV-Leistung immer ein negativer Wert ist -.-
[Siehe Forum](https://openwb.de/forum/viewtopic.php?p=54611#p54611)
> fix kostal piko var2: PV power must be negative

- modules/sdm120modbusSocket/readsdm.py
Similar to the other values of that meter, there seem to be races in querying serial number.  
It's a one-shot action only if not already in ramdisk. Hence a pretty long sleep of 0.2s should be fine as it only occurs exactly once (after each boot).
Additional trace output showing the retrieved serial has also been added.
> Sleep before retrieving meter serial

- packages/modules/http/device.py
Wenn ein Port angegeben wird, wird dieser auch geparst.
Bugreport: [https://openwb.de/forum/viewtopic.php?p=54708#p54708](url)
> parse port in http module if given

- packages/modules/fronius/inverter.py
Reverts snaptec/openWB#1868
Nachvollziehbarer Gedankengang, allerdings kann in 2.x der Wert aus dem Modul-Topic nicht dem Device und der dazugehörigen Komponente zugeordnet werden.
> Revert "Fronius: MQTT-Topics für Erzeugerwerte angepasst"

- modules/bezug_discovergy/discovergy.py
- modules/bezug_discovergy/discovergy_test.py
Wie [im Forum berichtet](https://openwb.de/forum/viewtopic.php?f=9&t=4610) gibt es auch Zähler von Discovergy, die keine Spannung liefern. In diesem Fall entdeckt bei einem Zähler der 2019 installiert wurde.
Mit diesem PR funktionieren dann auch diese.
> fix: some discovergy meters do not report voltages

- packages/modules/fronius/counter_sm.py
- packages/modules/fronius/device.py
Die Meterlocation in der Komponentenkonfiguration muss im json-Format sein. Innerhalb der Komponente kann dann mit dem Enum gearbeitet werden.
> meterlocation enum only for internal use

- modules/wr_tripower9000/tripower.py
```python
data = {'RPC': '{"version": "1.0","proc": "GetPlantOverview","id": "1","format": "JSON"}'}
response = requests.post('http://' + address + '/rpc', json=data, timeout=3)
```
sollte das gleiche Ergebnis liefern wie
```
headers = {'Content-Type': 'application/json', }
data = {'RPC': '{"version": "1.0","proc": "GetPlantOverview","id": "1","format": "JSON"}'}
response = requests.post('http://' + address + '/rpc', headers=headers, data=data, timeout=3)
```
Das war offensichtlich nicht der Fall.
> fix requests headers and data

- modules/bezug_e3dc/e3dc.py
- modules/bezug_e3dc/main.sh
Das bestehende E3DC Bezugsmodul wurde auf V2 Syntax  umgestellt. Wie bisher wird 230 Volt angenommen und Ampere berechnet. Die Berechnung findet nur statt, wenn ein EVU Bezug vorliegt. 
Der Typ vom Leistungsmesser 6 (Modbusadresse 40129 -1) wird nicht mehr abgefragt (da immer 1). Modul ist mit meinem E3DC getestet
> E3DC Bezugsmodul auf  V2 Syntax umgestellt

- packages/helpermodules/log.py
This should resolve exceptions when log messages contain non ASCII characters.
> fix logging conversion asc/utf

- runs/cron5min.sh
Other scripts pause on Update/Reboot.
Cron5min was running while update are active.
These can cause problems.
Now the script do not run on Update
> Pause on Update or Reboot

- modules/bezug_smashm/main.sh
- modules/bezug_smashm/sma_em_measurement.py
- modules/bezug_smashm/sma_em_measurement_test.py
Ein weiterer Schritt in Richtung Kompatibilität für openWB 2: Die direkte Nutzung der Ramdisk für den EM fliegt raus und der `ValueStore` kommt rein.
Außerdem habe ich eine ganze Menge Code aufgeräumt. Offenbar vergessene Teile von irgendwann mal entfernt und generell alles übersichtlicher verkürzt. Auch die Versionshistorie habe ich entfernt (dafür ist git da).
Das ganze habe ich auch schon auf meine oWB aufgespielt und es liefert weiterhin plausible Daten.
> refactor SMA EnergyMeter / HomeManager module: Use ValueStore and clean-up code

- modules/bezug_fronius_s0/main.sh
- modules/bezug_fronius_sm/main.sh
- modules/speicher_fronius/main.sh
- modules/wr_fronius/main.sh
- packages/modules/common/fault_state.py
- packages/modules/fronius/bat.py
- packages/modules/fronius/counter_s0.py
- packages/modules/fronius/counter_sm.py
- packages/modules/fronius/device.py
- packages/modules/fronius/inverter.py
- runs/updateConfig.sh
- web/settings/modulconfigpv.php
Da bei einigen Fronius-Modulen keine oder falsche Zählerstände ausgegeben werden, wird in allen Fronius-Modulen simcount verwendet.
> Use simcount for fronius

- modules/bezug_smashm/main.sh
Wenn das Laden von Daten vom SMA HomeManager/EnergyMeter einen timeout erfährt, dann hinterlässt das keine eindeutigen Spuren im Log. Das ist bei der Fehlersuche unpraktisch. Daher ergänzt dieser PR eine Logausgabe.
> log it if fetching Date from SMA HomeManager/EnergyMeter times out

- runs/atreboot.sh
Schaut man aktuell direkt nach einem Reboot ins log steht dort:
```
File "/var/www/html/openWB/runs/mqttsub.py", line 15, in <module>
from modules.common.store.ramdisk import files
ImportError: No module named 'modules'
```
Das liegt daran, dass ich in #1879 das entsprechende Import hinzugefügt habe, das aber nur funktioniert, wenn `PYTHONPATH` korrekt gesetzt ist, was in `helperFunctions.sh` passiert. Diese Datei wird in der `atreboot.sh` aber nicht gesourced. Zunächst ist das nicht aufgefallen, da der 5-Minuten-Cronjob nach kurzer Zeit das Programm doch wieder startet.
> fix: mqttsub.py fails to start in atreboot.sh because PYTHONPATH is not set

- modules/bezug_huawei/main.sh
Im Forum beschwert man sich, dass [huawei EVU nicht geht](https://openwb.de/forum/viewtopic.php?f=9&t=4621).
Zumindest zeigt ein kurzer Blick auf die modules/bezug_huawei/main.sh, dass die Datei so mit Sicherheit nicht das tut, was der Autor im Sinn hatte. Getestet ist das zwar nicht, aber es kann nur besser werden :-).
> fix huawei counter values are not read by loadvars

- runs/mqttsub.py
Fixup für #1879: Das was ich da gebaut habe geht erst ab Python 3.6...
So sollte es jetzt auch mit 3.5 gehen.
> fix: '_sre.SRE_Match' object is not subscriptable before Python 3.6

- runs/mqttsub.py
openWB/pv/X/W liefert negative Ergebnisse für Produktion und openWB/pv/X/W hätte aber gerne positive Zahlen, damit man negative draus machen kann. *roll*
Siehe auch [forum](https://openwb.de/forum/viewtopic.php?p=55564#p55564)
> fix: openWB/set/pv/X/W Vorzeichenfehler

- packages/modules/alpha_ess/device.py
- packages/modules/carlo_gavazzi/device.py
- packages/modules/common/fault_state.py
- packages/modules/janitza/device.py
- packages/modules/openwb/device.py
- packages/modules/openwb_flex/device.py
- packages/modules/openwb_pv_evu/device.py
- packages/modules/powerdog/device.py
- packages/modules/siemens/device.py
- packages/modules/solax/device.py
- packages/modules/studer/device.py
- packages/modules/sungrow/device.py
- packages/modules/sunny_island/device.py
- arguments with class `Optional` still require a default value to be really optional
- for inverter components a `id` or `num` is mandatory
```
2022-01-18 19:53:24: PID: 1836: legacy run server: Received command ["modules.sungrow.device","counter","192.168.178.69","0"]
2022-01-18 19:53:24: PID: 1836: legacy run server: Unhandled exception
File "/var/www/html/openWB/packages/legacy_run_server.py", line 44, in redirect_stdout_stderr_exceptions_to_log
yield
File "/var/www/html/openWB/packages/legacy_run_server.py", line 83, in handle_connection
self.__callback(read_all_bytes(connection))
File "/var/www/html/openWB/packages/legacy_run_server.py", line 104, in handle_message
importlib.import_module(parsed[0]).main(parsed[1:])
File …
```
> provide default values for optional arguments

- loadvars.sh
- modules/bezug_e3dc/e3dc.py
- packages/modules/common/simcount.py
Simcount wird nun direkt im Bezugsmodul e3dc gelesen
Simcount für e3dc Bezug im Loadvars.sh entfernt
Simcount (SimCountFactory) für V2 persistiert nun korrekt die EVU Topics (Lösung mit @yankee42 erarbeitet), Zähler fing nach Reboot bei 0 an da er nur auf ganze Zahlen (nicht float) checkte
Dadurch sollte das Daily Excel wieder stimmen
> E3DC Bezug Anpassung V2 Korrektur

- packages/legacy_run_server.py
- runs/update.sh
Normalerweise kommt das Loglevel aus den environment-Variablen. Für den legacy-run-server werden diese jedoch nicht gelesen. Selbst wenn sie gelesen werden würden wäre das ein Problem, denn wenn jemand dann das Loglevel verstellt, würde diese Änderung im legacy-run-server niemals ankommen.
Mit diesem PR wird das Loglevel aus der openwb.conf ausgelesen und bei Änderung der Datei auch aktualisiert.
(Im Nachhinein frage ich mich, ob es nicht einfacher gewesen wäre in PHP beim Speichern einmal ein Script aufzurufen, welches das Loglevel auch im legacy-run-server verstellt... mhhh... Fällt mir spät ein. Immerhin hat die Lösung so wie sie jetzt ist den Vorteil, dass es auch funktioniert, wenn das Loglevel auf andere Art und Weise verstellt wird als durch die PHP-UI...)
> fix: legacy run server disregards configured log level

- packages/helpermodules/auto_str.py
- packages/modules/common/component_state.py
- packages/modules/common/store/_api.py
- packages/modules/common/store/_battery.py
- packages/modules/common/store/_counter.py
- packages/modules/common/store/_inverter.py
Mir wurde von @okaegi die Anregung zugetragen, ob man beim Speichern nicht mehr loggen könnte. Insbesondere hat er sich für den Zählerstand interessiert.
Ich habe da mal was gebaut. Bei mir sieht damit die Ausgabe wie folgt aus:
```
2022-01-21 10:26:25: PID: 26115: ValueStore: Saving InverterState(counter=10420500.0, currents=[0.75, 0.81, 0.88], power=-364.0)
2022-01-21 10:26:28: PID: 11123: ValueStore: Saving CounterState(currents=[-0.4007846556233653, 0.06142668428005284, 0.03372446762277271], imported=3202494.1745, power=-70.23, voltages=[229.4, 227.1, 230.1], exported=5513137.3984, frequency=50, powers=[-91.94, 13.95, 7.76], power_factors=[0, 0, 0])
```
So wie ich es gebaut habe kommt das Log auch in der Broker-Variante raus in der vorher garkeine Logausgaben waren. War das …
> when storing anything in a `ValueStore`, log the value

- packages/modules/sungrow/counter.py
- frequency and voltages for version 1 untested
- documented registers for power per phase do not provide valid numbers, so not activated
> sungrow counter: add frequency and voltages

- modules/wr_solarview/main.sh
- modules/wr_solarview/solarview.py
- runs/updateConfig.sh
- web/settings/modulconfigpv.php
This PR contains:
- A fix for a bug that was introduced when the original shell script was moved to python.
- The shell script [used the first argument as command](https://github.com/git-developer/openWB/blob/9c8c49cd52f1ad7cc022137ad08ebda14e01355e/modules/wr_solarview/main.sh#L143), defaulting to `00*`.
- The python module [uses](https://github.com/git-developer/openWB/blob/4583660fcf48468ad86c25af22461be0163b53d8/modules/wr_solarview/solarview.py#L161) the string `1:-00*`.
- A new feature to read a custom command from the configuration file, as requested [in the forum](https://openwb.de/forum/viewtopic.php?p=56018#p56018). This allows users to configure a single inverter as relevant for openWB, and not the whole plant.
The original contribution was …
> SolarView: Allow configuration of command

- packages/modules/victron/counter.py
Ich habe hier einen kleinen Bug beim Auslesen der Grid-Spannung von L3 gefixt (falsches Register) sowie das phasenweise Auslesen der Leistungen hinzugefügt.
> Victron module: Fixed register reading voltage L3 + added power reading per phase

- .gitignore
- packages/modules/common/simcount.py
- runs/simcount.py
relevant changes in commit [7bc2a2faaf027846239cebe2abde0a1c9ab7b2ef](https://github.com/snaptec/openWB/commit/7bc2a2faaf027846239cebe2abde0a1c9ab7b2ef)
Skipping first second results in incorrect calculation as we are calculating areas in a diagramm (integral). This step was only necessary in the old simcount under runs as that was a discrete calculation.
> SimCount Bugfix

- packages/modules/http/inverter.py
- web/settings/modulconfigpv.php
- accept inverter power as positive number in 1.x to not break existing installations
> http inverter: compatibility for 1.x

- packages/legacy_run.sh
Eigentlich war es so gedacht, dass (mit Ausnahme von den SoC-Modulen) keine Module parallel ausgeführt werden. Es könnte andernfalls zu Problemen kommen, weil dies parallele Dateizugriffe auf der Ramdisk zur Folge haben könnte (und oWB keine Locks verwendet). Oder zu Problemen führen, wenn [ein Modul paralelle Modbusverbindungen aufbaut](https://www.openwb.de/forum/viewtopic.php?p=56406#p56406).
Übersehen habe ich, dass `socat` schon per Standardwert einen timeout von 0.5 Sekunden hat, sobald einer der beiden Kommunikationskanäle zu ist. Damit ist für alle Befehler die >0.5 Sekunden brauchen nicht mehr gegeben, dass festgestellt werden kann, wann diese fertig sind.
Dieser PR behebt das in dem er den timeout auf 5 Minuten setzt. Es sollte kein Script geben, was ansatzweise in die Nähe …
> Legacy run server: Paralelle Ausführung mehrere Befehle verhindern

- packages/modules/openwb_pv_evu/device.py
PV an EVU Kit wurde mit falscher IP angesprochen, da eine falsche Basisklasse für den Inverter importiert wurde.
> fix imported inverter class for openwb_pv_evu

- packages/modules/huawei/bat.py
- packages/modules/huawei/counter.py
- packages/modules/huawei/inverter.py
Bei Huawei muss auch in openWB 1.x zwingend eine gemeinsame Modbus-Verbindung genutzt werden, da nach jeder neuen Verbindung 7 Sekunden auf den WR gewartet werden muss.
> huawei: do not close connection in components

- packages/helpermodules/skip_while_unchanged.py
- packages/helpermodules/skip_while_unchanged_test.py
- packages/legacy_run_server.py
Alternative zu #2003 und #1994
#2003 ist zu kompliziert.
Gegenüber #1994 hat dieser PR den Vorteil, dass sich die Logik bei unveränderter Bedingung einen Funktionsaufruf zu überspringen separat testen lässt. Potentiell mag das auch für anderen Code wiederverwendbar sein. Außerdem vermeidet es die unschöne globale Variable `debug_update_timestamp`. Die Datei `legacy_run_server.py` bzw. genauer die Funktionen `try_update_log_level_from_config` / `update_log_level_from_config` werden etwas kürzer und übersichtlicher. Im Gegensatz zu #1994 verwendet dieser PR einen Lock um zu verhindern, dass die Funktion mehrfach paralell ausgeführt wird. Gegenüber #1994 wird bei nicht erfolgter Aktualisierung wegen eines Fehlers beim Lesen der Datei (Datei ändert sich während sie gelesen wird o.ä.) dies …
> Legacy run server: fix "maximum recursion depth exceeded"

- runs/atreboot.sh
atreboot.sh: quotes missing in check for installed secrets.py
stretch: no impact
buster: missing quotes resulted on buster in fail, leading to unrequired enabling secrets locally in soc_vwid
> soc_vwid: atreboot.sh fix missing quotes

- modules/bezug_smashm/main.sh
- modules/smaemd_pv/main.sh
- packages/modules/common/component_context.py
- packages/modules/sma/counter.py
- packages/modules/sma/counter_test.py
- packages/modules/sma/device.py
- packages/modules/sma/inverter.py
- packages/modules/sma/speedwire_listener.py
- packages/modules/sma/utils.py
Ich habe bei mir gerade ein Update auf meiner Wallbox mit SMA Energy Meter als EVU-Zähler gemacht und dabei sind mir ein paar Probleme aufgefallen:
1. Es gibt keinen wirksamen timeout. Die alten Scripte `modules/bezug_smashm/main.sh` und `modules/smaemd_pv/main.sh` haben zwar noch einen timeout, aber die Wirkung davon ist nur begrenzt durchschlagend: Sie trennen die Verbindung zum legacy-run-server, aber beenden nicht das Script. Bei falsch konfigurierter Seriennummer heißt es dann "listening forever". Und jede Regelschleife kommt ein weiterer lauschender Thread hinzu.
2. Das Error-Reporting funktioniert nicht. Im `Device` wird ein `MultiComponentUpdateContext` und innerhalb dieses Context wird dann noch ein `SingleComponentUpdateContext`. Es ist nicht vorgesehen diese beiden Varianten zu …
> fix timeout and error reporting for speedwire devices

- web/settings/modulconfigpv.php
Seit https://github.com/snaptec/openWB/pull/1879 und https://github.com/snaptec/openWB/pull/1942 wird in der `mqttsub.py` nicht mehr der Betrag der gesendeten Leistung gebildet. Als Ergebnis muss die Erzeugungsleistung positiv gesendet werden.
> fix mqtt pv description

- web/settings/smarthomeconfig.php
Add note to all input fields, where a percent sign may be entered, to use "%%".
This is needed by the used config parser in smarthome 2.0.
> smarthome2: add info for "%" in urls

- web/status/processAllMqttMsg.js
Der Server macht sich die Mühe beim Versenden der FaultStrings diese zu JSON-encoden. Im Status auf der UI sieht man dann JSON encodierte Fehlermeldungen. Das ist garnicht so richtig schön. Vorallem wenn Umlaute darin vorkommen.
Mir fallen zwei Lösungen ein: Entweder die Daten nicht JSON encodieren (warum sollte man auch?) oder... was dieser PR macht: Die Daten auf dem client wieder dekodieren (unter der Annahme, dass hinter dem JSON-encode ein tieferer Plan steckt.).
> parse faultStr on the UI, so that the user does not need to read JSON encoded text

- packages/modules/common/modbus.py
- web/settings/modulconfigpv.php
Im Forum kommt immer mal wieder auf, dass bei SolarEdge Modbus standardmäßig auf Port 1502 läuft statt auf Port 502. Man muss dann den Solarteur beauftragen oder ein Ticket bei SE aufmachen, damit die den Port umkonfigurieren. Umständlich. Warum kann man nicht einfach den Port in der openWB ändern?
Dieser PR ändert das. Hier ein paar Beispiele was jetzt funktionieren sollte:
- IPv6: `[2a00:1450:4001:c01::67]`
- IPv6 mit Port: `[2a00:1450:4001:c01::67]:1502`
- IPv4: `173.194.35.7`
- IPv4 mit Port: `173.194.35.7:1502`
- Hostname: `solaredge.home`
- Hostname mit Port: `solaredge.home:1502`
Vor dem PR ging ausschließlich IPv4 ohne Port. (wobei die anderen Optionen ohne Port lediglich an der Valdierung auf der UI gescheitert und nicht daran, dass der Server es nicht gekonnt hätte)
> allow modbus port to be specified using the address

- packages/modules/common/modbus.py
Ich hätte in #2015 den Paramter `port` nicht umbenennen dürfen: Er ist Teil der API und Code der `ModbusClient("...", port=123)` verwendet funktioniert sonst nicht mehr. Sie auch [forum](https://openwb.de/forum/viewtopic.php?p=58771#p58771)
> fixup for #2015: port parameter must not be renamed

- packages/modules/sonnenbatterie/bat.py
strip more characters from response in `__read_variant_2`: `\n` and `\r`
> fix reading sonnenbatterie variant 2

- modules/bezug_powerwall/powerwall.py
- modules/speicher_powerwall/powerwall.py
- modules/wr_powerwall/powerwall.py
- packages/modules/common/powerwall.py
Wegen [diesen Forenthread](https://openwb.de/forum/viewtopic.php?f=9&t=4810) habe ich nochmal in das Powerwall-Script reingeschaut, dessen Batterieteil ich vor kurzem in #1817 überarbeitet habe.
Es werden natürlich alle möglichen HTTP-Responses in dem Modul geloggt, aber leider nicht die Response, um die es in dem Thread im Forum geht.
Allgemein ist der Code ist nicht mehr auf dem Stand der Technik. Dank #1823 gibt es die Möglichkeit automatisch zu loggen und auch die Fehlerekennung (`raise_for_status()`) automatisch zu machen und damit kann jede Menge Code entfallen.
Leider hatte der Code mit #1889 ein erhebliches Copy&paste-Erlebnis erlitten. Wenn man jetzt irgendwas irgendwo fixen will muss man das gleich 3x machen.
Ich habe daher den ganzen Code überarbeitet: Der Teil, der zwischen …
> refactor powerwall: de-duplicate code, use http-session with logging and automatic error detection

- web/settings/modulconfigpv.php
input element was initialized with "pvflexidold", has to be "pv2flexidold"
> fix typo modulconfigpv pv2flexid

- modules/bezug_rct/main.sh
- modules/bezug_rct/rct.py
- modules/bezug_rct/rct_read.py
- modules/speicher_rct/main.sh
- modules/wr_rct/main.sh
Seems that the rct2 modules cannot comlete replace the old rct modules.
So we keep the old version for compatibility.
> restore old rct module

- modules/speicher_bydhv/byd.py
- modules/speicher_e3dc/e3dc.py
- modules/speicher_solaredge/solaredge.py
Das loadvars-Skript setzt eine Fehlermeldung für die Statusseite, wenn die Batterie-Abfrage zu lange dauert. Diese Meldung wurde nicht zurück gesetzt.
> remove battery timeout error message

- modules/soc_tesla/tesla.php
The token file is created from inside apache and only writeable for this user. The token refresh is run inside the main loop from another user. So the token file needs to be writeable for other users.
> soc tesla - fix file permissions

- runs/mqttsub.py
Wiederherstellung der Kompatiblititat zu <1.9.25x
Wenn, wie vorher, negative Zahlen per MQTT  eingeliefert werden,  dann werden die akzeptiert. 
Meine MQTT Quell kann die 1.9'er nicht unterscheiden und liefert immer Negative Zahlen ein.
> Update mqttsub.py pv/W

- runs/cron5min.sh
- runs/initRamdisk.sh
- runs/mqttsub.py
- runs/smarthomehandler.py
- runs/smarthomemq.py
- runs/usmarthome/smartacthor.py
- runs/usmarthome/smartavm.py
- runs/usmarthome/smartbase.py
- runs/usmarthome/smartelwa.py
- runs/usmarthome/smarthttp.py
- runs/usmarthome/smartidm.py
- runs/usmarthome/smartmqtt.py
- runs/usmarthome/smartmystrom.py
- runs/usmarthome/smartshelly.py
- runs/usmarthome/smartstiebel.py
- runs/usmarthome/smarttasmota.py
- runs/usmarthome/smartviessmann.py
- web/settings/smarthomeconfig.php
- web/settings/topicsToSubscribe_smarthomeconfig.js
Erste Version vom Smarthomehandler MQ. Dieser liest alle Parameter nur noch aus MQ, nicht mehr aus dem Smarthomeconfig.ini
In den Smarthomesettings 2.0 hat es neu einen Parameter, mit dem man auswählen kann ob der bisherige Smarthomehandler oder der Smarthoemhandler MQ laufen soll. Diese Parameter wird nur vom Cron5min Job angefragt, d.h. unter 1.9 wird zuerst der bisherige Smarthomehandler gestartet und dann ggf beendet und dann der Smarth MQ gestartet. Der Smarthome MQ wird sowohl unter 1.9 und unter 2.0 (gleiche Codeline) laufen
> Smarthome MQ

- modules/wr2_ethlovatoaevu/main.sh
- modules/wr2_kostalsteca/kostal_steca.py
- modules/wr2_kostalsteca/main.sh
- modules/wr2_solax/main.sh
- modules/wr2_sungrow/main.sh
- modules/wr2_victron/main.sh
- some main.sh referenced "pvwatt" but should use "pv2watt"
- fix shellsheck warnings
- fix flake8 and pylint warnings
> fix typos in wr2 modules

- web/themes/colors/theme.html
Wie im Forum besprochen, musste das Eingabefeld für RFID-Codes unter den 70%-Button verschoben werden.
> Colors theme fix: Move Code button to bottom of modal

- modules/soc_vwid/main.sh
Avoid recording normally useless idle messages in EV-SOC log.
This will show a much longer history of SOC request cycles.
In debug level 2 idle log entries will still be recorded.
> soc_vwid: change level for idle log entries from 0 to 2

- modules/bezug_solax/main.sh
- modules/speicher_solax/main.sh
- modules/wr2_solax/main.sh
- modules/wr_solax/main.sh
- packages/modules/solax/bat.py
- packages/modules/solax/counter.py
- packages/modules/solax/device.py
- packages/modules/solax/inverter.py
- web/settings/modulconfigpv.php
Solax gen4
Bestehnden Solax gen3 Treiber angepasst. Als zusätzliches Eingabefeld wird neu Modbus ID verlangt. Gen4 verlangt hier ein Wert, gen3 sollte mit 0 laufen
> solax gen4

- helperFunctions.sh
- runs/atreboot.sh
Im Moment kommen Ausgaben, die aus der `atreboot.sh` kommen ohne timestamp und ohne eine Info, die Rückschlüsse darauf lässt, dass der Output aus der atreboot.sh kommt ins Log gespült.
Das ist zum Beispiel ärgerlich wenn man sowas hat wie [das hier im Forum](https://openwb.de/forum/viewtopic.php?p=59232#p59232). Ausschnitt:
```
rozess gefunden
echo: write error: Broken pipe
load versions...
```
Wo das "load versions" herkommt lässt sich noch eindeutig auf die atreboot.sh zurückführen. Aber was ist mit den anderen beiden Ausgaben. Die kommen die daher? Oder ist das Script längst abgebrochen und die Ausgaben kommen ganz woanders her?
Warum ist das Script überhaupt abgebrochen? Kam es zum 5-Minuten-timeout? Wahrscheinlich nicht, dann hätte "update in progress" verschwinden sollen. Dennoch …
> when running atreboot.sh, log all output to debug-log including timestamp and fixed string "at_reboot"

- goecheck.sh
Passiert, sobald der Ladepunkt deaktiviert wird (bspw. wie bei mir automatisch nach Erreichen eines gewünschten SOC via PV-Laden) oder nicht mehr genügend Überschuss vorhanden ist. Dann geht der Soll-Ampere-Stand (llsoll) auf 0. Dadurch passt er nicht mit dem Minimum bei go-e einzustellendem 6 Ampere zusammen => es wird der Soll-Ampere mit 0 gesendet und go-e setzt seinen minimal Ampere-Wert (6A). Das wiederholt sich dann bei jedem Zyklus => go-E blinkt ständig.
Siehe auch:
https://openwb.de/forum/viewtopic.php?p=60707#p60707
> Go-e: Kein triggern der API wenn Soll-Max-Ampere (llsoll) Null ist

- web/settings/executeupdate.php
- web/settings/saveupdate.php
- web/settings/updatePerformNow.php
GET Requests sollten keine Seiteneffekte haben. Browser schützen vor Situationen in denen Seiteneffekte durch versehentliches Auslösen von anderen Requestarten ausgelöst werden (Verwendung des Zurück-Buttons im Browser, aber auch Anklicken von Links oder auch böse cross-site Angriffe).
Das Update in openWB wird per GET ausgelöst. Das ist schlecht, denn es produziert einen erheblichen Seiteneffekt. Es sollte per POST gehen.
Mit diesem PR baue ich das so um, dass Updates per POST ausgelöst werden.
**DAS IST UNGETESTET!!!** (Ja ich denke ich sollte allmälich nach SSH fragen, damit ich sowas testen kann).
**!!!!!!!!!!!**
Wenn es nicht funktioniert, dann kann man auch kein weiteres Update machen um es zu beheben. **Daher muss das vor einem merge unbedingt jemand testen (!!!!)** …
> update with HTTP Post only

- modules/soc_vwid/soc_vwid.py
Problem was reported a few times now - should be improved.
When open of reply file fails, "sudo rm reply file" and open it once more
> soc_vwid: catch and handle permission error on open of reply file

- modules/smarthome/shelly/off.py
- modules/smarthome/shelly/on.py
- modules/smarthome/shelly/watt.py
- runs/mqttsub.py
- runs/usmarthome/smartbase.py
- runs/usmarthome/smartmeas.py
- runs/usmarthome/smartshelly.py
- web/settings/smarthomeconfig.php
- web/settings/topicsToSubscribe_smarthomeconfig.js
Neu wird die Kanalwahl für Shellies unterstützt. Im Gui kann ausgewählt werden:
a) Auf welchem Kanal das on/off Kommando geschickt wird.
b) Welcher Meter ausgelesen werden soll
Zusätzlich gibt es aus Kompatibilitätsgründen das bisherige Verhalten (alle Meter addieren, On / Off auf Kanal 0 senden) als Auswahloption.
Programme an flake8 angepasst
> smartmq Kanalwahl für Shellies

- modules/bezug_kostalpiko/kostal_piko.py
Ich habe gerade mal in den Code geschaut.
'dxsEntries', ['33556736', '251658753', '83887106', '83887362', '83887618']
Hier scheint mir der erste Wert falsch zu sein. Hier sollte '67109120' stehen. Das wäre dann der "GridAC" und somit zumindest meiner Meinung nach der richtige Wert. Es hilft ja nichts zu wissen, was die Panales liefern. Der Output des Wechselrichters ist für uns interessant, oder?
-Total DC input [W][double] --> http://192.168.178.21/api/dxs.json?dxsEntries=33556736
-Output power [W][double] --> http://192.168.178.21/api/dxs.json?dxsEntries=67109120
> Update kostal_piko.py to Output power

- modules/bezug_kostalpiko/kostal_piko.py
Ergänzung zu PR #2235: Wenn ein Hybrid-System vorhanden ist, muss noch die Batterieentladeleistung von der WR-Leistung subtrahiert werden. Bisher wurde in diesem Fall die DC-Ausgangsleistung des WR verwendet, was zu Ungenauigkeiten führt.
> support for kostal piko hybrid systems

- web/settings/setPassword.php
Escape user-provided input (`$_POST['username']`) so that a shell command injection is no longer possible.
> Prevent shell command injection

- runs/smarthomemq.py
- runs/usmarthome/global0.py
- runs/usmarthome/smartacthor.py
- runs/usmarthome/smartavm.py
- runs/usmarthome/smartbase.py
- runs/usmarthome/smartbase0.py
- runs/usmarthome/smartbut.py
- runs/usmarthome/smartelwa.py
- runs/usmarthome/smarthttp.py
- runs/usmarthome/smartidm.py
- runs/usmarthome/smartmeas.py
- runs/usmarthome/smartmqtt.py
- runs/usmarthome/smartmystrom.py
- runs/usmarthome/smartshelly.py
- runs/usmarthome/smartstiebel.py
- runs/usmarthome/smarttasmota.py
- runs/usmarthome/smartvampair.py
- runs/usmarthome/smartviessmann.py
Neu werden beim ReRead und dem Start alle gelesenen mqtt Parameter protokolliert und validiert. Dazu wird die Datei smartcon.log erstellt, welches nur die Config parameter enthält. Der Startup wurde leicht geändert, um dem null (alle config Parameter weg) Problem auf die Spur zu kommen. Aus jetziger Sicht läuft zu viel parallel auf dem mqtt Broker so dass nicht innert 5 Sekunden alle smarthome parameter gelesen werden können.
> logging/validierung von mqtt  parameter

- packages/modules/sma_modbus_tcp/inverter_modbus_tcp.py
Merge of 2245-sma-hybrid contained a duplicated else statement that causes a misleading exception with non-hybrid SMA inverters. This PR simply removes the else statement on line 86 that was mistakenly copied from line 53.
> Fix duplicated else causing misleading exception

- modules/speicher_sbs25/main.sh
- packages/modules/sma_sunny_boy/bat_smart_energy.py
- packages/modules/sma_sunny_boy/device.py
- web/settings/modulconfigbat.php
- web/settings/modulconfigpv.php
Sunny Boy Smart Energy liefert keine Lade-/Entladeleistung. Diese muss aus Batteriestrom und -spannung berechnet werden.
> sunny boy smart energy

- packages/modules/solaredge/bat.py
- packages/modules/solaredge/counter.py
- packages/modules/solaredge/device.py
- packages/modules/solaredge/external_inverter.py
- packages/modules/solaredge/inverter.py
Fix zu [https://openwb.de/forum/viewtopic.php?p=67867#p67867](https://openwb.de/forum/viewtopic.php?p=67867#p67867)
Das Auslesen der WR-Daten in Z.244 funktioniert, die Speicherdaten in Z. 255 sind ohne Timeout nicht abfragbar.
> fix solaredge modbus contextmanager

- modules/wr2_solarmax/main.sh
- packages/modules/solarmax/inverter.py
- web/settings/modulconfigpv.php
Solarmax wird nun auch als zweiter Wr unterstützte PV Leistung wird als uint 32 ausgelesen...
> Solarmax 2 , pv leistung als unit32 lesen

- modules/soc_vwid/main.sh
- modules/soc_vwid/soc_vwid.py
Current approach forces a new login in the VW Servers on each inquiry of the SOC.
This may cause a reaction on VW side in form of additional measures to make programmatic access from non-VW clients more difficult.
The unrequired login also costs about 50% of the total runtime.
Each login returns a new set of tokens.
The PR stores the tokens to a file in ramdisk (soc_vwid_tokensX (X=number of Ladepunkt).
On each query the tokens file is restored to the tokens in the vwid object and the tokens are reused until they become invalid.
If invalid the new tokens are stored in the file.
Tests done:
- Run without existing tokens file: works, SoC is returned, new file is created.
- Run with existing and valid tokens file: works, SoC is returned
- Run with existing but invalid tokens file: SoC is …
> Socvwid p7

- runs/upgradeChargeLogs.py
- charge log entries before 03/2020 had no rfid tag and were not upgraded as the expected row length did not match
- add case to upgrade rows with 8 values
- do not break after first row matches new length of 10 values to also upgrade already partial modified files
> add charge log upgrade for data before 3/2020

- openwb-install.sh
- runs/update.sh
Ich habe vor kurzem ein Update meiner openWB auf die aktuelle Nightly gemacht. Jetzt fällt mir auf, dass der Verbrauch meiner Klimaanlage nicht mehr angezeigt wird. Im smarthome-log finde ich:
```
2022-07-21 11:06:39: EVU Bezug(-)/Einspeisung(+): 225 max Speicherladung: 0
2022-07-21 11:06:39: Uberschuss: 225 Uberschuss mit Offset: 225
2022-07-21 11:06:39: Speicher Entladung(-)/Ladung(+): 0 SpeicherSoC: 100
2022-07-21 11:06:39: (1) Leistungsmessung durch sdm120
File "/var/www/html/openWB/modules/smarthome/sdm120/sdm120.py", line 31, in <module>
f1 = open('/var/www/html/openWB/ramdisk/smarthome_device_ret' + str(devicenumber), 'w')
PermissionError: [Errno 13] Permission denied: '/var/www/html/openWB/ramdisk/smarthome_device_ret1'
2022-07-21 11:06:40: …
```
> do not run atreboot.sh as root

- packages/modules/sma_sunny_boy/inverter.py
Mir ist zufällig aufgefallen, dass bei SMA in der Klasse SmaSunnyBoyInverter in [Zeile 42](https://github.com/snaptec/openWB/blob/a7dc53d7665257dfac1baeaf881d07c894021b8e/packages/modules/sma_sunny_boy/inverter.py#L42) und in [Zeile 47](https://github.com/snaptec/openWB/blob/a7dc53d7665257dfac1baeaf881d07c894021b8e/packages/modules/sma_sunny_boy/inverter.py#L47) ein Wert für `energy` per Modbus ausgelesen wird, dieser Wert jedoch nie verwendet wird. Stattdessen wird der Wert in [Zeile 63](https://github.com/snaptec/openWB/blob/a7dc53d7665257dfac1baeaf881d07c894021b8e/packages/modules/sma_sunny_boy/inverter.py#L63) von einem anderen Wert ersetzt.
Reingekommen ist die Zeile 63 durch #2245 (@JanFellner).
Grob geschätzt würde ich sagen dass der Core2 jetzt kaputt ist und die Zeile 63 …
> fix SMA Inverter: energy is read via modbus twice, first requested value is ignored

- rfidtag.sh
The status "valid tag for EV charge" has been accidentially overwritten by later check against standard socket tag.
Now check for standard socket tag is completely skipped if a valid EV charge tag has been found.
> Fix YC display of EV activation when standard socket is present

- rfidtag.sh
Need this fix also in `yc/stable`.
FYI: Update of `yc/...` branches to latest openWB release is planned later this year.
> yc/stable: Fix YC display of EV activation when standard socket is present

- runs/atreboot.sh
atreboot process should be killed after setting status flags or we will kill ourselfe before resetting
> fix killing stalled atreboot.sh

- packages/helpermodules/auto_str.py
- packages/modules/openwb_evu_kit/device.py
Kleinigkeiten:
- Bei 2 Modulen fehlte die `__init__.py`
- In der `packages/modules/openwb_evu_kit/device.py` steht eine Type-annotation an der falschen Stelle
- In der `packages/helpermodules/auto_str.py` fehlt eine Type-Annotation für einen Return-Type.
> add missing __init__.py and fix type annotations

- modules/extopenwb/main.sh
- modules/extopenwblp1/main.sh
- modules/extopenwblp2/main.sh
- modules/extopenwblp3/main.sh
- modules/extopenwblp4/main.sh
- modules/extopenwblp5/main.sh
- modules/extopenwblp6/main.sh
- modules/extopenwblp7/main.sh
- modules/extopenwblp8/main.sh
- runs/isss.py
- fix shellcheck warnings in extopenwb module
- fix detecting rfid null tag in `isss.py`
> fix rfid null tag

- packages/helpermodules/exceptions/registry_test.py
> For example, the following file system layout defines a top level parent package with three subpackages:
> ```
> parent/
>     __init__.py
>     one/
>         __init__.py
>     two/
>         __init__.py
>     three/
>         __init__.py
> ```
https://docs.python.org/3/reference/import.html#regular-packages
In unserem Fall heißt es `packages` und nicht `parent`. Dadurch gibt es ein Paket mit dem Namen `packages`. Das führt dazu, dass alle Klassen in zwei Paketen vorkommen. Folgende Zeilen funktionieren *beide*:
```python
from packages.modules.alpha_ess.config import AlphaEssBatSetup
from modules.alpha_ess.config import AlphaEssBatSetup
```
Das ist nicht gewollt. Der Ordner `packages` enthält Pakete, ist aber selbst kein Paket. Daher muss die `__init__.py` da weg.
> remove top-level `__init__.py` (directory "packages" is not a package - it contains packages)

- runs/atreboot.sh
- runs/update.sh
In #2328 schrieb @DetMoerk:
> Seit der Anpassung treten Fehler beim Update auf. Die Version wird nicht mehr aktualisiert und teilweise können Verzeichnisse nicht gelöscht werden.
Werden der pkill und die beiden Git Zeilen per sudo aufgerufen, funktioniert es wieder. Fehler sind in der /var/log/apache/error.log zu finden!
Ich bin dem nachgegangen. Im Log fand ich:
```
pkill: killing pid 7405 failed: Die Operation ist nicht erlaubt
error: unable to unlink old 'web/backup/.donotdelete': Keine Berechtigung
error: unable to unlink old 'web/tools/upload/restore.log': Keine Berechtigung
error: unable to unlink old 'web/tools/upload/uploaddir': Keine Berechtigung
Checke Dateien aus: 100% (1277/1277), Fertig.
fatal: Konnte Index-Datei nicht zu Commit 'origin/master' setzen.
[Tue Aug 09 …
```
> fix permissions for backup dir, fix wrong positive error message from pkill

- loadvars.sh
Da stand mal -gt  also  "greater-then"  also ">"  nicht ">="
So hat das Display schlaflose nächte und das Pushover läuft über
> lasse das display wieder einschlafen.

- packages/modules/sma_sunny_boy/device.py
- packages/modules/sma_sunny_boy/inverter.py
- packages/modules/sma_sunny_boy/sma_sunny_boy_test.py
Nur wenn der WR DC-seitig Leistung liefert, darf die WR-Leistung um die Speicher-Leistung reduziert werden. Andernfalls beträgt die WR-Leistung 0W.
Getestet mit einem Sunny Boy Smart Energy.
> fix sma smart energy power

- packages/modules/http/api.py
Zufällig ist mir im HTTP-Modul merkwürdiges aufgefallen:
- Die Funktion `request_value` sagt:
```python
if "none" == url:
return None
```
Aber diese Funktion wird niemals mit "none" aufgerufen. Der einzige Ort von dem aus die Funktion aufgerufen wird ist aus `create_request_function`. Diese überprüft den Pfad bereits vor dem Aufruf. Denkbar wäre lediglich dass jemand zum Beispiel `create_request_function("No", "ne")` aufruft. Aber der Fall erscheint mir eher abwegig. Insofern ist dieser Test unnötig und das Ergebnis ist immer garantiert ein `float` und niemals `None`.
Das `if` ist seit #1832 unnötig. Da habe ich wohl übersehen das `if` zu entfernen.
In #2200 bzw. genau genommen in commit af6b1dc779e8eafaf5dfdd7e0b5e5bb77560aa44 kam die Änderung rein, dass die Funktion `None` statt `0` …
> fix: `request_value` is never called with "none", result is always float

- modules/smarthome/acthor/watt.py
- runs/mqttsub.py
- runs/usmarthome/smartacthor.py
- runs/usmarthome/smartbase.py
- runs/usmarthome/smartbase0.py
- web/settings/smarthomeconfig.php
- web/settings/topicsToSubscribe_smarthomeconfig.js
Um den Supportaufwand zu reduzieren, wird neu im smarthomelog bei den Geräten die mit Überschuss aus openWB versorgt werden eine zusätzliche Meldung geschrieben wenn ein Modbuswrite statgefunden hat. 
2022-09-15 17:46:38,186 INFO (2) Actest rel: 1 oncnt/onstandby/time: 14/0/23893 Status/Üeb: 10/1 akt: 40 Z: 0 2022-09-15 17:46:38,183 INFO (2) Gerät wurde upgedatet, neue Vorgabe 530 Periode 32
Die Periode ist die Zeit zwischen zwei Updates. Die Vorgabe ist der Betrag der übertragen wurde. Diese ist je nach Gerätetyp mal der Überschuss , oder die Sollleistungsaufnahme. Zusätzlich kann als Parameter neu pro Gerät eine Anzahl Sekunden eingegeben werden, nachdem eon Gerät upgedatet wird (Feld Periode). Wird in den Einstellungen 0 Sekunden erfasst, kommt die Defaultregelung von Openwb zum …
> Acthor besseres Loging

- modules/bezug_siemens_sentron/main.sh
- packages/modules/siemens_sentron/config.py
- packages/modules/siemens_sentron/counter.py
- packages/modules/siemens_sentron/device.py
- web/settings/modulconfigevu.php
Currently, Siemens SENTRON (7KM PAC2200) energy meters can be used in the EVU module of openWB by choosing the generic JSON module and parsing the power/import/export values from the energy meter's webpage data URLs. However, this is limited to measuring only the basic EVU values and also has the unnecessary performance overhead of HTTP and JSON parsing.
This commit introduces a custom implementation for these energy meters. It reads all EVU values openWB can process directly from the energy meter via Modbus/TCP. Users only have to enter the meter's IP address.
This implementation has been tested in my home installation. All values correspond to the ones displayed in the meter's webpage and no performance issues for running the control loop could be detected.
> add support for Siemens SENTRON (7KM PAC2200) measuring devices

- packages/modules/lg/device.py
- packages/modules/lg/lg_test.py
If the auth_key is not valid, the device returns http status 405. The session object checks this and throws an HTTPError and we have no chance to update the auth_key. So catch the HTTPError and try to authenticate again with password.
> lgess: catch http error on failed auth

- web/themes/colors/powergraph.js
Wie im Forum besprochen war die Darstellung des Hausverbrauchs im Daily Graph nicht korrekt, wenn Smart Home Devices verwendet werden. Das sollte jetzt korrekt funktionieren.
> Fix dailygraph display

- packages/dataclass_utils/_dataclass_from_dict.py
- packages/dataclass_utils/_dataclass_from_dict_test.py
Auf der Suche nach der Ursache des [hier beschriebenen Problems mit dem HTTP Modul](https://openwb.de/forum/viewtopic.php?p=71902#p71902) ist mir aufgefallen, dass die Funktion `dataclass_from_dict` offenbar nicht damit klar kommt, wenn eine Klasse von einer anderen Klasse ableitet, die ein Generic hat. Daher wird in dem Beispiel die Klasse `HttpCounterSetup` nicht korrekt erzeugt und nix geht.
Ich konnte das Problem mit einem einfachen Test nachbilden und auch fixen. Im Bezug auf HTTP ist das mit #2289 reingekommen, welcher bereits am 14.07., also vor über 2 Monaten gemergt wurde. Ich bin etwas irritiert davon, dass das erst jetzt auffällt. Hat es wirklich niemand gemerkt oder übersehe ich da noch etwas??
> fix: from_dict does not work on classes that extend classes with generic

- runs/mqttsub.py
- web/settings/modulconfigevu.php
add  missing topics in evu mqtt.
openWB/set/evu/HzFrequenz oder openWB/set/evu/Hz Netzfrequenz in Hz, float, Punkt als Trenner
openWB/set/evu/WPhase1 Leistung in Watt für Phase 1, float, Punkt als Trenner, positiv Bezug, negativ Einspeisung
openWB/set/evu/WPhase2 Leistung in Watt für Phase 2, float, Punkt als Trenner, positiv Bezug, negativ Einspeisung
openWB/set/evu/WPhase3 Leistung in Watt für Phase 3, float, Punkt als Trenner, positiv Bezug, negativ Einspeisung
openWB/set/evu/PfPhase1 Powerfaktor für Phase 1, float, Punkt als Trenner, positiv Bezug, negativ Einspeisung
openWB/set/evu/PfPhase2 Powerfaktor für Phase 2, float, Punkt als Trenner, positiv Bezug, negativ Einspeisung
openWB/set/evu/PfPhase3 Powerfaktor für Phase 3, float, Punkt als Trenner, positiv Bezug, negativ Einspeisung
> evu-mqtt: add missing topics

- modules/smarthome/nxdacxx/off.py
- modules/smarthome/nxdacxx/on.py
- modules/smarthome/nxdacxx/watt.py
- runs/mqttsub.py
- runs/smarthomemq.py
- runs/usmarthome/smartnxdacxx.py
- web/settings/smarthomeconfig.php
- web/settings/topicsToSubscribe_smarthomeconfig.js
Erste Unterstützung als Smarthomedevice.
Der Dac N4Dac02 wird mit dem Überschuss über Modbus  angesteuert, und wandelt diesen in eine Spannung zwischen 0,01 und 10,0 Volt um.
> Dac V1 bis V10 in Smarthome

- packages/helpermodules/compatibility.py
- packages/modules/common/abstract_chargepoint.py
- packages/modules/common/b32.py
- packages/modules/common/component_state.py
- packages/modules/common/evse.py
- packages/modules/common/lovato.py
- packages/modules/common/modbus.py
- packages/modules/common/mpm3pm.py
- packages/modules/common/sdm.py
- packages/modules/common/store/_chargepoint.py
- packages/modules/internal_openwb/chargepoint_module.py
- packages/modules/internal_openwb/socket.py
- runs/initRamdisk.sh
- runs/isss.py
Komplette Überarbeitung des ISSS-Daemons:
- Lesen und Schreiben der Ladepunkt-Daten in eigenes Modul ausgelagert. Dies kann bei der Duo für LP 1 und LP 2 initalisiert werden.
- Auslesen des SDM-Zählers erfolgt mit den Methoden aus dem Package-Modul
- neues Modul für den B32 Zähler hinzugefügt
- Lesen und Schreiben der EVSE-Register in eigenem Modul
- Phasenumschaltung und CP-Unterbrechung erfolgt in Threads und blockieren nicht mehr den Daemon.
- Die Buchse erbt die Klasse des internen Ladepunkts und fügt Methoden zum Öffnen und Schließen des Aktors hinzu.
Wenn der ISSS-Daemon stabil läuft, kann auch der redundante Code in buchse.py und autoevse.py damit ersetzt werden.
> rewrite isss daemon

- runs/update.sh
In der `update.sh` gibt es ein `sleep 15`. Warum? Es ist ein Faktor der Updates langsamer macht. Gerade wenn man Änderungen "eben schnell" testen will ist das nervig, dass das Update so lange dauert.
Das ganze kam aus commit 90fd667d0c6a588380e7e80a535e3160e4d928a4, in dem die commit-message "schalte lademodus auf stop bei update start" steht. Damals wurde ein Befehl eingeführt, der den Lademodus auf stop stellt und dann 15 Sekunden wartet. Ich nehme schwer an um darauf zu warten, dass der neue Lademodus aktiv wird. Das hat sich wohl durch das `updateinprogress`-Flag erledigt. Der Lademodus wird zwar noch auf "stop" gestellt, die Regelschleife macht damit aber ohnehin nichts mehr, denn sie bricht wegen dem `updateinprogress`-Flag sofort ab.
Es erscheint mir aber trotzdem schlau ein Update …
> update.sh: Auf die Regelschleife warten statt auf gut Glück zu schlafen

- modules/bezug_e3dc/e3dc.py
- modules/speicher_e3dc/e3dc.py
- packages/modules/common/simcount/__init__.py
- packages/modules/common/simcount/_simcount.py
- packages/modules/common/simcount/_simcounter.py
- packages/modules/common/simcount/_simcounter_state.py
- packages/modules/common/simcount/_simcounter_store.py
- packages/modules/conftest.py
- packages/modules/fronius/bat_test.py
- packages/modules/fronius/counter_s0_test.py
- packages/modules/fronius/counter_sm_test.py
- packages/modules/fronius/inverter_test.py
- packages/modules/kostal_piko/device.py
Der nächste Schritt nach #2349:
Ich habe mir das SimCount-Modul genauer angesehen und mir ist aufgefallen, dass die Klassen `SimCountLegacy` und `SimCount` viel gemeinsame Code haben. Mein Hauptziel war es das ganze so zu überarbeiten, dass der Code de-dupliziert wird. Dazu habe ich:
- Eine Funktion `sim_count` erzeugt, die beide Klassen abdeckt.
- Der Teil der nicht gemeinsam ist, ist der Teil, der sich damit beschäftigt Daten aus Ramdisk und/oder Broker zu laden. Den Teil habe ich in die Klassen `SimCounterStoreRamdisk` und `SimCounterStoreBroker` extrahiert.
Der alter Parameter `data` der Funktion `sim_count` war vom Typ `dict`. Das fand ich ungünstig, da nicht direkt ersichtlich ist, mit welchen Eigenschaften man in diesem Objekt rechnen kann. Ich habe daher eine Klasse …
> refactor simcount for better readability

- regel.sh
Wenn die Regelschleife mehrfach läuft ist das nicht gut. Es kann dazu führen dass diverse Skripte mehrmals laufen, die nicht mehrmals laufen sollten. Zum Beispiel weil sie Modbusverbindungen zu ein und demselben Gerät aufbauen. Oder weil sie gleichzeitig in irgendwelche Dateien schreiben.
Für Huawei-WR taucht der Hinweis auf, man möge die Regelschleife auf langsam stellen. Aber auch andere Geräte können betroffen sein. Gerade wenn man ein Update gemacht hat und die Software neu startet ist es völlig normal, dass die erste Regelschleife sehr langsam läuft, bis diverse Caches gefüllt sind.
Sinnvoll wäre daher, wenn die Regelschleife einfach selbstständig erkennt, wenn sie bereits läuft und ggf. einen Durchlauf überspringt. Das macht dieser PR.
> do not allow the regulation loop to run multiple times in parallel

- modules/soc_aiways/aiways_get_soc.py
The Python module "requests" adds "content-length" headers automatically. There is no need to add them manually to the headers, as the module currently does. In fact, even if you add them manually, they are actually overwritten by mod requests. (And that is good because the static length would otherwise be wrong in most cases and would ruin the transmission.)
> Module soc_aiways: Remove "content-length" from POST request headers

- packages/modules/http/config.py
- packages/modules/http/device.py
ssia. Dient auch als weitere Demo wie `ConfigurableDevice` eingesetzt werden kann.
Nebenbei haben die ganzen HTTP-Config-Klassen `@auto_str` spendiert bekommen, damit die Logausgabe auch lesbar ist.
Das ganze ist noch ungetestet!
> convert HTTP module to configurable device in order to reduce code duplication

- runs/services.sh
`echo "$lastmanagement" > "$OPENWBBASEDIR/ramdisk/issslp2act"`
Aus dieser ramdisk-Datei holt der isss-Daemon die Information, ob eine Duo vorliegt.
`sudo pkill -f '^python.*/isss.py'`
Hier müsste noch unterschieden werden, ob ein Neustart oder Cron5Min vorliegt. Ohne diese Zeile wird nach einem Update der isss-Daemon nicht neu gestartet, sondern nur nach einem Reboot. Kannst Du dir das bitte nochmal anschauen @yankee42 ?
> fix isss for duo

- packages/modules/common/simcount/_simcounter_store.py
@okaegi hat mir geschrieben, dass er festgestellt hat, dass in #2449 bei einem Reboot die Zählerstände verloren gehen. Das habe ich mir dann angesehen und dieser PR soll das beheben.
Der ganz alte Code hat bei fehlendem Sim-Zählerstand diesen aus dem Broker geholt:
https://github.com/snaptec/openWB/blob/f4c822a75ea43e6b55eeb56d8b04476cc9a78edf/loadvars.sh#L1217-L1222
Die aktuelle Logik beherrscht das theoretisch auch:
https://github.com/snaptec/openWB/blob/8e7677f9ae0713fec9b45b91a713d1771046077f/packages/modules/common/simcount/_simcounter_store.py#L139-L144
Der Code wird allerdings nur dann aufgerufen, wenn die `sec0`-Datei existiert:
https://github.com/snaptec/openWB/blob/8e7677f9ae0713fec9b45b91a713d1771046077f/packages/modules/common/simcount/_simcounter_store.py#L134-L137
Bei einem …
> fix: simcount looses counter values on reboot

- .editorconfig
- .github/workflows/github-actions-python.yml
Es kommt immer mal wieder vor, dass PRs geöffnet werden, bei denen die Einrückung gegen die Standard verstößt. Insbesondere Tabs&Spaces.
Dieser PR fügt den existierenden GitHub-Actions eine Überprüfung zu, ob die Einrückung bei den Dateien, die im PR angefasst wurden korrekt ist.
Ich habe mir auch im [Marketplace ein paar GitHub-Actions angesehen](https://github.com/marketplace?type=actions&query=editorconfig) und getestet, die einem etwas Arbeit gegenüber meiner Eigenentwicklung abnehmen, aber nichts davon hat richtig funktioniert. [editorconfig-action](https://github.com/marketplace/actions/editorconfig-action) funktioniert in der neuesten "normalen" Version garnicht. Der Fehler dort ist zwar schon 2019 auf dem Master korrigiert worden, jedoch gab es nie ein Release dazu. Auch die …
> use GitHub Action to check editorconfig compliance

- .github/workflows/github-actions-python.yml
- packages/modules/common/configurable_device.py
- packages/modules/conftest.py
- packages/modules/json/device.py
- packages/modules/json/device_test.py
Umstellung eines weiteren Moduls (JSON) zur Zwecke der Vereinfachung auf `ConfigurableDevice`.
Nebenbei gefixt: Die Component factory durfte keine return-type annotation haben, sonst gab es in der `ComponentFactoryByType` einen Fehler.
Im Live-Betrieb ungetestet, aber diesmal mit ein paar einfach Unittests.
> use ConfigurableDevice for json module to shorten and simplify code

- packages/modules/json/bat.py
- packages/modules/json/counter.py
- packages/modules/json/inverter.py
Wenn man im JSON-Modul Werte produziert, die kein `float` (oder `int` würde wohl auch durchgehen) produziert, dann führt das zu unlustigen Folgefehlern (siehe [Forum](https://www.openwb.de/forum/viewtopic.php?p=74189&sid=6e27938887d9c2fb5a32acb231d903e3#p74189). Mit dem PR wird sofort immer ein `float` aus den gelesenen Werten gemacht. Wann das nicht geht fliegt sofort eine Exception, die die Suche nach der Ursache erleichtert.
> json module: make sure values retrieved are float. Be fail-fast if not.

- modules/smarthome/http/off.py
- modules/smarthome/http/on.py
- modules/smarthome/http/watt.py
- modules/smarthome/nxdacxx/off.py
- modules/smarthome/nxdacxx/on.py
- modules/smarthome/nxdacxx/watt.py
- modules/smarthome/ratiotherm/off.py
- modules/smarthome/ratiotherm/on.py
- modules/smarthome/ratiotherm/watt.py
- modules/smarthome/stiebel/off.py
- modules/smarthome/stiebel/on.py
- modules/smarthome/stiebel/watt.py
- packages/smarthome/smartlog.py
- packages/smarthome/smartret.py
- runs/mqttsub.py
- runs/usmarthome/smartnxdacxx.py
- web/settings/smarthomeconfig.php
HTTP Gerät:
Es wurde auf Python Log umgestellt.
Es wurde im on / off trigger ein Browser Header genommen. Es wurde auf static Types umgestellt.
Dac Gerät:
Es wurde auf Python Log umgestellt.
Neuer Dac typ M120T von Pigeon
Es wurde auf static Types umgestellt.
Ratiotherm WP
Es wurde auf Python Log umgestellt.
Es wurde auf static Types umgestellt.
Stiebel WP
Es wurde auf Python Log umgestellt.
Es wurde auf static Types umgestellt.
Smarthome Config 2.0
Maximaler Speicherladung 30'000
Textkorrektur bei DAC
J/N Hausverbrauch  besser erklärt
> Python Log im Smarthome... diverse Korrekturen

- modules/soc_eq/main.sh
API documentation says only one request all 2 minutes. As we had Returncode 400 Errors on systems using Debug Level 1 / 2 this is the Change to be in the specification
> set interval on debug to 2 Minutes

- modules/soc_psa/main.sh
- modules/soc_psa/psasoc.py
- runs/updateConfig.sh
- web/settings/modulconfiglp.php
Die aktuelle Implementierung des SoC PSA Moduls unterstützt aktuell nur das erste Fahrzeug im Account.
Ist das gewünsche Fahrzeug nicht an der ersten Stelle, ist ein Auslesen des SOC nicht möglich.
Dieses Ticket fügt die VIN als optionalen Eingabeparameter zur API hinzu.
Wurde eine VIN angegeben, wird der SoC für dieses Fahrzeug abgerufen.
Forum SoC Modul: https://openwb.de/forum/viewtopic.php?p=75190#p75190
> Add VIN selector to SoC PSA

- modules/soc_vwid/libvwid.py
Please merge asap.
fix for aan issue since 2022-1124: 
A structure in a response of the login request contains a single "}", which can't be split to a name,value pair.
Added a try-except around the split and ignore such lines.
Tested and works.
> soc_vwid: fix login issue

- regel.sh
- slavemode.sh
* Avoid log spamming with warnings by not accounting for the regulation spread.
* Fix handling of multiple CP current set
All changes _only_ relevant to load control system client mode.
> LM-Client mode: Multi-CP fix and avoid log spam

- loadconfig.sh
- web/settings/settings.php
- zielladen.sh
Ich finde das mit dem Zielladen recht praktisch, beobachte aber, dass das Verhalten nicht optimal ist. Das Laden beginnt zu spät und irgendwann bemerkt es der Algorithmus und muss die Stromstärke hochkorrigieren. Je nach Einstellung der maximalen Ladeleistung ist es dann zu spät und der gewünschte Ladezustand kann nicht mehr erreicht werden.
Meiner Analyse nach liegt das Problem bei mir an zwei Dingen:
1. Der Algorithmus rechnet immer mit einer Effizienz der Ladeelektronik von 100%. Das wird kaum ein Fahrzeug schaffen und entsprechend beginnt die Ladung immer zu spät.
2. Besonders wenn man nur kleine Mengen mit eher hohem Ladestrom lädt, reagiert der Algorithmus zu träge.
Dieser PR beschäftigt sich mit Punkt 1. Es wird ein Feld unter Zielladen ergänzt, welches sonst nur im …
> Zielladen: Wirkungsgrad der Ladeelektronik beachten

- packages/modules/devices/http/api.py
- packages/modules/devices/http/bat.py
- packages/modules/devices/http/counter.py
- packages/modules/devices/http/device.py
- packages/modules/devices/http/inverter.py
Dieser PR enthält 4 commits, die sich mit Verbesserungen am HTTP-Modul beschäftigen.
1. Commit: HTTP module: fix return type of `create_request_function`:
Das ist offenbar ein Fehler, den ich in #2337 reingebracht habe. Vor dem PR konnte das Ergebnis vom Code her nicht `None` sein, von der Signatur her aber schon. Dummerweise hatte ich beides geändert, so dass es wieder nicht passt.
2. Commit: HTTP module: In legacy accept empty path as "none", use configuration default instead of fixed string "none" if option is not set
Es erscheint mir intuitiver das Feld auf der Konfigurationsseite leer zu lassen statt dort "none" reinzuschreiben. Wie offenbar auch [jemand anderes im Forum](https://openwb.de/forum/viewtopic.php?p=75302#p75302). Mit diesem Commit wird ein leeres Feld genau so behandelt …
> HTTP Modul: Akzeptiere leeres Feld, Phasepfade validieren, Code aufräumen und optimieren

- modules/soc_vwid/libvwid.py
- modules/soc_vwid/prepare_libvwid.sh
Hallo Lena, Lutz,
bitte bald mergen, in aktueller Nightly läuft das nicht in python2.
Danke
> soc_vwid: fix python2 syntax problem in libvwid.py

- packages/modules/devices/e3dc/config.py
- packages/modules/devices/e3dc/device.py
- packages/modules/devices/e3dc/external_inverter.py
Inverter Klasse in Inverter und External_inverter aufgetrennt. Read_ext nur noch für V1.9 verwendet
> E3DC openWB 2.0

- nurpv.sh
Wenn ein Ladevorgang an einem oder mehreren Ladepunkten (nur LP 2 oder 3!) aktiv ist und der Ladepunkt 1 gesperrt wird, wurden bisher alle Ladevorgänge unterbrochen. Nach der eingestellten Wartezeit starten die Ladevorgänge dann wieder.
Dieser PR verhindert die Unterbrechung der aktiven Ladevorgänge.
> do not stop charging on additional charge points

- modules/soc_smarteq/README.txt
- modules/soc_smarteq/main.sh
- modules/soc_smarteq/soc_smarteq.py
implement token refresh
improve logging.
mode 0: only errors and warnings are logged
mode 1 (info) delivers in soc.log 1 line per run like:
2022-12-17 11:27:45 INFO:soc_smarteq:Lp2 SOC: 82%@2022-12-17 08:38:44, Method:  2-refresh_tokens 1-get_status
- timestamp of soc-update
- INFO: logging level
- soc_smarteq: module name
- SOC xx%: soc-percent
- @: timestamp of car-server update
- Method: steps done 
- 1-get_status: simplest and fastest step with valid access_token
- 2-refresh-tokens: refresh access token with valid refresh token, then 1-get_status, slightly slower the only 1
- 3-full (re)connect: login with username and password, then 1-get_status, takes considerably more ttime than 1 and 2
3-full reconnect can be avoided by setting both intervals to less than 2 hours, e.g. 90/10!
mode …
> soc_smarteq: implement token refresh, improve logging

- loadvars.sh
- runs/initRamdisk.sh
- runs/mqttsub.py
- runs/updateConfig.sh
- sofortlademodus.sh
- web/settings/sofortconfig.php
- web/settings/topicsToSubscribe_sofortconfig.js
If an et provider has been configured, a new option will show up under each charge point in Einstellungen->Ladeeinstellungen->Sofortladen, which allows to enable charging based on tariff individually (enabled by default).
With this enhancement a master can do load management in a house with multiple external openWBs when they have different electricity providers, but share the same house connection.
> tariff based charging: allow enabling by charge point

- web/settings/savemqtt.php
Damit die Graphen auch ohne Fernzugriffs-Erlaubniss klappen, Es werden hier die für den Graph-Abrufe nörtigen Schreibzugriffe erlaubt.
> Erlaube Graph-Update

- packages/modules/smarthome/lambda_/smartlambda.py
- packages/modules/smarthome/ratiotherm/smartratiotherm.py
Ratiotherm alter PR  (Dynregel = 1) angepasst (auf neuen Verzeichnispfad umgestellt)
https://github.com/snaptec/openWB/pull/2588
Verzeichnispfad von Lambda an neuen Verzeichnispfad Lambda_ angepasst.
Lambda und Ratiotherm überflüssiger print im init entfernt
> smarthome fix

- runs/atreboot.sh
feedback from user recommends to install python3 lxml module via apt-get to avoid memory problems during compile with pip3
> at_reboot.sh: install lxml via apt-get instead via pip3

- modules/soc_evcc/main.sh
- runs/updateConfig.sh
- web/settings/modulconfiglp.php
Fiat requires an app pin for SoC access, so add optional field to enter that pin and only use it if car type is fiat.
> soc_evcc: add pin for fiat

- runs/atreboot.sh
- runs/rse/rseDaemon.py
- runs/services.sh
- following services are only started if not in isss mode:
- smarthome
- rse
- pushbuttons
- isss mode "duo" is only activated if second charge point is configured as modbus or daemon
- configuring virtual IPs is separated from isss mode detection as only setting "isss" has to be considered
- remove virtual IP setup from `atreboot.sh` as `services.sh`is already called and will handle this
- fixes #2608 #2427
> Service cleanup

- regel.sh
- use integer comparison in if statements where possible
- fix check for `ramdisk/lp1anzahlphasen`
- initialize `lp2anzahlphasen` with "0" if everything failed
- fix valid range for `anzahlphasen` (1..23) -> (1..24)
- fix shellcheck warnings and errors in the modified part of regel.sh
> fix phase detection edge cases

- nurpv.sh
Reverts snaptec/openWB#2562
Durch die damalige Änderung werden laufende Ladevorgänge nicht mehr geregelt, wenn LP1 gesperrt wird.
https://www.openwb.de/forum/viewtopic.php?p=82790#p82790
> Revert "do not stop charging on additional charge points"

- web/settings/modulconfigpv.php
Seems like modbus ids 1 to 15 are reserved for standalone or client (if in swarm mode) inverters.
If in "swarm" mode, complete data from all inverters must be retrieved from modbus id 16.
> add note to huawei inverter configuration

- packages/modules/devices/e3dc/counter.py
- packages/modules/devices/e3dc/device.py
- packages/modules/devices/e3dc/external_inverter.py
- packages/modules/devices/e3dc/inverter.py
- added note to not log complete config objecs as it will contain german umlauts ("Zähler")
- changed logging to only print configuration details
- fixed spelling and python naming
> fix logging error with unicode characters

- modules/soc_myrenault/zoenwake.py
Es gibt immer noch Zoes, die fürs laden speziell geweckt werden müssen. Flake8 Anpassungen gemacht und neuste Keys eingeführt
> Wake up Zoe

- web/themes/colors/powergraph.js
Bei Verbrauchern mit unkonventionellen Zähler-Inkrementen (z.B. go-E-Charger) wird der PV-Anteil des Hausverbrauchs nicht korrekt angezeigt. Dieser Fix sollte solche Situationen erkennen und den PV- und Speicher-Anteil korrigieren.
> Colors theme: Fix incorrect PV percentage

- modules/mpm3pmethll/readmpm3pm.py
- modules/mpm3pmethllframer/readmpm3pm.py
- modules/mpm3pmethlls2/readmpm3pm.py
- modules/mpm3pmll/readall.py
- modules/mpm3pmspeicher/readmpm3pm.py
- modules/sdm120modbusll/readsdm3.py
remove missed python3 type annotations in modules running on python2
> fix python2 syntax

- modules/mpm3pmll/readall.py
FileNotFoundError is not defined in python 2
`Except Exception` is bad practice, but we use it here anyway.
> fix python2 FileNotFoundError

- packages/modules/smarthome/acthor/smartacthor.py
- packages/modules/smarthome/avmhomeautomation/smartavm.py
- packages/modules/smarthome/elwa/smartelwa.py
- packages/modules/smarthome/http/smarthttp.py
- packages/modules/smarthome/idm/smartidm.py
- packages/modules/smarthome/lambda_/smartlambda.py
- packages/modules/smarthome/mqtt/smartmqtt.py
- packages/modules/smarthome/mystrom/smartmystrom.py
- packages/modules/smarthome/nxdacxx/smartnxdacxx.py
- packages/modules/smarthome/ratiotherm/smartratiotherm.py
- packages/modules/smarthome/shelly/smartshelly.py
- packages/modules/smarthome/stiebel/smartstiebel.py
- packages/modules/smarthome/tasmota/smarttasmota.py
- packages/modules/smarthome/vampair/smartvampair.py
- packages/modules/smarthome/viessmann/smartviessmann.py
- packages/smarthome/smartbase.py
- packages/smarthome/smartbase0.py
- packages/smarthome/smartcommon.py
- packages/smarthome/smartmeas.py
- runs/smarthomemq.py
Der Smarthomemq.py wurde zerlegt in einen openWB 1.9 Teil und einen zwischen openWB 1.9 und openWB 2.0 gemeinsamen Teil. Die gleiche Einlieferung findet auch für openWB 2.0 statt. Somit soll dieser PR nur für openWB 1.9 verwendet werden Es wurde ein Fehler bei der mindestlaufzeit pro Tag behoben
> smarthome 2.0 openWB 1.9 Zerlegung

- modules/bezug_sungrow/main.sh
- modules/speicher_sungrow/main.sh
- modules/wr2_sungrow/main.sh
- modules/wr_sungrow/main.sh
- packages/modules/devices/sungrow/counter.py
- packages/modules/devices/sungrow/device.py
- packages/modules/devices/sungrow/inverter.py
- web/settings/modulconfigbat.php
- web/settings/modulconfigevu.php
- web/settings/modulconfigpv.php
Doku zum Fix des Auslesens:
https://github.com/snaptec/openWB/issues/2637
Doku zum Fix der Modulkonfiguration:
https://github.com/snaptec/openWB/issues/2714
Bitte um Durchsicht und push falls keine Auffälligkeiten vorhanden sind.
Bei Fragen gerne melden.
> Sungrow Fixes

- packages/smarthome/smartcommon.py
Für Umschaltung manuell auf automatisch wird das smarthome mqtt cache ausgeschaltet, da auch im Online umgeschaltet werden kann und somit das Cache nicht immer synchron ist.
> Umschalten auf automatisch um 23:59

- packages/modules/smarthome/idm/off.py
- packages/modules/smarthome/idm/on.py
- packages/modules/smarthome/idm/smartidm.py
- packages/modules/smarthome/idm/watt.py
- packages/smarthome/smartbase.py
- packages/smarthome/smartcommon.py
Neu wird IDM die aktuelle PV Leistung (Register 78) zusätzlich übergeben, Die PV Leistung ist für Smarthome nicht steuernd. Der idm treiber wurde vereinfacht. der Branch kann auch für openwb 2.0 übernommen werden, in mainloop wird die PV Leistung mit 0 vorbelegt. Die nötige Änderung in openwb 2.0 kommt dann noch.
https://openwb.de/forum/viewtopic.php?p=88834#p88834
> idm....mit PV Leistung

- modules/bezug_sungrow/main.sh
- modules/speicher_sungrow/main.sh
- modules/wr_sungrow/main.sh
- packages/modules/devices/sungrow/config.py
- packages/modules/devices/sungrow/device.py
- web/settings/modulconfigpv.php
[https://www.openwb.de/forum/viewtopic.php?p=90527#p90527](https://www.openwb.de/forum/viewtopic.php?p=90527#p90527)
> configurable port for sungrow

- packages/modules/internal_chargepoint_handler/clients.py
use /dev/serial0 as fallback if no other serial devices are present
> backport client_factory

- packages/smarthome/smartbase.py
Grundsätzlich werden nun beim statusupdate von einem Gerät die nicht definierten temperatur sensoren  (>device_temperatur_configured) initialisiert. Ursprünglich wurde das nur beim deaktivieren und aktivieren von einem Gerät gemacht. Kann für Openwb1.9 und Openwb 2.0 übernommen werden. Damit sollten keine Temperatur anzeigen mehr im Gui hängen bleiben.
> smarthome temperatur

- packages/modules/smarthome/nxdacxx/smartnxdacxx.py
- packages/modules/smarthome/nxdacxx/watt.py
Anpassung nach Forumsdiskussion
https://openwb.de/forum/viewtopic.php?p=95934#p95934 Für openwb 1.9 und 2.0
> smarthome dactype = 3 anpassung

- packages/modules/smarthome/shelly/off.py
- packages/modules/smarthome/shelly/on.py
- packages/modules/smarthome/shelly/watt.py
Kann für openwb 1.9 und openwb 2.0 übernommen werden. Shelly gen 2 verwenden andere on / off http cmds als gen1. Die sind nun angepasst. Shelly pro 3em ist noch etwas speziell er kann auf drei verschiedenen Kanälen die Leistung zurückliefen und es kann noch ein optionales add on verbaut werden, damit er schalten kann. Den Shelly pro 3em sollte so erfasst werden.
fall a) Nur Leistungsmessung
Unter separater Leistungsmessung dann dort Meter Auswahl den jeweile Kanal erfassen. Auswahl: Meter summiert oder Meter 2 bis 4 das entspricht -> Summe aller Leistung pro phase oder Leistung A,B, C alleine) 
fall b) Leistungsmessung und Schalten (geht nur mit  shelly addon zum schalten ) 
Shelly im gleichen Gerät zweimal erfassen. Einmal als separate Leistungsmessung wie im fall a und im oberen Teil …
> smarthome shelly gen2 support und 3pro em mit add on

- packages/modules/smarthome/acthor/watt.py
Sofern die installierte Leistung grösser als die maximal Leistung vom Acthor ist, wird ggf die CAP angepasst, da sonst der Heizstab nicht voll ausgereget wird. Kann für 1.9 und 2.0 übernommen werden
> acthor installierte Leistung > maximal Leistung

- packages/modules/devices/solaredge/device.py
Seems like SE needs some time before a new connection can be established. Tested with 2.0s down to 1.0s and 1.2s might be okay and stable. This PR only considers `read_legacy()`.
This is only a quick and dirty fix. Only one connection should be used also in legacy mode.
- add delay for inverter components (only one connection per inverter used)
- use inverter connection for battery if same ip configured
> fix reconnection delay

- packages/modules/smarthome/nxdacxx/watt.py
Bei Dac DA02 wird neu auch die bisherige Leistungsaufnahme in die Berechnung von 0 - 10 V mit einbezogen um Schwingen zu vermeiden.
Kann für 1.9 und 2.0 übernommen werden.
https://forum.openwb.de/viewtopic.php?p=103457#p103457
> Dac typ = 02

- packages/modules/smarthome/lambda_/watt.py
fix for pymodbus endian class (changes once 2023 august to enum to uppercases only,
checked during runtime,
not compatible between openwb 1.9 want lowercases ( -> BinaryPayloadBuilder(byteorder=Endian.big) and openwb 2.0 (wants upercase ( -> BinaryPayloadBuilder(byteorder=Endian.BIG)
auto = "@"
big = ">"
little = "<"
Als Lösung werden die Konstanten Werte aus der endian class (die die letzten Jahre unverändert geblieben sind) selber übergeben
siehe auch
https://forum.openwb.de/viewtopic.php?p=104639#p104639
> lambda pymodbus

- modules/soc_i3/i3soc.py
- modules/soc_i3/main.sh
> BMW-SOC-Module: fix authentication

- openwb-install.sh
Bei einer aktuellen Neuinstallation unter Buster wird ohne Eingrenzung der paho-mqtt Version die aktuelle Version 2.1.0 gezogen. Zwischen Version 1,6 und 2.0 gibt es breaking Changes die Anpassungen in verschiedenen Sourcen erforden würden. Durch die Anpassung wird die aktuellste verfügbare Version <2.0.0 für die Installation herangezogen.
> Update openwb-install.sh fixieren von paho-mqtt<2.0.0

- modules/soc_ovms/main.sh
- modules/soc_ovms/soc_ovms.py
- runs/updateConfig.sh
- web/settings/modulconfiglp.php
SoC-Module for OVMS.
This will be an alternative for the smarteq Module, which will become obsolete after 31.12.2024, when Smart/Mercedes will stop the Smart Control Center Infrastructure.
There are users of openWB 1.9 considering the OVMS alternative.
> SoC module for OVMS

- web/settings/saveconfig.php
> check for valid modules

- modules/soc_ovms/soc_ovms.py
initial token creation was failing - fixed
make registered token cp specific to allow ovms soc modules on lp1 and lp2 without interference of token
> soc_ovms: fix initial token creation, add cp to token appl

- modules/soc_ovms/main.sh
- modules/soc_ovms/soc_ovms.py
Kleine Korrekturen:
main.sh: Doppelte Ausführung entfernt
soc_ovms.py: unzutreffender Kommentar korrigiert.
Bitte bald mergen - Danke
> soc_ovms: fix double execution and comment

- modules/soc_vwid/main.sh
Die Ausführung als user www-data beim Speicher der LP Konfiguration führt immer wieder zu Permission Problemen.
Diese Änderung führt das Modul immer als user pi aus, auch beim Speichern der Konfiguration.
> soc_vwid: main.sh - always execute as user pi

- modules/soc_i3/i3soc.py
use the same session-id in all soc requests to avoid login with new captcha after some time
added session-id to store file
> soc_i3: use same session-id in all requests
